### ISSUE TITLE
Deduplicate - find next perfect square

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#100]
1. [Find the next perfect square!](https://www.codewars.com/kata/56269eb78ad2e4ced1000013)
- 7kyu. Only inputs which are themselves perfect squares are valid, otherwise -1 should be returned.
- Satisfaction: 89%
- 7 pending issues, most of them related to C# translation, but I am not sure how valid they are.
- 105k completions
- 12 languages + 3 pending translations.
- Published Oct 2015, author inactive.

2. [nextPerfectSquare](https://www.codewars.com/kata/599f403119afacf9f1000051)
- 7kyu. Negative inputs should return 0. Non-perfect squares are valid inputs.
- Satisfaction: 93%
- 2 pending issues.
- ~850 completions.
- 5 languages, all of them overlapping with 1. (this kata has an approved C translation, and C translation is pending in 1.). No pending translations.
- Published Aug 2017, author last active 2-3 months ago.

-----

### Conclusion

- Keep [Find the next perfect square!](https://www.codewars.com/kata/56269eb78ad2e4ced1000013).
- [x] Retire [nextPerfectSquare](https://www.codewars.com/kata/599f403119afacf9f1000051)

**Comment by ejini6969** [comment]
Retire 2. due to less completions & less languages

**Comment by EloiseRosen** [comment]
vote for retire 2 - they both seem fine but 1 has more languages

**Comment by benjaminzwhite** [comment]
Vote for retire 2 - the C# issues with kata 1 are claimed to have been addressed as of 1 hour ago by new fork:

[Comment by NikCSharp on C# fork](https://www.codewars.com/kata/56269eb78ad2e4ced1000013/discuss/csharp#62e83ce816d2d600297b697f)

**Comment by Nik-Sharp** [comment]
Vote to retire 2 - Less completions, less languages, and was posted later than the first kata

**Comment by akar-0** [comment]
retire 2.
