### ISSUE TITLE
Deduplicate - Finding anagrams of a word

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#101]
1. [Arrh, grabscrab!](https://www.codewars.com/kata/52b305bec65ea40fe90007a7)
- 6kyu.
- Satisfaction 94% with ~4k solutions.
- 1 pending issue.
- 8 languages, no pending translations. Exclusive Groovy, Julia.
- Published Dec 2013, author inactive.
2. [Where my anagrams at?](https://www.codewars.com/kata/523a86aa4230ebb5420001e1)
- 5kyu
- Satisfaction 89% with ~76k solutions.
- 12(!) pending issues.
- 11 languages + 7 pending translations
- Published Sep 2013, author inactive.

Both kata seem to be exact duplicates, I was able to pass both with the same code. I did not check if either of the kata has any performance requirements or anything what would justify difference in rankings.

ADDED: 

3. [Lorraine Wants to Win the TV Contest](https://www.codewars.com/kata/562dbaf65d4ab6685c0000ed)
- 7 kyu
- The task suggests some performance requirements but it does not seem to be enforced in languages I tested
- Satisfaction 91% with 450+ completions
- 2 reported, pending issues , but while solving the kata I already found two more
- 3 languages (none unique), no pending translations
- Published Nov 2015, author active

If possible, please update your post with an explicit statement, so I would know that this kata is accounted for even though it was added in late. If there will be not enough votes, I think I will just start another round between 1. and 3. some time later.

-----

### Conclusion

- Keep 1. [Arrh, grabscrab!](https://www.codewars.com/kata/52b305bec65ea40fe90007a7)
- [x] Retire 2. [Where my anagrams at?](https://www.codewars.com/kata/523a86aa4230ebb5420001e1)
- No conclusion about 3. [Lorraine Wants to Win the TV Contest](https://www.codewars.com/kata/562dbaf65d4ab6685c0000ed), probably will stay or will be processed in another round.

### Filling gaps

- [x] Move ObjectiveC translation
- [x] Move CoffeeScript translation
- [x] Move PHP translation
- [x] Move R tranlation
- [x] Move LUA pending translation
- [x] Move Clojure pending translation
- [x] Move Scala pending translation
- [x] Move F# pending translation
- [x] Move Java pending translation

**Comment by hobovsky** [comment]
I vote to keep 2. because it has more available languages, fix as many issues as possible, and transfer missing translations from 1.

I did not check how both kata differ in terms of quality, but I do not expect them to be very different: both are old, and good tests are tricky enough to write I don't suppose anyone bothered to write rich tests in any of both kata.

Ad 3: I vote retire because despite its promises, the kata does not deliver: JS passes with the most trivial algorithm and no preprocessing, and tests are structured incorrectly (nested `it` blocks what leads to messed up, red/green test output).

**Comment by Madjosz** [comment]
I vote to keep 1. Problems with 2:
* ranking is way too high
* No random tests in Python, JS (vs. present in 1)
* Old test framework in Python, JS (vs. new in 1)

**Comment by hobovsky** [comment]
> I vote to keep 1.

Voting this way is totally fine, but please consider difference in maintenance cost: copying a dozen of languages from 2. to 1. vs copying/adding/fixing tests (from 1.) to 2.

**Comment by ejini6969** [comment]
I vote to keep 1 either, since only CS, Go, Rust, R, Objective-C and PHP require transferring in which I believed they're mostly all in bad shape (no random tests and do not cover edge cases (if any?) ) so maybe we can discard those languages if maintaining them is impossible. Also, the rank is inappropriate IMO!

EDIT : Retire 3 due to same solution in the other one able to pass, plus abit under-ranked and less languages

**Comment by CiprianAmza** [comment]
The second kata has 12 pending issues and seems a bit overranked, but the issues are about missing tests. Given the fact that they are complete duplicates, one should probably be removed. Maybe the second.

**Comment by Kacarott** [comment]
Honestly the main reason to keep option 2, would be that option 1 has a terrible, unsearchable name. I think I am going to vote to keep option 2, despite it being over-ranked.

**Comment by Blind4Basics** [comment]
we could change the title of 1, couldn't we?
I'd prefere to get rid of 2 as well, even if that means losing a (solid) bunch of languages. Maintenance cost is too high on this one.

**Comment by akar-0** [comment]
keep 1 only.

> we could change the title of 1, couldn't we?

Katas can be renamed easily apparently, I did it on [this kata](https://www.codewars.com/kata/57dab71714e53f4bc9000310) (originally named *Rotate, Remove, Re**r**urn*) and there has been no problem.

**Comment by EloiseRosen** [comment]
vote for retire 2 (due to rank, random tests, issues), rename 1

**Comment by benjaminzwhite** [comment]
Vote for retire 2 also: rank/issues. 

Agree with renaming 1 also if it's easy as akar-0 says: something like "Find all anagrams of a word" so it's searchable.

**Comment by hobovsky** [comment]
Votes are clear enough: keep 1., retire 2. This also means some effort before requesting retirement:

- Move ObjectiveC translation
- Move CoffeeScript translation
- Move PHP translation
- Move R tranlation
- Move LUA pending translation
- Move Clojure pending translation
- Move Scala pending translation
- Move F# pending translation
- Move Java pending translation
- Consider renaming to some more searchable title

Any help with moving the translations, or ideas to make the transition smooth, are welcome. For example, maybe we don't need to move pending translations which are bad and would be rejected anyway? Which ones would be such?

**Comment by ejini6969** [comment]
Clojure and Java are in bad shape (no random tests) so maybe they can be rejected if not salvageable. Also, CS, PHP and R transferred and awaiting approval !

**Comment by Blind4Basics** [comment]
[java translation](https://www.codewars.com/kumite/62f2b72c2b0c79000e391dcf?sel=62f2b72c2b0c79000e391dcf), compliant with TS (almost).
(damn, I forgot how painful java is, when done directly on CW... x/ )

**Comment by KayleighWasTaken** [comment]
The Scala pending translation needs to be redone, it's 5 years old and in Scala 2. I can quickly remake it in Scala 3 if desired.

**Comment by KayleighWasTaken** [comment]
I think that 3 should probably be kept? It's distinct enough from the others I think, though maybe we could modify the tests to actually require performance.

**Comment by fcr--** [comment]
[Lua translation](https://www.codewars.com/kumite/62fba2e3679adf00312f26f4?sel=62fba2e3679adf00312f26f4) including random test cases which were not part of the original translation + a few refactors here and there to make it nice.

**Comment by fcr--** [comment]
PS: I would vote for keeping 1 and removing 2 and 3
