### ISSUE TITLE
Deduplicate - Narcissistic number

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#102]
1. [Does my number look big in this?](https://www.codewars.com/kata/5287e858c6b5a9678200083c)
- 6kyu
- Satisfaction 91% with almost 100k completions
- 6 pending issues
- 16 languages + 6 pending translations
- Published Nov 2013, author active

2. [Narcissistic Numbers](https://www.codewars.com/kata/56b22765e1007b79f2000079)
- 7kyu
- Satisfaction 94% with 6.5k solutions
- No pending issues
- 9 languages + 5 pending translations. Julia and Golang exclusive.
- Published Feb 2016, author last active Apr 2022.

Both tasks seem to be exact duplicates.

### Conclusion

- Keep 1. [Does my number look big in this?](https://www.codewars.com/kata/5287e858c6b5a9678200083c)
- [x] Retire 2. [Narcissistic Numbers](https://www.codewars.com/kata/56b22765e1007b79f2000079)

### Filling gaps

- [x] Transfer Julia translation
- [x] Transfer Go translation

**Comment by hobovsky** [comment]
Vote to keep 1. as more complete. Retire 2. as an exact duplicate, transfer missing translations to 1.

**Comment by ejini6969** [comment]
Same opinion as hobs

**Comment by CiprianAmza** [comment]
I agree with keeping only the first one. It has more solutions and more translations. Not sure if the rank should be kept as 6 kyu in comparison with the today new katas rank.

**Comment by Blind4Basics** [comment]
same

**Comment by akar-0** [comment]
keep 1, retire 2.

**Comment by EloiseRosen** [comment]
vote for retire 2

**Comment by hobovsky** [comment]
Consensus is quite clear: keep 1., retire 2. I will request retirement after gaps between existing translations are filled:
- Transfer Julia translation
- Transfer Go translation

Additionally, pending issues could be reviewed and addressed where necessary. Maybe we could also think of some better (i.e. searchable) title?

**Comment by akar-0** [comment]
Done for Go.

**Comment by akar-0** [comment]
I left a message to stellartux (author of the Julia translation) to ask him to transfer his translation. It's better if he can do it himself. Though, it seems he hasn't been active for a about 3 weeks.

**Comment by akar-0** [comment]
About the title, I like the current one because it's funny pun, in relation with the name of those numbers. Maybe just append *(narcissistic numbers)* to the title?

**Comment by ejini6969** [comment]
@hobovsky I think the first one alr had C#, instead it should be `transfer TypeScript translation`

**Comment by JulianNicholls** [comment]
As the author of 'Does my number look good in this', I would vote for mine being kept. Mine also predates the other one by 3 years.

**Comment by hobovsky** [comment]
> @hobovsky I think the first one alr had C#, instead it should be `transfer TypeScript translation`

I think I messed up something when comparing available languages, probably got lost between tabs. Both C# and TS translations are there in the target kata. I can't also find the trace of Golang in the source kata :| But still, Julia needs to be moved.

Thanks for help everyone, and sorry for confusion.

**Comment by akar-0** [comment]
> @hobovsky   I can't also find the trace of Golang in the source kata :| But still, Julia needs to be moved.

I was the author of the translation in the other kata, I just unpublished it when I did the transfer. Sorry, I should
 have mentioned it.

**Comment by hobovsky** [comment]
> I left a message to stellartux (author of the Julia translation) to ask him to transfer his translation. It's better if he can do it himself. Though, it seems he hasn't been active for a about 3 weeks.

It seems that stellartux moved the translation, so I can ask for retirement of the duplicate kata :)
