### ISSUE TITLE
Send "Cigar Strings(easy)" back to beta / draft

### ISSUE THREAD

**Issue by ejini6969** [codewars/content-issues#103]
[Cigar Strings(easy)](https://www.codewars.com/kata/5b64d2cd83d64828ce000039/discuss/python)

1. The description is basically a complete fuss!
i) Did not mention how `SAM formatting` works in the current context
ii) Mentioned about `read from sample file` which makes users mis-thought of doing so, instead, what they meant is the parameter given is called `read`
iii) Did not mention what type of `flags` are part of the cigar string
iv) Did not mention the meaning of each of those `flags` as per se in the random tests
v)  `determines whether a cigar string fully matches the reference and accounts for all bases`. What is the correct format for such base? What is the criteria for matching??? Description explains a lot of irrelevant stuff but do not touch this point!
vi) Inconsistency in description regarding the output in python && C++.

2. Test cases and language
 i) Python new test framework should be used
ii) Example and fixed tests should provide samples on all the cigar types same as those in the random tests
iii) The output being "True", "False" in C++ are odd and should be replaced with something else

3. Novelty
 The task is basically just another duplicate of "sum of integers in string" with weird pattern matching that are combination of at least 
 3 different tasks, which is very artificial and violates the "do one thing, and do it well" policy!

Now, the thing is, if you think this kata is salvageable from its current state (send back to beta and not draft mode), please vote as such ( no -> 👎, yes ->👍)

**Conclusion**
- [x] Retire [Cigar Strings(easy)](https://www.codewars.com/kata/5b64d2cd83d64828ce000039/discuss/python)

**Comment by akar-0** [comment]
I think this is typically the kind of pointless katas that deserve a mere retirement.

**Comment by EloiseRosen** [comment]
Just did this kata. My review is, uh, yes let's retire.

**Comment by benjaminzwhite** [comment]
Just solved this to see what's going on - yes, please retire; basic string/regex task hidden behind confusing description and strange input/output formats. 

It seems like author originally wanted to do a series on bioinformatics, which might have been nice, but never followed up - as it stands, it actually makes me want to **not** learn more about bioinformatics.

**Comment by Blind4Basics** [comment]
I actually liked that one... Mostly because of the context...
But yeah, it's in very bad shape. I also believe that the random tests always expect False without even checking if the random input is valid or not... And looking at the stats, ~~I guess it cannot leave beta anymore~~ (oops, just woke up, sorry x) ), so let's retire it.

**Comment by ejini6969** [comment]
From @KayleighWasTaken on [discord](https://discord.com/channels/846624424199061524/850643940209328148/1006922808737148959)
`Retire imo `
