### ISSUE TITLE
Deduplicate - isomorphic strings

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#104]
1. [Check if two words are isomorphic to each other](https://www.codewars.com/kata/59dbab4d7997cb350000007f)
- 6kyu
- Satisfaction 94% with 630 solutions
- 2 pending issues
- 4 languages, Haskell-exclusive, lacks C# translation
- Published Oct 2017, author inactive.

2. [Word Patterns](https://www.codewars.com/kata/562846dd1f77ab7c00000033)
- 6kyu
- The task slightly differs but all the difference boils down to one call to `split`
- Satisfaction 95% with 780 completions
- 2 pending issues
- 4 languages, all languages overlap with 3.
- Published Oct 2015, author active

3. [Simple Fun #31: Is Substitution Cipher?](https://www.codewars.com/kata/58870742c815166a960000af)
- 6kyu
- Satisfaction 95% with 170 solutions
- 1 pending issue
- 5 languages, Crystal-exclusive
- Published Jan 2017, author inactive

I was able to solve all kata in Python with identical code (with an almost trivial modification for 2.).  
The 3. is mentioned by ejini to "require effort to find the correct algorithm", but I am not sure what this would mean.  
One matter to discuss is, is 2. similar enough to be considered a duplicate?

### Conclusion

- Keep [Check if two words are isomorphic to each other](https://www.codewars.com/kata/59dbab4d7997cb350000007f)
- [x] Retire [Word Patterns](https://www.codewars.com/kata/562846dd1f77ab7c00000033)
- [x] Retire [Simple Fun #31: Is Substitution Cipher?](https://www.codewars.com/kata/58870742c815166a960000af)

**Comment by benjaminzwhite** [comment]
I just solved all three katas in Python - my same solution passes all 3. Number 2, as you said, is just about `splitting` the second input, so I vote that it's **not** different enough.

My vote would be to keep 1 - the description is clearest, the title is evocative and searchable. The description of 3 isn't great.

Also - kata 1 needs updating to new test framework in Python: I can do this if you want, but it will be my first such modification - so can I confirm the steps I should take: 

I fork the kata -> update the tests -> then post in discourse + Discord a link to my fork for approval -> Then once fork is approved I remove it from the Ejini Github list of kata to update, is that all correct?

I note also your recent issue to fix the random tests in Python, so they don't all expect `False`

**Comment by ejini6969** [comment]
By that -> ` "require effort to find the correct algorithm"` I meant it's tagged as puzzle so I thought the mind-map to come up with the solution is not so obvious! But as mentioned by benjamin above, the description for `1` is the clearest as it mentioned about the definition of `isomorphic`.

So, I vote to keep 1 since 2 has an unclear description despite slightly higher completion and 3 might be a copy of a problem from external sites (refer to #42)

**Comment by Blind4Basics** [comment]
3 is missing an edge case that's is showing up _one_ time in both 1 and 2 (`"aaa" "bbbb"`).

keep 1, yeah.

**Comment by akar-0** [comment]
keep 1 only.

**Comment by EloiseRosen** [comment]
vote for keep 1, retire the others

**Comment by hobovsky** [comment]
With 5 votes I think the conclusion is clear to keep 1. and retire 2. and 3. I will request retirement after gaps are filled:

- [x] Move C# translation to 1. (from 2. or 3.)
- [x] Move Crystal translation from 3.

**Comment by hobovsky** [comment]
Moved Crystal translation.
Moved C# translation.
