### ISSUE TITLE
Deduplicate - Hanoi record

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#111]
1. [Hanoi record](https://www.codewars.com/kata/534eb5ad704a49dcfa000ba6)
  * 6kyu
  * 84% with 1.5k completions
  * 1 pending issue
  * 11 languages + 6 pending translations, covers all languages available in 2.
  * Published Apr 2014, author active

2. [Tower of Hanoi](https://www.codewars.com/kata/5899f1df27926b7d000000eb)
  * 7kyu
  * 89% with 1k completions
  * No pending issues
  * 7 languages + 1 pending translation, all languages are present in 1.
  * Published Feb 2017, author inactive

The kata are exact duplicates.

-----

### Conclusion

- Keep 1. [Hanoi record](https://www.codewars.com/kata/534eb5ad704a49dcfa000ba6)
- [x] Retire 2. [Tower of Hanoi](https://www.codewars.com/kata/5899f1df27926b7d000000eb)

There are no translations to transfer.

**Comment by hobovsky** [comment]
The only difference between the kata is their rank, and I think 7 kyu is more suitable.

Still, I vote to keep 1. as more complete and retire 2. Maybe the rank can be maintained at least a bit by adding tests resulting in potential overflow when calculating `2^MAX_INT_SIZE - 1`, and maybe constructing tests in a way to not make the pattern too apparent.

Keeping 2. because of a better rank is also OK, but this would mean moving 4 approved and 5 pending translations.

**Comment by akar-0** [comment]
Keep 1, for having much more languages available.

Probably (but independently), on tests causing overflow should be added in languages where it is possible, but it doesn't change much (one test is easy to hardcode).

**Comment by KayleighWasTaken** [comment]
1 seems better to keep to me as well.

**Comment by EloiseRosen** [comment]
vote for keep 1

**Comment by khanhtranngoccva** [comment]
> The only difference between the kata is their rank, and I think 7 kyu is more suitable.
> 
> Still, I vote to keep 1. as more complete and retire 2. Maybe the rank can be maintained at least a bit by adding tests resulting in potential overflow when calculating `2^MAX_INT_SIZE - 1`, and maybe constructing tests in a way to not make the pattern too apparent.
> 
> Keeping 2. because of a better rank is also OK, but this would mean moving 4 approved and 5 pending translations.

I think the test for 1 can feature large numbers, forcing the user to use modular arithmetic to solve (just like in *BECOME IMMORTAL*) and then the 6 kyu kata can safely move up 1 rank.

**Comment by Kacarott** [comment]
I vote to keep 1, retire 2

**Comment by ejini6969** [comment]
Keep 1

**Comment by Blind4Basics** [comment]
keep 1.
