### ISSUE TITLE
Deduplicate - acronym

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#112]
1. [makeAcronym](https://www.codewars.com/kata/557efeb04effce569d000022)
* 7kyu
* input with invalid types (really annoying), and invalid characters
* 88% with 1.6k completions
* 1 pending issue
* 4 languages (Exclusive approved CoffeScript, Ruby)
* Published Jun 2015, author active

2. [Make acronym](https://www.codewars.com/kata/57a60bad72292d3e93000a5a)
* 7 kyu
* valid inputs only
* 88% with ~1k completions
* 2 pending issues
* 4 languages (2 unique) + 2 pending translations (both unique)
* Published Aug 2016, author last active May 2022

----

### Conclusion:

- [x] Retire 1. [makeAcronym](https://www.codewars.com/kata/557efeb04effce569d000022)
- Keep 2. [Make acronym](https://www.codewars.com/kata/57a60bad72292d3e93000a5a)

### Filling gaps

- [x] Move CoffeeScript approved translation from 1. to 2.
- [x] Move Ruby approved translation from 1. to 2.

**Comment by hobovsky** [comment]
Kata 1. has a very annoying requirement of input validation and throwing all kind of crap into user solution, so if this kata is decided to be kept, I'd vote to remove this requirement.
Random tests in kata 2. generate inputs expecting answers of only 1 character or 2 characters long, so maybe could be improved.

I am slightly inclined to keep 2. due to smaller effort required to move languages and no input validation.

**Comment by Blind4Basics** [comment]
retire 1.
Because transferring languages of 2 to one means opening issues in one about lack of random tests in those langauges

**Comment by ejini6969** [comment]
2 should be kept due to no input validation and translating to typed languages are less tedious !

**Comment by Kacarott** [comment]
retire 1

**Comment by EloiseRosen** [comment]
vote for retire 1

**Comment by akar-0** [comment]
keep 2 only.

**Comment by hobovsky** [comment]
From @KayleighWasTaken [on Discord](https://discord.com/channels/846624424199061524/1006915524371947650/1006916344706519110):

> Not logged in to gh on phone but I vote we keep kata 2 
> Can fix the stuff with it's tests

**Comment by hobovsky** [comment]
From **Glinator** [on Discord](https://discord.com/channels/846624424199061524/1006915524371947650/1006917454414491739):

> Kata 1 can't be translated to languages with stricter typing because of its messy inputs.
> Also isn't the description of Kata 2 a bit to precise ? I mean for a 7 kyu I feel like having the algorithm already given in the description is a bit too much

**Comment by KayleighWasTaken** [comment]
> From @KayleighWasTaken [on Discord](https://discord.com/channels/846624424199061524/1006915524371947650/1006916344706519110):
> 
> > Not logged in to gh on phone but I vote we keep kata 2
> > Can fix the stuff with it's tests

Can confirm is me.

**Comment by wtlgo** [comment]
Keep 2
