### ISSUE TITLE
Deduplicate - Divide by two numbers

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#113]
1. [Is n divisible by x and y?](https://www.codewars.com/kata/5545f109004975ea66000086)
* 8kyu
* positive integers only
* 91% with ~74k completions
* 1 pending issue
* 43 languages + 2 pending translations
* Published May 2015, author inactive

2. [Can we divide it?](https://www.codewars.com/kata/5a2b703dc5e2845c0900005a)
* 8kyu
* Positive and negative integers
* 93% with 47k completions
* 3 pending issues, one about being a duplicate of 1.
* 13 approved languages, 3 pending translations, all languages are covered in 1.
* Published Dec 2017, author inactive

----

### Conclusion

- Keep 1. [Is n divisible by x and y?](https://www.codewars.com/kata/5545f109004975ea66000086)
- [x] Retire 2. [Can we divide it?](https://www.codewars.com/kata/5a2b703dc5e2845c0900005a)

**Comment by Kacarott** [comment]
Keep 1, due to many translations

**Comment by KayleighWasTaken** [comment]
Keep 1, more translations

**Comment by ejini6969** [comment]
Keep 1

**Comment by Blind4Basics** [comment]
keep 1

**Comment by EloiseRosen** [comment]
vote for keep 1

**Comment by wtlgo** [comment]
Keep 1
