### ISSUE TITLE
Deduplicate - is a palindrome?

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#114]
1. [Palindrome Strings](https://www.codewars.com/kata/57a5015d72292ddeb8000b31)
* 8kyu
* palindrome can be a word or an integer, case sensitive
* 91% with ~18k completions
* 1 pending issue
* 7 languages + 1 pending translation, none unique
* Published Aug 2015, author inactive

2. [Is it a palindrome?](https://www.codewars.com/kata/57a1fd2ce298a731b20006a4)
* 8kyu
* case-insensitive words
* 93% with ~25k completions
* 1 pending issue with a reported pending bugfix
* 15 languages + 9 pending translations
* Published Aug 2016, author last active May 2022

3. [Numerical Palindrome #1](https://www.codewars.com/kata/58ba6fece3614ba7c200017f)
* 7kyu
* only numbers are valid inputs, anything else is invalid. Part of a series.
* 92% with ~3.5k completions
* 1 pending issue
* 6 languages + 1 pending translation (exclusive Julia)

4. [Palindrome Sentences](https://www.codewars.com/kata/588b4ab855d1d9912e000027)
* beta
* input is a sentence, punctuation does not contribute to being a palindrome or not
* 83% with 105 completions
* 1 pending issue about being a duplicate
* python only
* Published Jan 2017, author active

5. [Palindrome for your Dome](https://www.codewars.com/kata/53046ceefe87e4905e00072a)
* 6kyu
* `reverse` is restricted in available languages
* 92% with 2.6k completions
* 2 pending issues
* 3 languages, no pending translations
* Published Feb 2014, author last active May 2022

6. [99 Problems, #6: detecting a palindrome list](https://www.codewars.com/kata/57d9951f3c3f9666e9000017)
* 8kyu
* presumably "FP-oriented" (whatever this would mean), input is a list, solution is expected to support generics
* 81% with 300+ solutions
* 1 pending issue with a reported fix
* Approved OCaml and F# only, JS translation is reported but I am not sure it fits idea of the kata. All are present in 2.
* Published Sep 2016, author inactive

----

### Conclusion

- [x] Retire 1. [Palindrome Strings](https://www.codewars.com/kata/57a5015d72292ddeb8000b31)
- Keep 2. [Is it a palindrome?](https://www.codewars.com/kata/57a1fd2ce298a731b20006a4)
- [x] Retire 3. [Numerical Palindrome #1](https://www.codewars.com/kata/58ba6fece3614ba7c200017f)
- [x] Retire 4. [Palindrome Sentences](https://www.codewars.com/kata/588b4ab855d1d9912e000027)
- Keep 5. [Palindrome for your Dome](https://www.codewars.com/kata/53046ceefe87e4905e00072a)
- [x] Retire 6. [99 Problems, #6: detecting a palindrome list](https://www.codewars.com/kata/57d9951f3c3f9666e9000017)

### Filling gaps

- ~~[ ] Move Julia pending translation from 3. to 2.~~ - the translation is bad and not really salvageable, it would be better to just create a new one.
- [x] Remove code restriction from 5.

**Comment by hobovsky** [comment]
Kata 1. is somewhat annoying due to mixed input types.
Kata 2. is OK, but limited to words and not sentences.
Kata 3 I did not like because of working only with numbers, needs input validation, and mixed output types
Kata 4 is nice because it works with sentences, but it's basically duplicate of 5.
Kata 5. I liked the most because it works with sentences, but has just a few languages and a code restriction which I am not sure is necessary
Kata 6 would be good if it sticks to idea of expecting a generic solution for homogenous lists of any type, but I am afraid it will end up as a bag of everything: generics, explicitly typed inputs, and heterogenous lists in dynamically typed languages.

I vote to retire 1., 3., and 4.
Kata 2. seems to be most complete, so probably is the best candidate to keep.
I have no opinion on kata 5. I like how inputs are sentences (and I like palindrome sentences :) ) but I can see how it can be too close to 2. I also think that blocking `reverse` is not necessary.
I slightly lean towards keeping 6. with a remark that it would be nice if kept generic.

**Comment by ejini6969** [comment]
Keep 2 due to highest completion and most languages

Retire 1. && 3. due to different input types and validations required.

Retire 4. due to least language & completion

I have no strong opinion on 5. but I agreed disabling `reverse` is annoying. If the restrictions are removed, I think it can be a more quality kata but might not be qualified for 6kyu ~~

Do not have enough understanding on FP to comment on 6. If it should be only FP related, then description should mentioned about that IMO (to prevent translating to other languages)

**Comment by hobovsky** [comment]
> Do not have enough understanding on FP to comment on 6. If it should be only FP related, then description should mentioned about that IMO (to prevent translating to other languages)

I might have used wrong words, because the kata is available currently in OCaml and F#. But I think that "FP aspect" is not that important (what would this even mean? destructuring? pattern matching? recursion?), and it's enough if the requirement is to support generics in statically typed languages, for example in C++, C#, Java, Swift, Haskell, etc.

**Comment by ejini6969** [comment]
`FP related` as in `only accept FP languages` (yeahh like those you mentioned in brackets) But it also does not mention anything about accepting statically-typed languages so I think it should be added if it's chosen to stay as such!

**Comment by nuoliveira** [comment]
I like the idea of palindrome sentences (5), I think it can be considered a separate kata.

I think the code restriction should be removed (reversing a string is a trivial task, currently it makes the kata more annoying rather than challenging).

There's also some inconsistencies with the description and the actual test cases / author solution but that can be fixed later if the kata remains up.

**Comment by error256** [comment]
> presumably "FP-oriented" (whatever this would mean), input is a list, solution is expected to support generics

Both of the languages have only fixed tests with lists of integer, so how is it "expected to support generics"?

**Comment by hobovsky** [comment]
> > presumably "FP-oriented" (whatever this would mean), input is a list, solution is expected to support generics
> 
> Both of the languages have only fixed tests with lists of integer, so how is it "expected to support generics"?

Oh that's how I interpreted [Glinator's post](https://www.codewars.com/kata/57d9951f3c3f9666e9000017/discuss/ocaml#62e0015fc1e633e610fae39c) but I did not notice his fork is not merged yet.

**Comment by monadius** [comment]
I vote to keep 1, 2, and 5. Definitely retire 4 and 6. I don't like 3 but it is a part of a series. So maybe it can be saved.

I vote to keep 1 because it is an OK 8 kyu exercise. Type conversion is not as annoying as input validation.

**Comment by Kacarott** [comment]
Keep 2 and 5

**Comment by EloiseRosen** [comment]
Of the sentence ones: keep 5, retire 4 (seemed ok but beta and only 1 language)
Of the non-sentence ones: keep 2, retire 1 and 3

No opinion on 6 (didn't solve because I don't know F# or OCaml)

**Comment by KayleighWasTaken** [comment]
Retire 1. Mixed input types are not my favourite.
Keep 2, most complete and is my choice of a single candidate to keep.
Retire 3. Input validation isn't a reasonable way to extend this task to 7kyu.
Keep 4. It's a nicer 7kyu extension of the task than 3 since it works on sentences and is punctuation insensitive.
Retire 5. Disabling reverse doesn't really make it any harder since since a bunch of the languages in it can just reverse using slice notation.
No opinion on 6, that's for the real FP users to argue about.

**Comment by RealSup** [comment]
I vote to keep 2 and 5, because it different by difficulty. And I suggest adding in 2 link to 5

**Comment by hobovsky** [comment]
I think that:

- keeping 2. and 5.,
- retire 1., 3., 4., and 6.

will be a conclusion closest to above opinions.  
I think I will also remove the restriction on 5., because it's difficult to enforce consistently between languages, and does not really help much in this kata anyway.
