### ISSUE TITLE
Deduplicate - BF Hello World

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#115]
Identical Brainfuck kata.

1. [BF basics #0: Hello World](https://www.codewars.com/kata/596f7d99f468ae8daa00000b)
* 7 kyu
* 88% with ~400 completions
* BF only (duh)
* Published Jul 2017, author active

2. [[BF] Hello World!](https://www.codewars.com/kata/582c2dffd82a1ff03000000a)
* 6 kyu
* 83% with ~500 completions
* Initial version was Javascript but JS is only a driver for tests, BF translation was added later
* Published Nov 2016, author active

-----

### Conclusion

- Keep 1. [BF basics #0: Hello World](https://www.codewars.com/kata/596f7d99f468ae8daa00000b)
- [x] Retire 2. [[BF] Hello World!](https://www.codewars.com/kata/582c2dffd82a1ff03000000a)

**Comment by hobovsky** [comment]
I admit I like 1. more: I think the rank is better, and I think the JS version in 2. is unnecessary.

**Comment by Kacarott** [comment]
I vote to keep 1, retire 2

**Comment by akar-0** [comment]
keep 1 only.

**Comment by EloiseRosen** [comment]
vote to keep 1, retire 2

**Comment by wtlgo** [comment]
I think, keep the 1st, I see no reason for this kata to have js version
