### ISSUE TITLE
Deduplicate - is negative zero?

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#116]
1. [Is It Negative Zero (-0)?](https://www.codewars.com/kata/5c5086287bc6600001c7589a)
* 7 kyu
* Tests only numbers
* 85% with ~3.5k completions
* No pending issues
* 15 languages, no pending translations
* Published Jan 2019, author deleted

2. [The Tale of Two Zeros](https://www.codewars.com/kata/563c39f92f7bed9572000011)
* 7 kyu
* Tests numbers, and whole variety of falsy values and empty things and various "tricky" inputs
* 88% with 430 completions
* 1 pending issue
* 3 languages (all covered by 1.), no pending translations
* Published Nov 2015, author inactive

-----

### Conclusion

- Keep 1. [Is It Negative Zero (-0)?](https://www.codewars.com/kata/5c5086287bc6600001c7589a)
- [x] Retire 2. [The Tale of Two Zeros](https://www.codewars.com/kata/563c39f92f7bed9572000011)

**Comment by wtlgo** [comment]
I like the 1st one more

**Comment by ejini6969** [comment]
Retire 2 due to annoying input validation, less completion && less languages

**Comment by akar-0** [comment]
Keep 1 only.

**Comment by Blind4Basics** [comment]
keep 1: 2 has an opened issue and a lot less languages

**Comment by EloiseRosen** [comment]
vote for keep 1, retire 2

**Comment by KayleighWasTaken** [comment]
keep 1, more languages

**Comment by Kacarott** [comment]
keep 1
