### ISSUE TITLE
Deduplicate - sum of intervals

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#117]
1. [Sum of Intervals](https://www.codewars.com/kata/52b7ed099cdc285c300001cd)
* 4 kyu
* 92% of 25k solutions
* 3 pending issues, one about inconsistent difficulty between languages
* 20 approved languages + 4 pending translations
* Published Dec 2013, author inactive 

2. [How many days are we represented in a foreign country?](https://www.codewars.com/kata/58e93b4706db4d24ee000096)
* 7 kyu
* 88% with 1.8k completions
* No pending issues
* 7 languages, no pending translations. Nim not present in 1.
* Published Apr 2017, author active

-----

### Conclusion

- Keep both [Sum of Intervals](https://www.codewars.com/kata/52b7ed099cdc285c300001cd) and [How many days are we represented in a foreign country?](https://www.codewars.com/kata/58e93b4706db4d24ee000096) as not duplicates.

**Comment by hobovsky** [comment]
The problem here is that 1. is meant to be difficult, but some languages (reportedly including Python) can be passed with a solution which passes also the 7 kyu version.

I think I'd still say the kata are not duplicates: kata 2. does not really spoil solutions for 1., and 1. should be just fixed to accept solutions of appropriate complexity.

**Comment by Blind4Basics** [comment]
iirc, there are some other kata in yellow level reuqiring the same kind of stuff (& enforcing performances) so.... retire 1?

Suggesting this, because I doubt fixing 20 languages will ever actually happen.

**Comment by monadius** [comment]
@Blind4Basics do you have links to other similar kata with performance requirements? I already fixed several languages in 1. There is an easy fix: It is enough to increase bounds of intervals. This fix does not eliminate all O(n^2) solutions but remaining solutions are more complex than the intended solution. I am going to fix all languages soon. So I vote to keep both 1 and 2.

**Comment by Blind4Basics** [comment]
you know how it is about finding something in the DB... (those kata obviously don't have sum of intervals in their name). Ok, if you can fix the languages, :+1:

**Comment by hobovsky** [comment]
I think we can safely conclude this set as not duplicates. We need to identify nonconformant languages in 1. and fix it.

**Comment by monadius** [comment]
I will try to fix all languages in 1 some time next week.

**Comment by monadius** [comment]
Tasks:

- Make sure that large interval tests are present.
- Large interval tests should not be passed with `max - min` solutions and with set-based solutions.
- Endpoints of large intervals should be in the range `[-1e9, 1e9]`.

Languages with large interval tests:

- [x] C
- [x] Clojure
- [x] COBOL
- [x] CoffeeScript
- [x] C++
- [x] Crystal
- [x] C#
- [x] Dart
- [x] Elixir
- [x] Go
- [x] Haskell
- [x] Java
- [x] JavaScript
- [x] Julia
- [x] NASM
- [x] PHP
- [x] Python
- [x] Racket
- [x] Ruby
- [x] Rust
- [x] TypeScript
