### ISSUE TITLE
Deduplicate - size of powerset

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#118]
1. [Counting power sets](https://www.codewars.com/kata/54381f0b6f032f933c000108)
* 7 kyu
* Duplicates should not be removed from the initial set
* 83% with 5.5k completions
* 4 pending issues, including bugs related to overflow and missing precision of calculations
* 9 languages + 2 pending translations. 4 languages and 2 pending translations are not covered by 2.
* Published Oct 2014, author deleted

2. [Estimating Amounts of Subsets](https://www.codewars.com/kata/584703d76f6cf6ffc6000275)
* 6kyu
* Expected answer does not account for an empty set. Duplicates should be removed from the initial set.
* 88% with 272 completions
* 2 pending issues 
* 5 languages, no pending translations. Crystal exclusive.
* Published Dec 2016, author active

-----

### Conclusion

- [x] Retire 1. [Counting power sets](https://www.codewars.com/kata/54381f0b6f032f933c000108)
- Keep 2. [Estimating Amounts of Subsets](https://www.codewars.com/kata/584703d76f6cf6ffc6000275)

### Filling gaps

- [x] Move Java approved translation
- [x] Move Typescript approved translation
- [x] Move PHP pending translation

**Comment by hobovsky** [comment]
Kata 1. is so bug ridden that there are bugs in its bugs. Precision issues, overflow, bad tests, missing sample tests, and whatnot.  Despite possibly not accurate rank of 2., I'd vote to retire 1. just because its sheer technical crappiness. I would not even require to move languages from 1. to 2., they are all so bad.

Kata 2. could be overranked, and also has some technical issues, but if I have to pick, I take anything else than 1.

**Comment by monadius** [comment]
I agree with hobovsky: 1 should be retired. The pending COBOL translation of 1 may be transferred to 2 but it should be updated to include repeated elements.

**Comment by ejini6969** [comment]
Retire 1 since it's unsalvageable

**Comment by Blind4Basics** [comment]
remove both?

**Comment by Kacarott** [comment]
Retire 1

**Comment by KayleighWasTaken** [comment]
In my opinion it's a useful kata to have in some capacity, since it does teach a useful maths concept. As for which one to keep I'd personally vote 1 due to more languages, though it does need a lot of fixing.

If we do retire both then I'm probably going to remake the kata again but in a maintainable state, more likely to the specs of 2 than one.

**Comment by EloiseRosen** [comment]
vote for retire 1

**Comment by raulbc777** [comment]
Save 2. :) It has an interesting mathematic formula to avoid brute force algorithms. Nevertheless the tests are not so huge to elaborate smart brute force.

**Comment by benjaminzwhite** [comment]
Retire 1

**Comment by akar-0** [comment]
I'm the author of the COBOL pending translation in 1. 2 is not easiy to translate to COBOL because inputs can be either an array of (small) numbers or of characters, it is not possible to do it in this language. If the input is restricted to a known range of small numbers (but the range of the inputs is not specified in the description) or characters, it is significantly easier than it would be otherwise (in the general case, this kata would be significantly harder in COBOL, since there is no equivalent to prebuilt sets in this language). I won't be opposed to retire 1 since it seems a poor quality in the general opinion, but I have no idea of which approach I should follow to translate 2.

**Comment by ejini6969** [comment]
>  I won't be opposed to retire 1 since it seems a poor quality in the general opinion, but I have no idea of which approach I should follow to translate 2.

Maybe we can set inputs of the 2nd one to array of numbers only since the purpose is to find unique entries of the array (plus it will not invalidate most solutions)

**Comment by hobovsky** [comment]
I think that for languages where writing a type-generic code is difficult, like C, COBOL, Pascal, etc. it will be ok to restrict input to only one type, for example ints

**Comment by akar-0** [comment]
> I think that for languages where writing a type-generic code is difficult, like C, COBOL, Pascal, etc. it will be ok to restrict input to only one type, for example ints

It's probably hard to figure it out without knowing COBOL. There are no `int`s in COBOL, numbers are defined by their number of digits. If I look at the tests in Python, the random arrays have always a size between 15 and 100 (this information would be necessarily provided in set up in COBOL) , and numbers are between -50 and 50 (but this is not specified). With this known information, the task is much more trivial than in a general case (numbers potentially large, that would require to sort the array to count the number of different elements).

I published a COBOL translation there, not sure it is satisfying: https://www.codewars.com/kumite/62fa0d46f96973001229c94b?sel=62fa0d46f96973001229c94b

**Comment by raulbc777** [comment]
I approved the COBOL translation made by akar-0 but expecting and watching with you how it behaves.

**Comment by fcr--** [comment]
Retire 1.  I had to provide an incorrect implementation in order to pass the tests in python.

**Comment by hobovsky** [comment]
Kata 1. is voted for retirement, but it has some languages not available in 2. I will create a list of gaps to fill, but if any of translations turns out to be broken, not in a good state to be moved, or difficult to fix, I think we can skip it.

Any volunteers are welcome to verify and move the translations!

**Comment by raulbc777** [comment]
I've seen the colors printed in the tests in Python and the red color makes a confusion. Now all the test that passed in Python have the color green. I'll check in JavaScript and Ruby
