### ISSUE TITLE
Deduplicate - check for factor

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#120]
1. [Thinkful - Number Drills: Pixelart planning](https://www.codewars.com/kata/58630e2ae88af44d2b0000ea)
 * 8 kyu
 * 88% with ~11k completions
 * 3 pending issues
 * 12 languages, no pending translations
 * Published Dec 2016, author inactive 

2. [Grasshopper - Check for factor](https://www.codewars.com/kata/55cbc3586671f6aa070000fb)
* 8 kyu
* 91% with 30k completions
* No pending issues
* 45 languages, no pending translations
* Published Aug 2015, author inactive

-----

### Conclusion

- [x] Retire 1. [Thinkful - Number Drills: Pixelart planning](https://www.codewars.com/kata/58630e2ae88af44d2b0000ea)
- Keep 2. [Grasshopper - Check for factor](https://www.codewars.com/kata/55cbc3586671f6aa070000fb)

**Comment by hobovsky** [comment]
Both kata have identical solution, the only difference between them is a backstory in 1. Maybe it's good enough reason to keep an 8 kyu?

Anyway, I personally think that they are too similar and 2. should be kept as a more complete and 1. retired as a duplicate.

**Comment by monadius** [comment]
Keep 2, retire 1.

**Comment by ejini6969** [comment]
Retire 1 due to less language and completion

**Comment by Kacarott** [comment]
Keep 2, retire 1

**Comment by Blind4Basics** [comment]
keep 2.

option: transfer the backstory of 1 to 2?

**Comment by EloiseRosen** [comment]
vote for retire 1, keep 2

**Comment by KayleighWasTaken** [comment]
Keep 2, more complete.
