### ISSUE TITLE
Deduplicate - Compare large exponentiations

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#122]
1. [Exponential Comparison](https://www.codewars.com/kata/5b1cce03777ab73442000134)
* 6 kyu
* Return larger one
* 90% with 320 completions
* No pending issues
* 4 languages (Java-exclusive), no pending translations
* Published Jun 2018, author inactive

2. [Compare powers](https://www.codewars.com/kata/compare-powers)
* 6 kyu
* Return greater than/equal/less than
* 86% with ~1.2k completions
* 3 pending issues
* 11 languages, no pending translations
* Published Jul 2015, author inactive

----

### Conclusion:

- [x] Retire 1. [Exponential Comparison](https://www.codewars.com/kata/5b1cce03777ab73442000134)
- Keep 2. [Compare powers](https://www.codewars.com/kata/compare-powers)

### Filling gaps

- [x] Move Java approved translation

**Comment by hobovsky** [comment]
Even though the 2. asks for somewhat suboptimal return format (like, why not positive/zero/negative (like comparison functions usually do), or a symbolic constants?) I think it's more complete than 1. w.r.t. available languages. What bothers me is, is the return format of 2. clear enough for 6 kyu audience?

I did not dig too deep to check for any potential precision issues with tests. Like, is it even possible there are any? Is is possible the tests will work incorrectly for inputs like `[81, bajillion], [3, 4 bajillions]`?

**Comment by monadius** [comment]
Retire 1, Keep 2.

The return format of 2 is standard in Ruby (the original kata language). Precision issues are possible but very unlikely. I expect to see issues with equal numbers (e.g.,  `[1000, 2]` and `[10, 6]`). But there are not special random tests for such numbers (all random tests expect either `1` or `-1` with very high probability).

**Comment by hobovsky** [comment]
> The return format of 2 is standard in Ruby (the original kata language).

I did not know that, thanks for explaining. 

Do you think it would be worth to take some precautions so this formt does not spread across translations, but somehow drive translators to use code idiomatic for their languages?

Edit: uh I forgot that theres already 11 languages,  maybe its already too late to enforce practices on translations to  the kata

**Comment by monadius** [comment]
I think the requirements could be changed to return negative/zero/positive values. This format is common in many languages and it is compatible with the original requirements. It will be not difficult to fix existing translations.

**Comment by Kacarott** [comment]
Keep 2, retire 1

**Comment by ejini6969** [comment]
Retire 1

**Comment by EloiseRosen** [comment]
Vote for retire 1, keep 2

**Comment by Madjosz** [comment]
[Moved Java translation](https://www.codewars.com/kumite/6305546c3226f4004b9bcd1c)
