### ISSUE TITLE
Deduplicate - Number of permutation without repetition

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#125]
From #39

1. [Unique Strings](https://www.codewars.com/kata/586c7cd3b98de02ef60001ab)
* 6 kyu
* Inputs are case-insensitive strings ('a' and 'A' are equal elements)
* 90% with 172 completions
* 5 pending issues, one about being a duplicate of 2.
* 3 languages, Elixir-exclusive, no pending translations
* Published Jan 2017, author inactive

2. [Number of permutations without repetitions](https://www.codewars.com/kata/571bff6082661c8a11000823)
* 6 kyu
* Allowed inputs are integers and lowercase strings. Some languages are reported to skip the requirement of mixed input types.
* 94% with 470 completions
* 1 pending issue
* 4 languages, Haskell and JavaScript exclusive, no pending translations
* Published Apr 2016, author last active Apr 2022

----

### Conclusion

- Keep 1. [Unique Strings](https://www.codewars.com/kata/586c7cd3b98de02ef60001ab)
- [x] Retire 2. [Number of permutations without repetitions](https://www.codewars.com/kata/571bff6082661c8a11000823) as a duplicate, with additional technical issues

### Filling gaps

- [x] Move Haskell approved translation from 2. to 1.
- Do not move JavaScript translation from 2. to 1. because it's incorrect. It can be discarded, and new JS translation can be eventually added to 1., without overflow issues and with BigInteger return type.

**Comment by hobovsky** [comment]
I don't like the mixed input types in 2., but maybe it's not a critical flaw? I also think the JS version is not correct: tests pass even though my solution overflows factorials for long inputs. 

I am slightly leaning towards keeping 2. as older and having one language more, but if it turns out that it requires big maintenance effort, I will be fine with retiring 2. and keeping 1.

**Comment by monadius** [comment]
It is not easy to decide which kata should be retired. But I vote to retire 1 and keep 2 because 2 is older and has more completions. Moreover, there are no random tests in Elixir in 1.

JS translation of 2 has potential overflow issues. It should be fixed by enabling Node 14 and requiring `BigInt` results.

I also don't like mixed input types in 2. Ideally, inputs should be strings (or lists) only.

**Comment by Kacarott** [comment]
I also do not like the mixed inputs in 2, and therefore would prefer to keep 1, but if 2 were chosen to be kept it wouldn't be a problem either.

**Comment by ejini6969** [comment]
Same opinion as Kacarott. Maybe if 2 should be kept, tests should be modified to receive strings only despite having to invalidate all solutions!!!

**Comment by KayleighWasTaken** [comment]
Retire 2, I have a vendetta against mixed input types.

**Comment by monadius** [comment]
Mixed input types can be easily changed to strings only and no solutions will be invalidated. I personally can fix 2 (if it is decided to stay) but I cannot fix missing random tests in 1 (Elixir).

**Comment by akar-0** [comment]
keep 1 only.

**Comment by fcr--** [comment]
Both are ok for me, I'll add the Lua translation once this issue is decided.

**Comment by EloiseRosen** [comment]
vote for keep 1, retire 2

**Comment by hobovsky** [comment]
There's more opinions to keep 1. and retire 2., and that's fine. The 2. has some technical issues and I don't feel bad with getting it retired.
