### ISSUE TITLE
Deduplicate - Day of the week from a date

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#126]
Reported in #39

1. [What day is it?](https://www.codewars.com/kata/5666bd1011beb6f768000073)
* 7 kyu
* input is a string `"YYYYMMDD"`
* 90% with 270 completions
* 1 pending issue
* 1 language (python)
* Published Dec 2015, author inactive

2. [#~For Kids~# d/m/Y -> Day of the week.](https://www.codewars.com/kata/5885b5d2b632089dc30000cc)
* 7 kyu
* input is a string `"DD/MM/YYYY"`
* 85% with 250 completions
* No pending issues
* 3 languages (JS, PHP, Ruby)
* Published Jan 2017, author inactive

3. [Day of The Week](https://www.codewars.com/kata/588d54c2ce8a3532a500001b)
* 7kyu
* input is Date object or string `"MM/DD/YYYY"` (yuck)
* 87% with ~ 530 completions
* No pending issues
* 1 language (JS only)
* Published Jan 2017, author inactive

4. [Christmas Day](https://www.codewars.com/kata/52af9d951f5a1298b2000170)
* 6kyu
* input is Date object or string with a couple of possible formats. All inputs have months and days fixed to Dec 25
* 88% with 1100+ completions
* 1 pending issue
* 3 languages (CS, JS, Ruby)
* Published Dec 2013, author inactive

5. [What will be the day of the week in a year?](https://www.codewars.com/kata/595695afc575c9d266000037)
* beta, breakdown clearly shows 7 kyu
* Input is `year, month, day` but it's ambiguous and not described properly, it's not clear if days are 0-based or 1-based
* 77% with 87 completions
* 2 pending issues, one about being a duplicate.
* 1 language (Java only)
* Published Jun 2017, author inactive

----

### Conclusion

- Keep 2. [#~For Kids~# d/m/Y -> Day of the week.](https://www.codewars.com/kata/5885b5d2b632089dc30000cc) and change its name to something better
- [x] Retire 1. [What day is it?](https://www.codewars.com/kata/5666bd1011beb6f768000073)
- [x] Retire 3. [Day of The Week](https://www.codewars.com/kata/588d54c2ce8a3532a500001b)
- [x] Retire 4. [Christmas Day](https://www.codewars.com/kata/52af9d951f5a1298b2000170)
- Kata 5. [What will be the day of the week in a year?](https://www.codewars.com/kata/595695afc575c9d266000037) got auto-retired as hopeless so no action required here.

### Filling gaps

- [x] Move Python approved translation from 1. to 2.
- [x] Move CoffeeScript approved translation from 4. to 2.

**Comment by hobovsky** [comment]
I cannot express enough how much I think we need more tasks related to handling dates, locale-sensitive data, and things related to I18n.

I think 1. is the cleanest.
Kata 2. is also technically OK, but I like input format of 1. a bit better.
Kata 3. has annoying, middle-endian input format, and sample tests with `Date` as input are missing.
I don't like inputs to 4: two fields are fixed, types can differ, formats can differ. Handling all possibilities is annoying af.
Kata 5. is somewhat OK but has some technical issues. I like the input of `y`,`m`,`d` the most, but it's still underspecified in the description. It has also bad tests, because some solutions do `day+1` and still pass.

I _think_ some of solutions to some of above kata, especially JS ones, might be locale-sensitive and would break on some environments when parsing input strings or formatting results with date formatters.

I vote to keep 2. because it's technically OK and has most languages, and improve its title. If for some reason 2. is not preferable, my second candidate to keep would be 1.
I think 3., 4., and 5. can be retired as close duplicates with no additional value when compared to 1.
Whatever kata is left, tests possibly could use some improvements: different locales, leap years (if relevant), etc.

**Comment by KayleighWasTaken** [comment]
Keep 1 or 2. No real preference.
Retire 3. Fuck that date format.
Retire 4. Less general case of the problem which is ranked higher than the others.
Retire 5. It's shit.

**Comment by monadius** [comment]
Keep 2.

**Comment by akar-0** [comment]
keep 2 only.

**Comment by EloiseRosen** [comment]
Looks like 5 is already retired. Vote for keep 1 or 2, retire the others.
