### ISSUE TITLE
Deduplicate - perimeter in a grid

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#127]
Reported on the wiki list of duplicates.

1. [Simple Fun #85: Polygon Perimeter](https://www.codewars.com/kata/58953a5a41c97914d7000070)
* 6 kyu 
* 95% with 190 completions
* 1 pending issue
* 4 languages, no pending translations. Exclusive: C#, Ruby
* Published Feb 2017, author inactive

2. [Land perimeter](https://www.codewars.com/kata/5839c48f0cf94640a20001d3)
* 5 kyu
* 95% with 1.9k solutions
* No pending issues
* 5 languages + 1 pending translation. Exclusive: CS, Haskell, PHP, COBOL
* Published Nov 2016, author inactive

-----

### Conclusion

- [x] Retire 1. [Simple Fun #85: Polygon Perimeter](https://www.codewars.com/kata/58953a5a41c97914d7000070)
- Keep 2. [Land perimeter](https://www.codewars.com/kata/5839c48f0cf94640a20001d3)

### Filling gaps

- [x] Move C# translation from 1. to 2.
- [x] Move Ruby translation from 1. to 2.

**Comment by hobovsky** [comment]
I have no real preference which one to keep, I will be fine with any decision.  
Kata 1. has more languages, and potentially lower cost to move missing languages.
I like kata 2. a bit more because it's older, has more completions, and I think a more accurate rank.

If there will be no clear conclusion which one to keep, I think I will just flip a coin :)

**Comment by ejini6969** [comment]
I vote to keep 2 due to higher completion and appropriate ranks plus 1 might be potentially facing copyright issues ~~

**Comment by KayleighWasTaken** [comment]
Keep 2, older, more completions, etc. and as ejini said as well, I think 1 is from a site that doesn't like their stuff being put on CW.

**Comment by Kacarott** [comment]
Keep 2, cooler.

**Comment by monadius** [comment]
Retire 1 because its description is copied from Codesignal. Moreover kata 2 has more languages (5 + 1 pending COBOL translation; I updated the original comment where available languages were swapped).

**Comment by akar-0** [comment]
Keep 2 only.

**Comment by EloiseRosen** [comment]
vote for retire 1, keep 2
