### ISSUE TITLE
Deduplicate - Multiply

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/content-issues#128]
1. [Multiply](https://www.codewars.com/kata/50654ddff44f800200000004)
   - 8 kyu
   - 81% with 5M completions
   - 3 pending issues
   - 58 languages
   - Published May 2013, no author specified
   - _The_ entry-level Kata for new Codewarriors
2. [Function 3 - multiply two numbers](https://www.codewars.com/kata/523b66342d0c301ae400003b)
   - 8 kyu
   - 81% with 54k completions
   - 1 pending issue
   - 19 languages, no pending translations
   - Published Sep 2013, author inactive

----

### Conclusion

- Keep 1. [Multiply](https://www.codewars.com/kata/50654ddff44f800200000004)
- [x] Retire 2. [Function 3 - multiply two numbers](https://www.codewars.com/kata/523b66342d0c301ae400003b)

**Comment by DonaldKellett** [comment]
Vote 1, retire 2

**Comment by ejini6969** [comment]
Don't forget to mention 2 requires writing the function from scratch, but it's been done in the previous 2 series of that kata ... so retirement !!!

**Comment by hobovsky** [comment]
Let's request retirement of 1. and see if we can break Codewars :D

**Comment by Kacarott** [comment]
Is it even worth opening an issue for this? 😄 Clearly we are keeping 1.

**Comment by hobovsky** [comment]
> Is it even worth opening an issue for this? 😄 Clearly we are keeping 1.

We can keep both :)

I actually like the "create a function from scratch" part, especially for an 8 kyu kata. But I believe there's more kata with such task.

**Comment by EloiseRosen** [comment]
vote for retire 2

**Comment by Blind4Basics** [comment]
well, 1 is the captcha for subscription to CW, so it cannot be retired in any way anyway x)

retire 2, ofc.
