### ISSUE TITLE
Deduplicate - Hamming Distance

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#129]
From #39

1. [Hamming Distance](https://www.codewars.com/kata/5410c0e6a0e736cf5b000e69)
* 6kyu
* Input is two strings of equal length
* 86% with ~2.7k completions
* 1 pending issue
* 10 languages + 3 pending translations
* Published Sep 2014, author inactive

2. [Simple Fun #141: Hamming Distance](https://www.codewars.com/kata/58a6af7e8c08b1e9c40001c1)
* 6kyu
* Input are two integers
* 94% with 750+ completions
* 1 pending issue
* 9 languages, no pending translations
* Published Feb 2017, author inactive

3. [Hamming Distance - Part 1: Binary codes](https://www.codewars.com/kata/5624e574ec6034c3a20000e6)
* 7 kyu
* inputs are two strings of only zeros and ones, both of the same length
* 92% with ~2k solutions
* 3 pending issues, one about being a duplicate of 1.
* 8 languages, no pending translations
* Published Oct 2015, author inactive

Languages:
![Image](https://user-images.githubusercontent.com/23709795/185591241-a74be71c-9730-457c-810e-94903959dba8.png)

----

### Conclusion

- Keep 1. [Hamming Distance](https://www.codewars.com/kata/5410c0e6a0e736cf5b000e69)
- Keep 2. [Simple Fun #141: Hamming Distance](https://www.codewars.com/kata/58a6af7e8c08b1e9c40001c1)
- [x] Retire 3. [Hamming Distance - Part 1: Binary codes](https://www.codewars.com/kata/5624e574ec6034c3a20000e6)

### Filling gaps

- [x] Move PHP translation from 3. to 1.
- [x] Move PureScript translation from 3. to 1.

**Comment by hobovsky** [comment]
Kata 1. is good to keep, I'd vote it to stay.
Kata 2. works with integers and allows for interesting solutions of `popcount(a xor b)`. I'd vote to keep it.
Kata 3. is pointless because it's an exact duplicate of 1 but with narrower inputs. Solutions which rely on parsing of binary inputs are effectively the same as for 2. I vote to retire it. It's only advantage are PHP and PureScript translations, which we'd have to transfer after retirement.

**Comment by ejini6969** [comment]
I was about to vote on keeping `1` only but since `2` teaches extensive knowledge regarding binary operations , I'll say keep 2 too.

**Comment by KayleighWasTaken** [comment]
Keep 1 and 2, retire 3 and move PHP and Purescript from 3 to 1.

**Comment by Kacarott** [comment]
Keep 1, 2. Retire 3.

**Comment by EloiseRosen** [comment]
vote for keep 1 and 2, retire 3
