### ISSUE TITLE
Deduplicate - create powerset

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#130]
Reported on wiki list of duplicates.

1. [By the Power Set of Castle Grayskull](https://www.codewars.com/kata/53d3173cf4eb7605c10001a8)
* 5kyu
* Input is a list, output is a list of lists
* 93% with 2.1k completions
* 2 pending issues
* 5 languages + 1 pending translation
* Published Jul 2014, author inactive

2. [Subsequences](https://www.codewars.com/kata/5a0127028ba91430e80000a8)
* 6kyu
* Input is a string, output is a list of strings
* 89% with 50 completions
* No pending issues
* JS only (covered by 1.)
* Published Nov 2017, author inactive

----

### Conclusion

- Keep 1. [By the Power Set of Castle Grayskull](https://www.codewars.com/kata/53d3173cf4eb7605c10001a8)
- [x] Retire 2. [Subsequences](https://www.codewars.com/kata/5a0127028ba91430e80000a8)

**Comment by hobovsky** [comment]
Both kata differ by their rank, but I don;t think 5 kyu is _much_ off. I vote to keep 1. because it requires smaller effort with moving languages, but I am fine with keeping 2. and moving languages there too.

**Comment by Kacarott** [comment]
Keep 1, retire 2.

**Comment by KayleighWasTaken** [comment]
1 should be kept on language coverage and completion alone. 2 is JS only with 50 completions, just retire it.
