### ISSUE TITLE
Deduplicate - Count Words

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#131]
From #39

1. [Count words](https://www.codewars.com/kata/count-words)
* 6 kyu
* 85% with ~600 completions
* Any non-letter is a non-word character (i.e. a separator). Some words from a predetermined list should not be counted.
* no pending issues
* 2 approved languages, 2 pending translations
* Published Feb 2016, author active

2. [Count words](https://www.codewars.com/kata/570cc83df616a85944001315)
* 8kyu
* Separators are whitespace characters, but "whitespace" is defined really bad, and not tested well.
* 82% with 6.7k completions
* no pending issues
* 1 approved language, 4 pending translations, C# exclusive
* Published Apr 2016, author inactive

----

### Conclusion

The kata are not duplicates and both will be kept.

**Comment by hobovsky** [comment]
I think that however easy/boring/dull both kata are, they are not similar enough to be considered duplicates and I would not remove any as a duplicate of another.
However, 2. is in not a really good shape and deserves retirement just because of this. Description is confusing, does not explain what "whitespace" is, tests do not check for said whitespace except two characters.

I vote to keep 1., and fix or retire 2. due to bad quality.

**Comment by ejini6969** [comment]
I agree with hobs, the rank for 2 is also abit inappropriate

**Comment by Kacarott** [comment]
Keep both, I think the premise of 2 makes a worthwhile 8kyu kata if the description (and potentially tests?) were rewritten.

**Comment by KayleighWasTaken** [comment]
If we're keeping just one then 1 is better, but both are different tasks. 2 needs a description/tests rewrite.

**Comment by akar-0** [comment]
Keep  both an fix 2.
