### ISSUE TITLE
Deduplicate - Nth biggest / smallest numbers

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#132]
From #39

1. [Find the 2nd largest integer in array](https://www.codewars.com/kata/55a58505cb237a076100004a)
* 7kyu
* input: array of mixed types, discard duplicates, output: second largest integer
* 89% with 1000+ completions
* 0 pending issues
* 2 languages, no pending translations
* Approved Jul 2015, author inactive

2. [Nth Smallest Element (Array Series #4)](https://www.codewars.com/kata/5a512f6a80eba857280000fc)
* 7kyu
* ints only, do not discard duplicates, position is 1-based, out-of-range position, output: nth smallest element
* 90% with 6.7k completions
* 1 pending issue
* 20 languages, no pending translations
* Published Jan 2018, author inactive

3 . [The nth smallest integer](https://www.codewars.com/kata/57a03b8872292dd851000069)
* 6kyu
* ints only, discard duplicates, position is 1-based, out-of-range position, output: nth smallest element
* 88% with ~850 completions
* 1 pending issues
* 5 languages + 2 pending translations (Perl-exclusive)
* Published Aug 2016, author inactive

----
### Conclusion

- Keep 2. [Nth Smallest Element (Array Series #4)](https://www.codewars.com/kata/5a512f6a80eba857280000fc)
- [x] Retire 1. [Find the 2nd largest integer in array](https://www.codewars.com/kata/55a58505cb237a076100004a)
- [x] Retire 3 . [The nth smallest integer](https://www.codewars.com/kata/57a03b8872292dd851000069)

### Filling gaps

- [x] Move Perl pending translation from 3. to 2.

**Comment by hobovsky** [comment]
All above kata accept sort-based solutions, so there's no real difference between requesting a second element or an nth element.

Kata 2. seems to be the most complete, but its description has to definitely be un-Zizou'ed. I;d vote to keep it.

I do not know if any of 1. or 3. deserves to be kept, but I can see how on this level it could be good to have another, similar task. If so, I'd vote to retire 3. and keep 1. and change its requirements to remove mixed input types. Move Perl translation from 3. to 1.

**Comment by KayleighWasTaken** [comment]
Mixed input types are just kinda bad, either remove them from 1 or retire it. Definitely retire 3. Keep 2.

**Comment by monadius** [comment]
Keep 2 only. 1 and 3 do not add much to the task: It is enough to deduplicate elements (which is a very simple task in many languages) and then check that the result contains enough element (another requirements which makes the description more complicated than necessary: return -1 in C++, return nil in Ruby, etc.).

**Comment by ejini6969** [comment]
Keep 2. Retire 1 due to annoying mixed input types and less languages, retire 3 due to over-ranked and inconsistent output types

**Comment by akar-0** [comment]
keep 2 only.

**Comment by EloiseRosen** [comment]
vote for keep 2, retire the others

**Comment by Kacarott** [comment]
keep 2 and fix its description. Retire others
