### ISSUE TITLE
Deduplicate - Multiple of 3 or 5

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#133]
Reported on #39

1. [Multiples of 3 or 5](https://www.codewars.com/kata/514b92a657cdc65150000006)
* 6kyu
* 88% with 275k completions
* 5 pending issues
* 35 languages + 1 pending translation
* Published Mar 2013, author active

2. [Sum of all the multiples of 3 or 5](https://www.codewars.com/kata/57f36495c0bb25ecf50000e7)
* 7kyu
* 90% with 23k completions
* 3 pending issues
* 10 languages + 6 pending translations, all languages covered in 1.
* Published Oct 2016, author last active May 2022

-----

### Conclusion

- Keep 1. [Multiples of 3 or 5](https://www.codewars.com/kata/514b92a657cdc65150000006)
- [x] Retire 2. [Sum of all the multiples of 3 or 5](https://www.codewars.com/kata/57f36495c0bb25ecf50000e7)

**Comment by ejini6969** [comment]
Retire 2 due to less languages and less completions

**Comment by hobovsky** [comment]
Both seem to be exact duplicates, so I think it's fine to get rid of one completely. Both kata accept O(n) solutions and have no performance requirements.

Even though 2. could be better for some reasons (better rank?), I think moving over 20 languages will be difficult.

**Comment by akar-0** [comment]
Keep 1 only.

**Comment by Kacarott** [comment]
keep 1, retire 2

**Comment by EloiseRosen** [comment]
vote for keep 1, retire 2

**Comment by benjaminzwhite** [comment]
Keep 1, retire 2. 

I love all of jhoffner's katas, they are the best!

(jhoffner has added +500 honor to your Codewars account for upvoting his kata. Make sure you delete this before copy pasting your comment on GitHub)

**Comment by akar-0** [comment]
keep 1 only
