### ISSUE TITLE
Deduplicate - Integer depth

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#134]
From #39

1. [Bleatrix Trotter (The Counting Sheep)](https://www.codewars.com/kata/59245b3c794d54b06600002a)
* 6kyu
* Result is the last number in the sequence of multiplies when reaching the full depth
* 93% with 770 completions
* No pending issues
* 7 languages, no pending translations (C++, PHP, TypeScript - exclusive)
* Published May 2017, author active

2. [Integer depth](https://www.codewars.com/kata/59b401e24f98a813f9000026)
* 6kyu
* Output: number of iterations to reach the full depth
* 94% with 2.3k completions
* 15 languages
* Sep 2017, author last active May 2022

----

### Conslusion

- Keep 2. [Integer depth](https://www.codewars.com/kata/59b401e24f98a813f9000026)
- [x] Retire 1. [Bleatrix Trotter (The Counting Sheep)](https://www.codewars.com/kata/59245b3c794d54b06600002a)

### Filling gaps

- [x] Move C++ approved translation from 1. to 2.
- [x] Move PHP approved translation from 1. to 2.
- [x] Move TypeScript approved translation from 1. to 2.

**Comment by hobovsky** [comment]
Both kata seem to be very similar to me, and I don;t think we need both. I also have no strong candidate to keep, so I think I'd vote to keep 2. as more complete.

**Comment by monadius** [comment]
Keep 2 because it has more languages and it does not test numbers `n <= 0` (for which 1 asks to return a string).

**Comment by akar-0** [comment]
Keep 2 only.

**Comment by benjaminzwhite** [comment]
I vote keep 2 also - clearer explanation, avoids returning strings, and more complete/languages.

**Comment by EloiseRosen** [comment]
Vote for retire 1, keep 2

**Comment by Kacarott** [comment]
Keep 2, more languages

**Comment by KayleighWasTaken** [comment]
Keep 2, more languages and I translated it to Scala before I saw the dedup issue.

**Comment by ejini6969** [comment]
Keep 2 due to reasons stated above
