### ISSUE TITLE
Deduplicate - sum of cubes

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#135]
From #39

1. [CubeSummation](https://www.codewars.com/kata/550e9fd127c656709400024d)
* 7kyu
* Cubes of all numbers between two, potentially unsorted, bounds
* 93% with 2.4k completions
* No pending issues
* 6 languages
* Published Mar 2015, author inactive

2. [Sum of Cubes](https://www.codewars.com/kata/59a8570b570190d313000037)
* 7kyu
* The range is `1...n`
* 92% with 11k completions
* No pending issues
* 22 languages, no pending issues
* Published Aug 2017, author inactive

----

### Conclusion

- Keep 2. [Sum of Cubes](https://www.codewars.com/kata/59a8570b570190d313000037)
- [x] Retire 1. [CubeSummation](https://www.codewars.com/kata/550e9fd127c656709400024d)

**Comment by hobovsky** [comment]
Both kata accept O(n) solutions, O(1) solutions are not enforced.

I have no good idea how to handle this case. Maybe these two tasks are different enough for a 7 kyu to be kept? Maybe turn 1. into a performance kata which would reject O(n) solutions? Or maybe keep only 2. because it has more languages?

Any ideas?

**Comment by monadius** [comment]
Keep 2 only because it has more languages. Unsorted bounds in 1 do not add much to the task.

**Comment by benjaminzwhite** [comment]
Vote keep 2 also, added "complexity" isn't really interesting in 1.

As for ideas - I thought maybe you could maybe "disguise" 1 with a question about finding how many rectangles in an n x n grid (combinatorial proof that this equals `(n+1 choose 2)**2` = sum of cubes from 1 to n) but it seems such a kata already exists:

[Number of rectangles in a grid 7 kyu](https://www.codewars.com/kata/556cebcf7c58da564a000045)

**Comment by EloiseRosen** [comment]
vote for keep 2, retire 1

**Comment by Kacarott** [comment]
Keep 2 for more languages

**Comment by ejini6969** [comment]
Keep 2 only
