### ISSUE TITLE
Deduplicate - escape html

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#137]
Reported in #39

1. [Safen User Input Part I - htmlspecialchars](https://www.codewars.com/kata/56bcaedfcf6b7f2125001118)
* 8kyu
* 92% with ~4.4k completions
* 1 pending issue
* 7 languages
* Published Feb 2016, author active

2. [Escape HTML Markup](https://www.codewars.com/kata/52c7c425f80c299ac60003df)
* 6kyu
* 82% with ~600 completions
* No pending issues
* 1 language + 1 pending translation, all covered by 1.
* Published Jan 2014, author inactive.

----

### Conclusion

- Keep 1. [Safen User Input Part I - htmlspecialchars](https://www.codewars.com/kata/56bcaedfcf6b7f2125001118)
- [x] Retire 2. [Escape HTML Markup](https://www.codewars.com/kata/52c7c425f80c299ac60003df)

**Comment by hobovsky** [comment]
Kata 1. has many completions and more languages. Interesting thing about it is that handling of `&`  needs some additional attention. It may be considered underranked.

Kata 2 is much older. It was reported to have many issues, but it seems all were resolved. Choice of characters to replace is a little bit smaller, and there's no `&`. 

Despite of being older, I'd vote to retire 2. as superseded by 1.

**Comment by Kacarott** [comment]
I also vote to retire 2, additionally because it is overranked.

**Comment by appsunited** [comment]
I am not sure if is the right direction to start a discussion to remove a kata, which has been completed more than 600 times. From my perspective both katas are fine and there is no reason to delete user content.

**Comment by akar-0** [comment]
Keep 1 only, first of all because it has more languages available. Though 8kyu seems underranked, it doesn't matter that much.

**Comment by ejini6969** [comment]
Retire 2, plus author gone which means maintenance can only be done from content support's side.

**Comment by EloiseRosen** [comment]
vote to retire 2 and keep 1 due to difference in number of languages

**Comment by hobovsky** [comment]
Decision seems to be clear: despite of being older, kata 2. will be retired as superseded by 1.
