### ISSUE TITLE
Deduplicate - Find most occurrence in array

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#138]
From #39

1. [Highest Rank Number in an Array](https://www.codewars.com/kata/5420fc9bb5b2c7fd57000004)
* 6kyu
* Return a single, the largest element with the largest count
* 92% with 11k completions
* 6 pending issues
* 8 languages + 2 pending translations
* Published Sep 2014, author inactive

2. [Most Frequent Elements](https://www.codewars.com/kata/53f103c3ef9ad4014f00013b)
* 7kyu
* Return a set of all elements with the max count
* 87% with 1.7k completions
* 1 pending issue
* 1 language (Python) + 1 pending translation (JS)
* Published Aug 2014, author last active Jun 2022

3. [Thinkful - Dictionary Drills: Multiple Modes](https://www.codewars.com/kata/586f5808aa04285bc800009d)
* 6kyu
* A bit convoluted rules related to resolving ties
* 91% with 1k completions
* No pending issues (but I think that the `["redder"]` test case is buggy)
* Python only
* Published Jan 2017, author inactive

4. [Find the majority](https://www.codewars.com/kata/5af974846bf32304a2000e98)
* 7kyu
* Return `None` for all inputs when there's no unambiguous winner
* 92% with ~550 completions
* No pending issues
* 2 languages (Python + JS), no pending issues
* Published May 2018, author inactive

----

### Conclusion

- Keep 1. [Highest Rank Number in an Array](https://www.codewars.com/kata/5420fc9bb5b2c7fd57000004)
- Keep 4. [Find the majority](https://www.codewars.com/kata/5af974846bf32304a2000e98)
- [x] Retire 2. [Most Frequent Elements](https://www.codewars.com/kata/53f103c3ef9ad4014f00013b)
- [x] Retire 3. [Thinkful - Dictionary Drills: Multiple Modes](https://www.codewars.com/kata/586f5808aa04285bc800009d)

**Comment by hobovsky** [comment]
I have no good candidates to retire here. All kata have identical main task, and differ when it comes to handling ties, in a way which can be potentially interesting in a low-level kata. But is it? No idea. 1. is the simplest and has most languages, 3. is (i think) the most complex.

**Comment by Blind4Basics** [comment]
* retire 2 (no random tests / 1 language only / most basic version of the task)
* 4 is the only one that is "up to date", considering how the tests are written, so I think we should make this one survive.
* between 1 and 3, keep 1. 3 seems more artificial and has only 1 language.

Summary:
* keep 1 and 4
* retire 2 and 3

**Comment by Kacarott** [comment]
I vote to keep 1 based on having the most languages. Retire the rest

**Comment by EloiseRosen** [comment]
vote for keep 1

**Comment by hobovsky** [comment]
No one wanted to keep 2. or 3., so they get retired.
Everyone agreed to keep 1., so it stays.
There is some opinions to keep 4., so it stays.
