### ISSUE TITLE
Deduplicate - sum of triangular numbers

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#140]
From #39

1. [Sum of Triangular Numbers](https://www.codewars.com/kata/580878d5d27b84b64c000b51)
* 7kyu
* negative inputs should be considered invalid
* 89% with ~13k completions
* No pending issues
* 17 languages, no pending translations
* Published Oct 2016, author inactive

2. [A tetrahedron of cannonballs](https://www.codewars.com/kata/530e259c7bc88a4ab9000754)
* 6kyu
* All inputs are valid
* 89% with 650 completions
* 2 pending issues
* 5 languages, no pending translations (all covered in 1.)
* Published Feb 2014, author inactive

-----

### Conclusion

- Keep 1. [Sum of Triangular Numbers](https://www.codewars.com/kata/580878d5d27b84b64c000b51)
- [x] Retire 2. [A tetrahedron of cannonballs](https://www.codewars.com/kata/530e259c7bc88a4ab9000754)

**Comment by hobovsky** [comment]
Kata 1. accepts O(n) solutions.  
Kata 2. is most probably meant to accept only O(1) solutions, but for some reason O(n) solutions do not get consistently invalidated when I resubmit them. Either tests significantly vary between runs, or revalidation is wonky again. I also did not check performance requirements of languages other than Python. I like how it uses the term "cannonball numbers", but its description is messy af: "pyramid, but not square", and "tetrahedron, but the important number is 3 and not 4", etc.

I did not check if any of the kata is affected by overflow, but JS translation of 2. is reported to be.
Top voted solutions to 1. are O(1) and kind of spoil solutions for 2.

I think kata 1. is good to keep as a low level exercise, with accurate rank, and no performance requirements.
I have no good opinion on kata 2. It is spoiled by 1., but maybe it would still be good to keep if enforced difficulty and accepted only O(1) solutions? I am fine with getting rid of it, but I also see how it could be seen as performance version or additional variety.

**Comment by monadius** [comment]
Keep 1, retire 2. Performance requirements do not make 2 more interesting (it is trivial to google the required formula) and O(1) solutions are spoiled by 1. Moreover, JS and Python versions of 2 have no random tests.

**Comment by akar-0** [comment]
keep 1 only.

**Comment by Kacarott** [comment]
Keep 1, retire 2

**Comment by EloiseRosen** [comment]
vote for keep 1, retire 2

**Comment by suic86** [comment]
keep 1, retire 2
