### ISSUE TITLE
Deduplicate - Array of strings to array of numbers

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#141]
From #39

1. [Convert an array of strings to array of numbers](https://www.codewars.com/kata/5783d8f3202c0e486c001d23)
* 7kyu
* 91% with 6.7k solutions
* No pending issues
* 6 languages, no pending translations
* Published Jul 2016, author inactive

2. [Strings to numbers](https://www.codewars.com/kata/5872d6eba44cfcd500000153)
* 7kyu
* Code golf
* 85% with 350 completions
* No pending issues
* JS only
* Published Jan 2017, author active

3. [[JS] Parse integers in array](https://www.codewars.com/kata/535d118ccdbf501816001101)
* 7kyu
* Bug fixing
* 91% with ~1.8k completions
* 1 pending issue
* JS only
* Published Apr 2014, author inactive

----

### Conclusion

- Keep 1. [Convert an array of strings to array of numbers](https://www.codewars.com/kata/5783d8f3202c0e486c001d23)
- Keep 3. [[JS] Parse integers in array](https://www.codewars.com/kata/535d118ccdbf501816001101)
- [x] Retire 2. [Strings to numbers](https://www.codewars.com/kata/5872d6eba44cfcd500000153)

**Comment by hobovsky** [comment]
Technically speaking, the three kata are not strict duplicates:

Kata 1. is a "normal" task for beginners. I am concerned by inputs with string representations of floats, I am not sure if these can be easily tested for, and whether tests do it correctly.

Kata 2. is a code golf, and I think a bad one. If I was able to solve it, anyone can.

Kata 3. is bug fixing, and I do not know JS well enough to tell whether the bug is interesting or not. What I dont like about it is that handling of floats is underspecified, I did not know what method of rounding should be used to turn floats into ints.

**Comment by monadius** [comment]
Keep 1 and 3, retire 2. 

2 is a trivial code golf which is not interesting at all.

3 demonstrates a [textbook bug](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#tricky_use_case) so it is not bad. I don't think that 3 is underspecified: The rounding method is given in the initial code.

**Comment by hobovsky** [comment]
Hey now reading about this, the bug presented in 3. is actually cool!

**Comment by Kacarott** [comment]
Agree with keeping 1 and 3. Retire 2

**Comment by EloiseRosen** [comment]
retire 2, keep the others sounds good
