### ISSUE TITLE
Deduplicate - Church numerals

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#142]
From wiki list of duplicates.

1. [Church numbers](https://www.codewars.com/kata/church-numbers-1)
- 4 kyu
- Requested operations are `add`, `mul`, `pow`. Numbers are two-argument uncurried functions. Provides some helpers to convert between Church and int. 
- 94% with 170+ completions
- 1 pending issue
- 1 language (JS), 1 pending translation (C++)
- Published Nov 2014, author active

2. [Church numbers (ii)](https://www.codewars.com/kata/church-numbers-ii)
- 3 kyu
- Same as 1., but operations are `pred` `sub` `compareTo` `div` `mod`
- 84% with ~100 completions
- 2 pending issues
- 1 language (JS)
- Published Nov 2014, author the same as for kata 1.

3. [Church numbers](https://www.codewars.com/kata/church-numbers)
- 4 kyu
- Requested operations are `add` `mul` `pow`. Provides `zero`, `one`, and `succ`. Uses normal, curried functions.
- 94% with ~360 completions
- No pending issues
- 4 languages
- Published Nov 2014, author active

4. [Church Numbers - Add, Multiply, Exponents](https://www.codewars.com/kata/church-numbers-add-multiply-exponents)
- 3 kyu
- Requested operations are `add` `mul` `pow`. Provides `zero`, `succ`, and functions to convert Church <=> int. Solution is spoiled by the description.
- 81% with 1k completions
- No pending issues
- 3 languages
- Published Aug 2015, author active

5. [Church numbers: find the predecessor and subtract](https://www.codewars.com/kata/church-numbers-find-the-predecessor-and-subtract)
- 4 kyu
- Requested operations are `pred` `sub`. Provides `zero`, `one`, and `succ`. Uses normal, curried functions.
- 92% with ~200 completions
- 1 pending issue
- 4 languages
- Published Nov 2014, author the same as for kata 3.

----

### Conclusion

- Keep 3. [Church numbers](https://www.codewars.com/kata/church-numbers)
- Keep 5. [Church numbers: find the predecessor and subtract](https://www.codewars.com/kata/church-numbers-find-the-predecessor-and-subtract)
- [x] Retire 1. [Church numbers](https://www.codewars.com/kata/church-numbers-1) after C++ translation is moved
- [x] Retire 2. [Church numbers (ii)](https://www.codewars.com/kata/church-numbers-ii)
- [x] Retire 4. [Church Numbers - Add, Multiply, Exponents](https://www.codewars.com/kata/church-numbers-add-multiply-exponents)

### Filling gaps

- [x] Move approved Python translation form 4. to 3.
- [x] Move pending C++ translation from 1. to 3.

**Comment by Kacarott** [comment]
1 and 2 are abominations which require un-curried arguments. Number 4 is horrendously overranked and essentially has the solution in the description.

Therefore I vote to keep 3 and 5, retire the rest.

Edit: Another idea would be to retire all of them, and create new kata with *all* operations. Or convert either 3 or 5 to use all operations.

**Comment by JohanWiltink** [comment]
Kill off 1, 2, 4; keep 3, 5.

I see no harm in keeping the current 3 and 5; also, authoring PS translations was _not_ fun when I did it - _I_ won't do it again.

_All_ are overrated, but I don't see much harm in that either - lure people in with cheap points. 😋

**Comment by JohanWiltink** [comment]
Note that 3 and 5, in their JS versions, require LC syntax. Haskell and PS syntax already is reasonably close to LC syntax, though some sugar is available there.

4 is the only one to have Python. A syntax checker for Python is available on some other LC kata ( :carrot: wrote that ); 3 and 5 ( if those are kept ) might benefit from a Python translation with syntax check. Python lambdas are quite suited to expressing LC.

**Comment by lsnbr** [comment]
Keep 3 and 5, same reasons as already said
