### ISSUE TITLE
Deduplicate - Shortest/longest word

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#144]
From #39

1. [Thinkful - List Drills: Longest word](https://www.codewars.com/kata/58670300f04e7449290000e5)
* 7kyu
* input is an array of words. Find length of longest word.
* 92% with 5k completions
* 2 pending issues
* 8 languages + 1 pending translation
* Published Dec 2016, author inactive

2. [Shortest Word](https://www.codewars.com/kata/57cebe1dc6fdc20c57000ac9)
* 7kyu
* input is a string, find length of shortest word
* 90% with 161k completions
* 1 pending issue
* 29 languages, no pending translations. Covers all languages of 1.
* Published Sep 2016, author active

3. [Squash the bugs](https://www.codewars.com/kata/56f173a35b91399a05000cb7)
* 8 kyu
* Bug fixing kata. Input is a string, find length of longest word.
* 91% with 24k+ completions
* No pending issues
* 11 languages, no pending translations
* Published Mar 2016, author the same as 2.

----

### Conclusion

- Keep 2. [Shortest Word](https://www.codewars.com/kata/57cebe1dc6fdc20c57000ac9)
- [x] Retire 1. [Thinkful - List Drills: Longest word](https://www.codewars.com/kata/58670300f04e7449290000e5)
- [x] Retire 3. [Squash the bugs](https://www.codewars.com/kata/56f173a35b91399a05000cb7) after CFML translation is moved

### Filling gaps

- [x] Move CFML translation from 3. to 2.

**Comment by hobovsky** [comment]
Kata 1. boils down to map + reduce. Kata 2. is a bit more complex, and generally is split + map + reduce. Out of the two, I think we do not need to have both, and that 2. is better to keep than 1. Let's keep 2. and retire 1. I did not check if tests in 2. are affected by potential bugs related to handling of consecutive spaces.

Kata 3. is bug fixing, and I think it has its place. I am not sure about the quality of the presented bug: most of issues are compilation errors and can be solved by following red squiggles in your IDE, or by just discarding all code and rewriting it from scratch. But still, I don't think it's a duplicate of 1. and 2. and would vote to keep it.

**Comment by ejini6969** [comment]
Keep 2, retire rest due to solutions can be copied from 2 with a minor tweak in the specific function used

**Comment by Kacarott** [comment]
In addition to hobovsky's reasoning, 2 has very many languages, so I vote to retire 1. Keep 2 and 3.

**Comment by Blind4Basics** [comment]
keep 2 only

**Comment by EloiseRosen** [comment]
Vote to retire 1, keep 2. Don't have a strong opinion on 3.

**Comment by benjaminzwhite** [comment]
Vote keep 2 only also -- in which case, small suggestion: add a clear definition of what a "word" is, because most of the questions/problems people have in discourse are due to being unclear on these kind of examples:

- `Let's` (this is treated as a word of length 5 - lots of peoples' solutions are treating this as being length 3) and
-  `21inc` (contains numeric chars, is considered as a word of length 5) 
 
being considered valid "words" (in Python tests at least).

**Comment by hobovsky** [comment]
There's 5 opinions to retire 3. vs. 2 opinions to keep it, so I think it's good to go.  
1 is unanimously retired, and 2. is kept.
