### ISSUE TITLE
Deduplicate - partitioning a string to odds & evens indexed

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#146]
Originally reported with #39

1. [Simple transposition](https://www.codewars.com/kata/57a153e872292d7c030009d4)
* 6 kyu
* 91% with 2.8k completions
* 1 pending issue
* 7 languages + 2 pending translations (Groovy, Haxe not covered by 2.)
* Aug 2016, author inactive

2. [Odd-Even String Sort](https://www.codewars.com/kata/580755730b5a77650500010c)
* 7 kyu
* 93% with 8.6k+ completions
* 1 pending issue
* 10 languages + 3 pending translations (C#, Haskell, TypeScript, D, Go, Rust not covered by 1.)
* Oct 2016, author active

------

### Conclusion

- Keep 2. [Odd-Even String Sort](https://www.codewars.com/kata/580755730b5a77650500010c)
- [x] Retire 1. [Simple transposition](https://www.codewars.com/kata/57a153e872292d7c030009d4)

### Filling gaps

- [x] Move Groovy translation from 1. to 2.
- [x] Move Haxe translation from 1. to 2.
- [x] Move Lua translation from 1. to 2.

**Comment by hobovsky** [comment]
Both kata are duplicates with a very minor difference w.r.t. minimal formatting of the answer in 2.
I think it will be better to keep kata 2. as more complete.
Please note that rank is not a very good guideline in case of this kata, because difficulty of the task can differ between languages: in some it will be a simple one-liner, in others characters have to be partitioned "manually".

**Comment by ejini6969** [comment]
Keep 2 due to higher completion and more languages

**Comment by Kacarott** [comment]
Keep 2, retire 1

**Comment by EloiseRosen** [comment]
Vote for keep 2, retire 1
