### ISSUE TITLE
Deduplicate - Case swapping

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#147]
From #39

1. [Case Swapping](https://www.codewars.com/kata/5590961e6620c0825000008f)
* 7 kyu
* letters and digits as inputs
* 92% with ~6.5k completions
* No pending issues
* 7 languages, no pending translations
* Published Jun 2015, author active

2. [altERnaTIng cAsE <=> ALTerNAtiNG CaSe](https://www.codewars.com/kata/56efc695740d30f963000557)
* 8 kyu
* ~~Only letters as inputs~~ letters and digits as inputs
* 90% with 33k+ completions
* 3 pending issues, one about being a duplicate of 1.
* 17 languages + 1 pending translation
* Published Mar 2016, author active

3. [Alternate case](https://www.codewars.com/kata/57a62154cf1fa5b25200031e)
* 7 kyu
* Inputs are not only letters
* 90% with 7.6k completions
* 3 pending issues, one about being a duplicate of 2.
* 10 languages + 3 pending translations
* Published Aug 2016, author inactive

4. [Strings: swap vowels' case](https://www.codewars.com/kata/5803c0c6ab6c20a06f000026)
* 7 kyu
* Only vowels are to be swapped
* 90% with 2.4k completions
* No pending issues
* 8 languages, no pending translations
* Published Oct 2016, author last active Jul 2022

----

### Conclusion

- Keep 2. [altERnaTIng cAsE <=> ALTerNAtiNG CaSe](https://www.codewars.com/kata/56efc695740d30f963000557)
- [x] Retire 1. [Case Swapping](https://www.codewars.com/kata/5590961e6620c0825000008f)
- [x] Retire 3. [Alternate case](https://www.codewars.com/kata/57a62154cf1fa5b25200031e) after translations are moved
- [x] Retire 4. [Strings: swap vowels' case](https://www.codewars.com/kata/5803c0c6ab6c20a06f000026) after any of F# translations is moved.

### Filling gaps

- [x] Move Clojure approved translation from 3. to 2.
- [x] Move COBOL approved translation from 3. to 2.
- [x] Move F# approved translation from 3., or pending F# translation from 4., to 2.
- [x] Move Nim pending translation from 3. to 2.

**Comment by hobovsky** [comment]
All kata are very similar, 2. is the simplest (requires no filtering), kata 1., 3., and 4. require one or two additional conditions (or not).

I think that 2. would be good to keep as the most complete. I am not sure if we need to keep any of 1., 3., and 4., and if we do, which one.

**Comment by ejini6969** [comment]
Keep 2 only since 1. and 3. solutions can be copied to pass 2. As for 4., it's just adding an extra conditional statement or using same regex concept, so it can be retired too ! (EDIT: In JS && CS version of 2, prototyping is used which adds as an extensive feature compared to other katas)

**Comment by benjaminzwhite** [comment]
Agree with keeping 2 only; most complete, good kyu ranking, and also best explanation/examples in kata description.

**Comment by heroicfun** [comment]
vote for keep 2, retire any

**Comment by Kacarott** [comment]
Keep 2

**Comment by error256** [comment]
> 2. is the simplest (requires no filtering)

2 has digits as well.

**Comment by hobovsky** [comment]
> > 2. is the simplest (requires no filtering)
> 
> 2 has digits as well.

... and how did I miss this? :|

**Comment by EloiseRosen** [comment]
vote for keep 2, retire the others

**Comment by Chrono79** [comment]
What I don't like from 2, it's some languages use String.Prototype or Class methods and some others don't, making the shared rank of 8 kyu unfair.

**Comment by VanessaGreene** [comment]
Retired 3
