### ISSUE TITLE
Deduplicate - sum of vararg list

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#148]
From #39

1. [Unlimited Sum](https://www.codewars.com/kata/536c738e49aa8b663b000301)
* 7kyu
* Omit non-numeric arguments
* 89% with ~4.5k completions
* 2 pending issues
* 3 languages, no pending translations
* Published May 2014, author inactive

2. [Sum of numerous arguments](https://www.codewars.com/kata/55c5b03f8c28da9a51000045)
* 7kyu
* return -1 if arguments contain negative numbers
* 93% with ~2.8k completions
* 1 pending issue
* 4 languages, no pending translations
* Published Aug 2015, author inactive

3. [Sum of all arguments](https://www.codewars.com/kata/540c33513b6532cd58000259)
* 7kyu
* No additional requirements
* 87% with ~8.2k completions
* No pending issues
* 7 languages, no pending translations. Covers all languages of 1. and 2.
* Published Sep 2014, author deleted

-----

### Conclusion

- [x] Retire 1. [Unlimited Sum](https://www.codewars.com/kata/536c738e49aa8b663b000301)
- [x] Retire 2. [Sum of numerous arguments](https://www.codewars.com/kata/55c5b03f8c28da9a51000045)
- Keep 3. [Sum of all arguments](https://www.codewars.com/kata/540c33513b6532cd58000259)

**Comment by hobovsky** [comment]
From all the kata, I vote to keep 3. as the most complete and cleanest. Retire 1. and 2., because they have fewer languages, and additional requirements are more annoying rather than interesting.

Fortunately, all translations stick to the idea of users having to define var args by themselves (except for C, but I think for C it's OK), but maybe it would be worth to spell out this aspect explicitly somewhere, because I am afraid it will attract inconsistent translations.

**Comment by Kacarott** [comment]
Agree with keeping 3

**Comment by KayleighWasTaken** [comment]
Keep 3.
