### ISSUE TITLE
Kata trail: Escape the Mines !

### ISSUE THREAD

**Issue by Madjosz** [codewars/content-issues#149]
5kyu kata [Escape the Mines !](https://www.codewars.com/kata/5326ef17b7320ee2e00001df) is a kata from 2014-08-13 and should be retired because of the following reasons:

* standard path-finding kata, so a duplicate
* no random tests in any language (JS, Haskell, Python, Ruby and pending Java)
* IMO `map` input is transposed to natural perception. This makes it difficult to guess what "right", "left", "up", "down" should refer to
* input coordinates are a dictionary in Python/Ruby which feels strange
* input `map` can be modified by user and then influences subsequent tests

React 👍 to keep or 👎 to retire.

----

### Conclusion

- [x] Retire  [Escape the Mines !](https://www.codewars.com/kata/5326ef17b7320ee2e00001df)

**Comment by hobovsky** [comment]
There is 6 pending issues about botched design, setup, and implementation. I agree with retiring, especially that there are many pathfinding kata already.

**Comment by Blind4Basics** [comment]
I believe it's the one where you have to check neighbors in a specific order to actually pass the tests, no? If not, we should retire that other one as well (once someone finds it again...)

**Comment by hobovsky** [comment]
> I believe it's the one where you have to check neighbors in a specific order to actually pass the tests, no? If not, we should retire that other one as well (once someone finds it again...)

I am not sure if this is one is the kata you remember, but there's [this comment](https://www.codewars.com/kata/5326ef17b7320ee2e00001df/discuss/javascript#54afa4ac56f22dab8200066a):

> most of the solutions (mine included) would fail if they tried "up" first because of the last test having mulitple possible path (the 'up' first would be a valid but longer path than expected solution). should add some test case in the same spirit for defeating all solution that relies on trying the same direction first.

**Comment by hobovsky** [comment]
With 9 x :-1: I think the conclusion is clear and the kata is good to get rid of.
