### ISSUE TITLE
List of duplicate kata to process

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#15]
A list collected by @ejini6969 of duplicate kata. The list is to be processed and kata should be either unpublished by a mod, or added to the [list of duplicate kata](https://github.com/Codewars/content-issues/wiki/List-of-Possible-Duplicate-Kata) to keep the record.

Format of the list: "duplicate (original)".

**Comment by ejini6969** [comment]
I'll add to the list when I had the time and there's more duplicate betas to be added.

**Comment by ejini6969** [comment]
Since I can't edit the original post, here are more of those duplicates ~~~~

\[hobovsky: all links processed, thanks!]

Last batch of duplicates I assume ~~

**Comment by hobovsky** [comment]
Thanks for collecting these, that was a great job!

All kata from your lists were either unpublished, or added to [this list](https://github.com/Codewars/content-issues/wiki/List-of-Possible-Duplicate-Kata) as needing some more attention.

Feel free to add any kata there or post a new issue when you find more.
