### ISSUE TITLE
Deduplicate - Remove or transform vowels

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#150]
From #39

1. [Disemvowel Trolls](https://www.codewars.com/kata/52fba66badcd10859f00097e)
* Remove all vowels
* 7kyu
* 89% with 223k+ completions
* 2 pending issues
* 23 languages + 5 pending translations
* Published Feb 2014, author inactive

2. [All Star Code Challenge #3](https://www.codewars.com/kata/58640340b3a675d9a70000b9)
* Remove vowels, input only lowercase
* 7kyu
* 92% with 3k completions
* 1 pending issue
* 5 languages + 4 pending translations (Go pending translation not covered by 1.)
* Published Dec 2016, author inactive

3. [Vowel remover](https://www.codewars.com/kata/vowel-remover)
* Remove only lowercase vowels from upper- and lower-case input
* 8kyu
* 92% with ~21k completions
* 2 pending issues
* 7 languages + 6 pending translations (COBOL approved translation, Go pending translation not covered by 1.)
* Published May 2015, author inactive

4. [Exclamation marks series #11: Replace all vowel to exclamation mark in the sentence](https://www.codewars.com/kata/57fb09ef2b5314a8a90001ed)
* Change all vowels to `'!'`
* 8kyu
* 93% with 16k completions
* 1 pending issue
* 12 languages, no pending translations
* Published Oct 2016, author inactive

5. [Vowel Changer](https://www.codewars.com/kata/597754ba62f8a19c98000030)
* Change all vowels to a requested character
* 7kyu
* 92% with ~1.7k completions
* No pending issues
* JS and python only
* Published Jul 2017, author inactive

6. [Vowel One](https://www.codewars.com/kata/580751a40b5a777a200000a1)
* Build a new string by mapping vowels to '0' and consonants to '1'.
* 7kyu
* 93% with 4.3k completions
* No pending issues
* 4 languages + 1 pending translation
* Published Oct 2016, author deleted

----

### Conclusion

- Keep 1. [Disemvowel Trolls](https://www.codewars.com/kata/52fba66badcd10859f00097e)
- [x] Retire 2. [All Star Code Challenge #3](https://www.codewars.com/kata/58640340b3a675d9a70000b9) after Go translation gets moved to 1.
- [x] Retire 3. [Vowel remover](https://www.codewars.com/kata/vowel-remover) after Go and COBOL translation get moved to 1.
- Keep 4. [Exclamation marks series #11: Replace all vowel to exclamation mark in the sentence](https://www.codewars.com/kata/57fb09ef2b5314a8a90001ed)
- [x] Retire 5. [Vowel Changer](https://www.codewars.com/kata/597754ba62f8a19c98000030)

### Filling gaps

- [x] Move Go pending translation from 2. or 3. to 1.
- [x] Move COBOL approved translation from 3. to 1,

**Comment by hobovsky** [comment]
I think kata here can be separated in separate groups:

- Remove vowels: out of kata 1., 2., and 3., I think the 1. would be best to keep due to the most languages. I'd vote to retire 2. and 3.
- Change vowels to some character: I like kata 5. a bit more than 4. because it's more generic, but I think that keeping 4. will be better because it has many more languages. 
- Kata 6., as dull as it is, is not necessarily close enough to be retired as a duplicate (in this set, at least). I'm fine with keeping it and handling in another round of "trivial `map` kata", or we can get rid of it now if you all prefer.

**Comment by KayleighWasTaken** [comment]
Keep 1, 5, and 6. Retire 2, 3, and 4.

For reasoning, see hobs comment. (I don't think that retiring 6 is in scope of this issue).

**Comment by EloiseRosen** [comment]
vote for keep 1, 4, and 6, retire the others

**Comment by ejini6969** [comment]
Keep 1 and 4 only, retire the rest! There's too many string substitution or replacement katas in the site and losing 6. adds no harm to the community (Except the author maybe :-)~~ 

EDIT: Owh wait, author long gone alr ^_^ (no harm whatsoever now ~~

**Comment by benjaminzwhite** [comment]
Agree with keep 1 and 4 based on hobovsky's reasoning. Agree retire 2,3,5.
 
Agnostic about 6 - but tend to agree with ejini about being r u t h l e s s (there's a comment in the discourse with someone saying "how many vowel katas are there on CW?" so...)

**Comment by hobovsky** [comment]
Almost everyone agrees with keeping 1. and 4. and retiring 2., 3., and 5.  
I have totally no idea what to do with 6. I will leave it as inconclusive for now, and maybe there will be some more opinions before remaining translations get moved and the issue gets closed.

**Comment by ejini6969** [comment]
With Go translation published earlier by someone and now COBOL has also been transferred, this one  can be concluded

**Comment by VanessaGreene** [comment]
Retired 2 and 3. Will I keep this open until a decision is made one 6?

**Comment by hobovsky** [comment]
I think that 6. will stay for now.
