### ISSUE TITLE
Deduplicate - get numbers / non-numerics from string

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#154]
From #39

1. [Filter the number](https://www.codewars.com/kata/55b051fac50a3292a9000025)
* 7 kyu
* Filter out non-digits. Result is of a numeric type.
* 94% with ~10k completions
* 1 pending issue
* 9 languages (C++, Java, NASM not covered by 2.)
* Published Jul 2015, author inactive.

2. [Get number from string](https://www.codewars.com/kata/57a37f3cbb99449513000cd8)
* 8 kyu
* Filter out non-digits. Result is of a numeric type.
* 92% with ~7k completions
* 3 pending issues
* 7 languages + 1 pending translation (F#, D not covered by 1.)
* Published Aug 2016, author inactive.

3. [Failed Filter - Bug Fixing #3](https://www.codewars.com/kata/55c606e6babfc5b2c500007c)
* 7 kyu
* Filter out digits. Bug fixing.
* 90% with ~2.5k completions
* 3 pending issues
* 5 languages, no pending translations
* Published Aug 2015, author the same as 1.

4. [Numbers in strings](https://www.codewars.com/kata/59dd2c38f703c4ae5e000014)
* 7kyu
* Additional processing required after filtering
* 93% with ~5k completions
* 1 pending issue
* 14 languages, no pending translations
* Published Oct 2017, author active

-----

### Conclusion

- Keep 1. [Filter the number](https://www.codewars.com/kata/55b051fac50a3292a9000025)
- [x] Retire 2. [Get number from string](https://www.codewars.com/kata/57a37f3cbb99449513000cd8)
- Keep 3. [Failed Filter - Bug Fixing #3](https://www.codewars.com/kata/55c606e6babfc5b2c500007c)
- Keep 4. [Numbers in strings](https://www.codewars.com/kata/59dd2c38f703c4ae5e000014)

### Filling gaps

- [x] Move approved F# translation from 2. to 1.
- [x] Move D pending translation from 2. to 1.

**Comment by hobovsky** [comment]
Kata 1. and 2. are exact duplicates, and I think 1. is a bit better to keep than 2. I vote to keep 1. and retire 2.

Kata 3. and 4. were reported on the list of dupes by ejini, but I don't think they are close enough duplicates to be in scope of this issue. I think both can be kept.

**Comment by KayleighWasTaken** [comment]
Agree with hobs. Keep 1, 3, 4; Retire 2

**Comment by CiprianAmza** [comment]
1 and 2 are exact duplicates (same solution pass both katas). I vote to retire the second (because it has 3 issues).

The 3rd one is the opposite of the first two, I see no reason to be retired, since it's not a duplicate. Same as both of you: retire 2, keep 1, 3, 4.

**Comment by EloiseRosen** [comment]
retire 2, keep the others sounds fine

**Comment by VanessaGreene** [comment]
Retired 2. Sorry for the delay here.
