### ISSUE TITLE
Deduplicate - multiply elements in array

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#155]
From #39

1. [Beginner - Reduce but Grow](https://www.codewars.com/kata/57f780909f7e8e3183000078)
* 8kyu
* all inputs valid
* 92% with ~66k completions
* 1 pending issue
* 25 languages, no pending translations
* Published Oct 2016, author active

2. [Product of Array Items](https://www.codewars.com/kata/5901f361927288d961000013)
* 7kyu
* `null` input or empty array are considered invalid and should return `null`.
* 88% with ~3.6k completions
* 1 pending issue, related to overflow in JS translation
* 9 languages + 4 pending translations, Groovy not covered by 1.
* Published Apr 2017, author inactive.

----

### Conclusion

- Keep 1. [Beginner - Reduce but Grow](https://www.codewars.com/kata/57f780909f7e8e3183000078)
- [x] Retire 2. [Product of Array Items](https://www.codewars.com/kata/5901f361927288d961000013)

### Filling gaps

- [x] Move approved Groovy translation from 2. to 1.

**Comment by hobovsky** [comment]
I think that even on this difficulty level, two identical tasks which differ only by validation of input are rather annoying than useful. It would not hurt to keep only 1. and get rid of 2.

**Comment by CiprianAmza** [comment]
Even if they do pretty much look similar, validation of input (especially at 7 kyu) may be something useful. I would suggest to keep both of them. If one of them has to be removed, I would keep the second one, because of the validation input (which is most probably better for 7 kyu than for 8 kyu).

**Comment by Blind4Basics** [comment]
but there are more languages in the 8kyu (and 8kyu is fine without the (boring) validation, I guess)

**Comment by EloiseRosen** [comment]
Vote for keep 1, retire 2 (language count, and I don't like the input validation personally)

**Comment by CiprianAmza** [comment]
> but there are more languages in the 8kyu (and 8kyu is fine without the (boring) validation, I guess)

Right, more languages is an important fact. Then I also think that keeping the first would fit better. Still, I would keep both, if possible.

**Comment by benjaminzwhite** [comment]
Important point for kata 1 - in Python there is no test for empty input list `[]`. 

This is important because, if users use `from math import prod` (available only since Python 3,8) then, somewhat counter-intuitively, the returned result of `prod( [] )` is actually `1` because the default start value of `prod` is `1`.

So in Python at least, if you keep kata 1, there should be a fixed test with `[]` with expected result = `0` or `None` or whatever, so that users can learn about this counter-intuitive behaviour of `math prod`.

Currently there are ~130 solutions using this approach that should fail on an empty input `[]`.

**Comment by hobovsky** [comment]
[Vacuous product](https://en.wikipedia.org/wiki/Empty_product) is difficult.  
Also, the kata description explicitly states "non-empty array".

**Comment by pete-garvin-bp** [comment]
Hey all, 

General question about this whole de-duplication process... Isn't some degree of repetition integral to learning? Especially at the beginner / 8kyu level? I certainly know it helped when I was beginning
