### ISSUE TITLE
Deduplicate - uppercase vowels

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#156]
From #39

1. [Uppercase all vowels](https://www.codewars.com/kata/57a1e23853ba339caf001000)
* 7kyu
* 81% with 170+ completions
* 2 pending issues
* 2 languages, no pending translations, no overlap with 2.
* Published Aug 2016, author inactive.

2. [Changing letters](https://www.codewars.com/kata/5831c204a31721e2ae000294)
* 7kyu
* 91% with 3.3k+ completions
* 3 pending issues
* 6 languages, no pending translations, no overlap with 1.
* Published Nov 2016, author inactive.

------

### Conclusion

- [x] Retire 1. [Uppercase all vowels](https://www.codewars.com/kata/57a1e23853ba339caf001000)
- Keep 2. [Changing letters](https://www.codewars.com/kata/5831c204a31721e2ae000294)

### Filling gaps

- [x] Move F# translation from 1. to 2.
- [x] Move Haskell translation from 1. to 2.

**Comment by hobovsky** [comment]
Both kata seem to be exact duplicates and could be merged. I propose to keep 2., move translations from 1. to 2. because it's fewer of them, and finally retire ~~2~~ 1.

**Comment by CiprianAmza** [comment]
First one is Haskell/F# only, while the second one has no Haskell/F# translation. Retiring first and moving the two translations to the second one?

**Comment by EloiseRosen** [comment]
> and finally retire 2

you mean finally retire 1?

**Comment by EloiseRosen** [comment]
vote for retire 1, keep 2, due to language count

**Comment by KayleighWasTaken** [comment]
more sensible to retire 1 and keep 2 in my opinion
