### ISSUE TITLE
Deduplicate - Morse decoder

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#157]
1. [Decode Morse](https://www.codewars.com/kata/54b0306c56f22d0bf9000ffb)
* 6 kyu
* 88% with ~1k completions
* 3 pending issues, 2 about being a duplicate
* 3 languages
* Published Jan 2015, author inactive

2. [Decode the Morse code](https://www.codewars.com/kata/54b724efac3d5402db00065e)
* 6 kyu
* 89% with 88k completions
* 2 pending issues
* 23 languages, 2 pending issues
* Published Jan 2015, author active

---- 

### Conclusion

- [x] Retire 1. [Decode Morse](https://www.codewars.com/kata/54b0306c56f22d0bf9000ffb)
- Keep 2. [Decode the Morse code](https://www.codewars.com/kata/54b724efac3d5402db00065e)

**Comment by hobovsky** [comment]
The kata are almost exact duplicates, solutions differ by a single space and a name of a preloaded variable.

I vote to keep 2. as more complete, and retire 1. as duplicate.

**Comment by benjaminzwhite** [comment]
I voted to keep 2, but noticed that in Python there are no random tests whatsoever.

**updates:** 
- Python fork with random tests and new test framework approved by B4B, issue closed on kata page.
- I removed "Decode the Morse Code" from main list of kata to update.

~~I therefore created a fork, which adds random tests and updates to new Python test framework:~~

~~[Link to Issue raised on kata discourse page](https://www.codewars.com/kata/54b724efac3d5402db00065e/discuss/python#634a7c5d777408003d41f620)~~

~~[Direct link to Python fork with random tests and updated test framework](https://www.codewars.com/kumite/634a7418a4725f004a8288af?sel=634a7418a4725f004a8288af)~~

~~Please update the main Python list if you approve the fork, or let me know in the kata discourse and I'll do it:~~

~~[https://github.com/codewars/content-issues/wiki/List-of-Python-Kata-to-Update](https://github.com/codewars/content-issues/wiki/List-of-Python-Kata-to-Update)~~

~~Please check for the Python fork that I have implemented the "back-compatibility" correctly where I first try to import the solution under the old naming convention `decodeMorse` before importing `decode_morse` - it's the first kata I've updated where there is such a requirement.~~
