### ISSUE TITLE
Retire " -Reverse it, quickly!"

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#158]
Kata: [-Reverse it, quickly!](https://www.codewars.com/kata/59ae589c07157afba80000a7/).

I think this kata is bad and should be removed because:
- It's code golf.
- It relies on an erroneous implementation and malformed implementation of comparer function which is not, and has never been, guaranteed to work.
- It prevents update of Node to newer version. The kata is Node 8 only and does not work with newer versions of Node because it relies on broken behavior.
- People don't like it, satisfaction rating is 76%.

Alternative: increase character limit and make it work with some other, valid approach, but I have no good idea what would it be.

Please vote 👎  to retire or 👍  to keep.

-----

### Conclusion

- [x] Retire as unsalvageable.

**Comment by nuoliveira** [comment]
There exists already one with a valid approach: [The soul of wit: reverse an array](https://www.codewars.com/kata/59b81886460387d8fc000043)

**Comment by B1tsTM** [comment]
Because the kata relies on old version of Node, it cannot ever be updated, and so it should be retired eventually.

Correction: it doesn't appear to be affected by updating to later node version, but it only works with small arrays. Despite that, it can be considered a duplicate kata.

**Comment by hobovsky** [comment]
> There exists already one with a valid approach: [The soul of wit: reverse an array](https://www.codewars.com/kata/59b81886460387d8fc000043)

So basically fixing the kata by changing to another approach would make it a duplicate, right?

Thanks for this input.
