### ISSUE TITLE
Deduplicate - add spaces between each characters

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#164]
From #39

1. [V A P O R C O D E](https://www.codewars.com/kata/5966eeb31b229e44eb00007a)
* Spaces in input should be skipped
* 7kyu
* 92% with ~9k completions
* No pending issues
* 16 languages, 3 pending translations (8 unique from 2.)
* Published Jul 2017, author inactive

2. [Spacify](https://www.codewars.com/kata/57f8ee485cae443c4d000127)
* 7kyu
* Input spaces are treated as regular characters
* 92% with ~7k completions
* 2 pending issues
* 12 languages, 4 pending translations (3 unique)
* Published Oct 2016, author deleted

----

### Conclusion

- Keep 1. [V A P O R C O D E](https://www.codewars.com/kata/5966eeb31b229e44eb00007a)
- [x] Retire 2. [Spacify](https://www.codewars.com/kata/57f8ee485cae443c4d000127) after moving translations to 1.

### Filling gaps

- [x] Move PHP approved translation
- [x] Move Swift approved translation
- [x] Move TypeScript pending translation
- [x] Move NIM pending translation

**Comment by hobovsky** [comment]
Maybe the aspect of handling spaces makes the kata sufficiently different for 7 kyu tasks, but I still think they are very similar. Additionally, I think that one additional simple condition in 1. makes the rank more suitable. I think that 1. can be kept as more interesting, and 2. can be retired as a less interesting/duplicate.

**Comment by ejini6969** [comment]
Agree to keep 1 and retire 2 due to above reason && author for 2 has already long gone!

**Comment by VanessaGreene** [comment]
@hobovsky Have translations been added to vaporcode?

**Comment by Kacarott** [comment]
@VanessaGreene The checkboxes are ticked, so I would assume so.

**Comment by hobovsky** [comment]
Yes, checkboxes are ticked, so everything is done. However, in newer tickets, I organized tasks a bit differently: https://github.com/codewars/content-issues/issues/203 and a kata is ready for retirement if all checkboxes in its sub-bullets are checked (or if there is none).

**Comment by VanessaGreene** [comment]
Spacify is now retired
