### ISSUE TITLE
Deduplicate - euclidean distance

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#165]
From #39

1. [Length of the line segment](https://www.codewars.com/kata/55f1786c296de4952f000014)
* Result is a formatted string, input is an array of arrays
* 7kyu
* 88% with 1150 completions
* No pending issues, but there are some posts mentioning issues with trailing zeros
* 3 languages, no pending translations
* Published Sep 2015, author inactive

2. [Distance Between 2 Points on a Cartesian Plane](https://www.codewars.com/kata/5944f3f8d7b6a5748d000233)
* Input is two arrays, output is a number rounded to `n` decimal places with strict equality assertions
* 7kyu
* 84% with ~400 completions
* No pending issues, one resolved issue about being a duplicate
* 4 languages, no pending translations (Crystal)
* Published Jun 2017, author inactive

3. [Geometry Basics: Distance between points in 2D](https://www.codewars.com/kata/58dced7b702b805b200000be)
* Input is two instances of a custom data type of `Point`, output is a number compared with fuzzy equality
* 8kyu
* 88% with ~8.6k completions
* 1 pending issue, and come complaints on the rank
* 8 languages, 2 pending translations
* Published Mar 2017, author inactive

4. [[Geometry A-2]: Length of a vector](https://www.codewars.com/kata/554dc2b88fbafd2e95000125)
* Input is array of arrays, test use correct fuzzy assertions (in most of languages)
* 7kyu
* 89% with ~2700 completions
* No pending issues
* 6 languages, no pending translations
* Published May 2015, author last active Sep 2022

----

### Conclusion

- Keep 3. [Geometry Basics: Distance between points in 2D](https://www.codewars.com/kata/58dced7b702b805b200000be)
- [x] Retire 1. [Length of the line segment](https://www.codewars.com/kata/55f1786c296de4952f000014)
- [x] Retire 2. [Distance Between 2 Points on a Cartesian Plane](https://www.codewars.com/kata/5944f3f8d7b6a5748d000233)
  - [x] Move approved Crystal translation to 3.
- [x] Retire 4. [[Geometry A-2]: Length of a vector](https://www.codewars.com/kata/554dc2b88fbafd2e95000125)
  - [x] Move approved CoffeeScript translation to 3.
  - [x] Move approved Haskell translation to 3.

**Comment by hobovsky** [comment]
Noe: I did not solve all of above kata in every available language, so quality of tests in languages I haven't trained might differ from what I saw in languages I trained.

All of the kata are very similar, differences are limited to extracting coords from inputs and rounding the result.

Kata 1. and 2. are IMO not worth keeping if only due to wonky handling of results.
Kata 3. and 4. are technically better, and 4. is older, but I think I would retire it and keep 3. due to amount of languages, while potential rounding issues are easy to fix in tests. I think that custom data type in 3. is also a nice touch. One potential problem can be its 8 kyu rank.

**Comment by JohanWiltink** [comment]
Kill everything that uses rounding, either by solver or internally. Keep 4 only.

Fixing tests is almost as much work as fully transplanting a language, so amount of languages works _against_ 3 here.

**Comment by monadius** [comment]
Keep 3 only: It has more languages and 8 kyu is a better rank for this problem. Moreover, 4 has some issues with the C# translation where a custom input type is used.

It is easy to fix rounding issues in 3 (only Python and Ruby should be fixed).

**Comment by JohanWiltink** [comment]
JavaScript would definitely need fixing in 3.

**Comment by VanessaGreene** [comment]
Retired 4
