### ISSUE TITLE
Deduplicate - check if left side of an array is equal to right side

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#166]
From #39

Both kata allow for O(n^2) solutions and treat "left to the beginning" or "right to the end" as having sum of 0.

1. [Peak array index](https://www.codewars.com/kata/5a61a846cadebf9738000076)
* 7kyu
* 93% with ~2.6k completions
* No pending issues
* 8 languages, 1 pending translation (COBOL not covered by 2.)
* Published Jan 2018, author active

2. [Equal Sides Of An Array](https://www.codewars.com/kata/5679aa472b8f57fb8c000047)
* 6kyu
* 91% with 91k completions
* 1 pending issue
* 18 languages, 5 pending translations
* Published Dec 2015, author inactive

----

### Conclusion

- Keep 2. [Equal Sides Of An Array](https://www.codewars.com/kata/5679aa472b8f57fb8c000047)
- [x] Retire 1. [Peak array index](https://www.codewars.com/kata/5a61a846cadebf9738000076)

### Filling gaps

- [x] Move COBOL translation

**Comment by hobovsky** [comment]
Both kata seem to be exact duplicates, at least in Python. I did not verify consistency between translations w.r.t. required complexity, generation of special cases (multiple valid answers), or edge cases.

I vote to keep 2. as more complete, _and_ harden it to require O(n) solutions only. Even when not hardened, 1. is still identical and, IMO, not necessary.

**Comment by Kacarott** [comment]
I agree with removing 1, keeping 2.
