### ISSUE TITLE
Kata trial - Remove Zeros

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#167]
[Remove Zeros](https://www.codewars.com/kata/52aae14aa7fd03d57400058f)

The kata attempts to impose restrictions which are impossible to enforce. Restricted methods are not blocked, the requirement of "no temporary arrays or objects" is not checked at all.  
The kata is also very difficult to translate but this does not stop users from posting translations into languages which make the restrictions even more difficult to enforce.

As noticed by JohanWiltink below, there already exists a kata identical to this one, minus restrictions: [Moving Zeros To The End](https://www.codewars.com/kata/52597aa56021e91c93000cb0)

Vote 👎 to retire or 👍 to keep.

-----

### Conclusion

- [x] Retire [Remove Zeros](https://www.codewars.com/kata/52aae14aa7fd03d57400058f)

**Comment by JohanWiltink** [comment]
The restrictions are unenforceable, and without the restrictions it's a duplicate. Retire with prejudice.

**Comment by 4500zenja1** [comment]
Yup, that kata has come up later than MZTTE, plus no restrictions => retire in favor of MZTTE, especially cuz the latter one has more languages and solutions but less restrictions.
