### ISSUE TITLE
Retire - splicing

### ISSUE THREAD

**Issue by JohanWiltink** [codewars/content-issues#168]
[splicing](https://www.codewars.com/kata/splicing) is stuck on `Node 10.x`, has multiple open `Issue`s, and has terrible design and execution:
* no random tests
* no enforcement of the requirements / restrictions
* no requirement that the `Array.prototype` method be non-enumerable
* mutating `this`
* functionality different than the native JS method
* functionality already implemented by native method `filter`
*  inconsistent return values

`14` solutions in CS, slightly over `1000` in JS.
It's not strictly a duplicate; there are two other kata asking to reimplement `splice` but they require duplicating the actual native functionality, and they are 5kyu instead of 7kyu.

It's just not worth the effort to me to update it to the current JS version.

To clean out `Node 10.x`, retire this kata.

Please up- or downvote this issue. (:+1: retire / :-1:  keep)

**Comment by Blind4Basics** [comment]
@JohanWiltink : "upvoting" the issue would mean the user agrees with you, so you _might_ wanna change your smiley. ;)

**Comment by JohanWiltink** [comment]
I voted both ways, to have both smilies available for people to vote.

**Comment by Blind4Basics** [comment]
@kazk: kata ready for retirement : 6 votes retire / 1 keep (@JohanWiltink : you can remove your second smiley, which doesn't reflect your opinion)
