### ISSUE TITLE
Another kata about braces

### ISSUE THREAD

**Issue by 4500zenja1** [codewars/content-issues#169]
Following #59 and #86, Voile has found another **beta** kata called ["Parsing & Automata - Matching Bracket Lists & Context-Free Grammars"](https://www.codewars.com/kata/58820ac243ca047e68000012) raised a CW issue about its similarity to ["Valid Parenthesis"](https://www.codewars.com/kata/valid-parentheses) and many others which have been mentioned in the Github issues before.

- Beta
- 40 completions
- 1 language (C++)
- 4 issues (one of which is about duplication)
- If the random tests will be implemented (BTW I've made the translation which should resolve this issue, available [here](https://www.codewars.com/kumite/63ac9e10b1ee6300588f3ab2)), you have to remove `throw` lines — and without it that's a duplicate of "Valid Parenthesis" but with `[]`
- Author last time seen on November 2022
- Kata is published on January 2017

**Comment by ejini6969** [comment]
Vote for retirement

**Comment by hobovsky** [comment]
After collecting a downvote, the kata got auto-retired as hopeless.

I am going to close this thread as not relevant anymore.
