### ISSUE TITLE
Deduplicate - sort array / string by last character

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#173]
From #39

1. [sort array by last character](https://www.codewars.com/kata/55aea0a123c33fa3400000e7)
* Input is an array of strings and numbers, without any explanation how non-strings should be handled
* 7kyu
* Satisfaction 84% with 200 completions
* 2 pending issues
* 4 languages, no pending translations, all covered by 2.
* Published Jul 2015, author inactive

2. [Sort by Last Char](https://www.codewars.com/kata/57eba158e8ca2c8aba0002a0)
* Input is a string which needs to be split
* 7kyu
* Satisfaction 92% with ~7k completions
* 3 pending issues
* 11 languages, no pending translations
* Published Sep 2016, author active

-----

### Conclusion

- Keep 2. [Sort by Last Char](https://www.codewars.com/kata/57eba158e8ca2c8aba0002a0)
- [x] Retire 1. [sort array by last character](https://www.codewars.com/kata/55aea0a123c33fa3400000e7)

**Comment by hobovsky** [comment]
Kata 1. seems to be worse than 2. because of annoying ints in inputs which are unexpected and underspecified.  
Kata 2. has many languages, and input being one long string makes the task arguably more complex/interesting.

Both kata are identical w.r.t. requirement of sorting: both expect stable sort by the same key.

My vote is to retire 1. and keep 2.

**Comment by Kacarott** [comment]
Retire 1, keep 2

**Comment by JohanWiltink** [comment]
Kill 'em both. There are enough sorting kata, last element doesn't make it special.

#2 encodes a list of strings as a string. I don't like that.

**Comment by hobovsky** [comment]
The "kill'em both" vote was heard, but it got severely outnumbered by "retire 1. and keep 2."  Kata 2. stays then, at least for now.
