### ISSUE TITLE
Deduplicate - how many fridays

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#175]
From #39

1. [Unlucky Days](https://www.codewars.com/kata/56eb0be52caf798c630013c0/)
* 7 kyu
* Find all Friday 13th in a given year
* Satisfaction 92% with 12.5k completions
* No pending issues
* 19 languages, no pending translations
* Published Mar 2013, author active

2. [TGI Friday!!](https://www.codewars.com/kata/5a0d6d8c6975982b5b000383)
* 6 kyu
* In a  range of years, count all months which have Friday as their last day
* Satisfaction 89% with 836 completions
* No pending issues
* Only JS approved, pending TS translations
* Published Nov 2017, author inactive

3. [1st day of month that are Sunday in a year range](https://www.codewars.com/kata/587dfbfc80be384fd30002de)
* 7 kyu
* In a range of years, count all months which start on Sunday. `endYear` may be less than `startYear`.
* Satisfaction 85% with 371 completions
* 2 pending issues
* Only JS approved, pending TS translations
* Published Jan 2017, author inactive 

4. [Friday the 13ths](https://www.codewars.com/kata/540954232a3259755d000039)
* 6 kyu
* In a range of years, count all Friday 13th. Answer needs to be formatted in a very annoying way.
* Satisfaction 93% with 3k completions
* No pending issues
* 6 languages, 1 pending translation
* Published Sep 2014, author deleted

5. [Find all Fridays the thirteens](https://www.codewars.com/kata/5aaf822725ebf9f2a600008e) -  exact duplicate of 4., unpublished.

-----

### Conclusion

- Keep 1. [Unlucky Days](https://www.codewars.com/kata/56eb0be52caf798c630013c0/)
- Keep 2. [TGI Friday!!](https://www.codewars.com/kata/5a0d6d8c6975982b5b000383)
- [x] Retire 3. [1st day of month that are Sunday in a year range](https://www.codewars.com/kata/587dfbfc80be384fd30002de)
- [x] Retire 4. [Friday the 13ths](https://www.codewars.com/kata/540954232a3259755d000039)

**Comment by hobovsky** [comment]
Kata 1. has the most languages, and is the simplest of the all four. I think it can be kept just due to amount of languages. It uses reasonable input ranges, and it's the only one which specifies used calendar.

Kata 2. is, IMO, the most interesting because the notion of "the last day of a month" is not necessarily trivial. I like this one the most of all four, and would vote to keep it.

Kata 3. is a trivial modification of the "Frida 13th" task. I think it will be not necessary if 1. and 2. are kept. Handling of the flipped year boundaries in undocumented and unnecessary annoyance. Additionally, it uses not really reasonable year ranges.

Kata 4. is extension if 1. into a range of years. The task is more general than 1., but I think it's not worth keeping when 1. and 2. are available. Required formatting of the answer makes me hate this kata even more.

I vote to keep 1. and 2., and retire 3. and 4. I think it's not bad to be left with two kata and even if they are somewhat similar, date manipulation is an underappreciated topic.

**Comment by Madjosz** [comment]
keep 1. most languages, appropriate rank
keep 2. very interesting task
retire 3. combination of 1. and 2., undocumented behaviour for end < start
retire 4. mm/dd/yyyy, do I need to say more?

**Comment by suic86** [comment]
IMO 1. is different than then the other three and it's easier then them. No 1. and 4. are the most similar.

I would definitely:

* Keep 1. - it's simple, properly ranked, translated to many languages
* Keep 2. - it's an interesting task and differs enough from the others
* Retire 4. - too similar to 1., not properly ranked and has annoying output format

I'm not sure about number 3.
