### ISSUE TITLE
Deduplicate - count pairs

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#179]
From #39

1. [Find all pairs](https://www.codewars.com/kata/5c55ad8c9d76d41a62b4ede3)
* 7kyu
* input: array of integers
* Satisfaction 93% with ~5k completions
* 3 pending issues 
* 7 languages, no pending translations (PHP unique)
* Published Feb 2019, author inactive

2. [Pair of gloves](https://www.codewars.com/kata/58235a167a8cb37e1a0000db)
* 6kyu
* input: array of strings
* Satisfaction 94% with 10k completions
* No pending issues
* 14 languages + 1 pending translation
* Published Nov 2016, author active

### Conclusion

- [x] Retire 1. [Find all pairs](https://www.codewars.com/kata/5c55ad8c9d76d41a62b4ede3)
- Keep 2. [Pair of gloves](https://www.codewars.com/kata/58235a167a8cb37e1a0000db)

### Filling gaps

- [x] Move PHP translation from 1. to 2.

**Comment by hobovsky** [comment]
Both kata differ only by rank and type of input elements.  
Input with strings seems to be a bit more interesting in some languages, but OTOH meaning of "pair" used by it is a bit awkward, because two red gloves not necessarily constitute a pair :)

I think I would prefer to keep 2. as having more languages, and I like string inputs a bit more. Retire 1.

**Comment by Blind4Basics** [comment]
your conclusion seems in contradiction with the previous sentence.... => ?

**Comment by hobovsky** [comment]
Hmmm is it?

**Comment by Blind4Basics** [comment]
oh, I believe I misunderstood what you meant about the red gloves...

**Comment by JohanWiltink** [comment]
Hmmm .. lower satisfaction, fewer solves, issues vs. none, fewer languages, published later ( ie duplicate ), author gone vs. active .. the _only thing #1 has going for it is a PHP version - which has all of `165` solves.

If you want to retire one or more of these, do you really need me to tell you to retire #1?

**Comment by hobovsky** [comment]
Yeah I need at least a couple of such opinions because without them, it's just me telling kazk _"uh, me and this other guy want you to retire this kata"_ :D

**Comment by Kacarott** [comment]
I vote to retire 1, keep 2

**Comment by Madjosz** [comment]
Only thing that speaks for 1. is that I find 7kyu more appropriate. Other than that keep 2. and retire 1.

**Comment by EloiseRosen** [comment]
Vote to retire 1, keep 2.

**Comment by hobovsky** [comment]
Okay then, unanimously keep 2., retire 1.
