### ISSUE TITLE
Improve "Valid braces" after deduplication

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#180]
Follow-up on #59 .

"Valid braces" and "Valid parentheses" both suffer from many issues:
- Both are severely misranked, to the point that an easier one is ranked higher than a harder one.
- Tests for edge cases are missing, and random tests have poor coverage.
- Probably many usual issues like not up to date testing frameworks etc.
- Both have many pending translations.
- Both are inconsistent between languages, for example w.r.t. characters other than parentheses.

It would be nice to have the kata fixed, but I think it can be not easy:
- Changing ranks is highly unlikely because both kata have many solutions. The only reasonable way to change ranks would be to recreate kata and move them through beta.
- Interesting cases have to be identified and provided as fixed tests and most probably as dedicated random generators.
- Decide on performance requirements, and complexity of allowed solutions. Should only single pass solutions be allowed, and is this possible to enforce?

Any ideas how to proceed?

**Comment by Kacarott** [comment]
My suggestion would be:
- remake "Valid parentheses" as a 7kyu kata, without any performance constraints. (Therefore, retiring the existing one)
- rework the existing "Valid braces" to require fairly performant solutions, with proper random tests that include edge cases, etc, and leave it at 6kyu.

**Comment by hobovsky** [comment]
The idea of redoing the kata seems to be liked by users, so we can try this, I think. The kata has now 17 approved languages, but I will try to review them and move the ones which are done well.

**Comment by Kacarott** [comment]
The remake is [done](https://www.codewars.com/kata/6411b91a5e71b915d237332d). Now just need to rework "Valid Braces"

**Comment by Kacarott** [comment]
@kazk [This kata](https://www.codewars.com/kata/52774a314c2333f0a7000688) Can now be retired, being replaced by the remake mentioned above.
