### ISSUE TITLE
Deduplicate - IPV4 validator

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#185]
From #39

1. [IP Validation](https://www.codewars.com/kata/515decfd9dcfc23bb6000006)
* 6kyu
* Satisfaction 84% with ~34k completions
* 2 pending issues
* 12 languages, 6 pending translations
* published Apr 2014, author inactive

2. [IPv4 Validator](https://www.codewars.com/kata/57193694938fcdfe3a001dd7)
* 7kyu
* Satisfaction 86% with 800+ completions
* 1 pending issue
* 4 languages, no pending translations (unique Clojure)
* Published Apr 2016, author deleted.

--------

### Conclusion

- Keep 1. [IP Validation](https://www.codewars.com/kata/515decfd9dcfc23bb6000006)
- [x] Retire 2. [IPv4 Validator](https://www.codewars.com/kata/57193694938fcdfe3a001dd7)

**Comment by hobovsky** [comment]
The kata 1. has more error conditions than kata 2. I remember going through a couple of languages in kata 1. in the past and improving tests coverage and test feedback.

I think that 1. should be kept. I think 2. can be retired because it's very similar to 1.

**Comment by JohanWiltink** [comment]
(2) is underspecified and underrated. (1) should mention whitespace as invalid though.

Keep (1), retire (2).

**Comment by hobovsky** [comment]
> (1) should mention whitespace as invalid though.

Yes that's true. If this kata survives, I would try to improve specs and tests related to whitespaces.

**Comment by Madjosz** [comment]
1. could use some more test cases in some languages (e.g. valid `0`s, numbers bigger than the standard numeric MAX values)
2. seems underspecified

--> keep 1., retire 2.

**Comment by hobovsky** [comment]
Moved Clojure translation.
