### ISSUE TITLE
Deduplicate - calculate grade

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#186]
From #39

1. [Grasshopper - Grade book](https://www.codewars.com/kata/55cbd4ba903825f7970000f5)
* 8kyu
* Input is only 3 values
* Satisfaction 92% with 71k completions
* 1 pending issue
* 24 languages, no pending translations
* Published Aug 2015, author inactive

2. [Thinkful - List and Loop Drills: Grade calculator](https://www.codewars.com/kata/586e0dc9b98de0064b000247)
* 7kyu
* Input is an array of arbitrary length
* Satisfaction 87% with 1300+ completions
* No pending issues
* Python only
* Published Jan 2017, author inactive

Marking criteria in both kata are exactly the same.

---------

### Conclusion

- Keep 1. [Grasshopper - Grade book](https://www.codewars.com/kata/55cbd4ba903825f7970000f5)
- [x] Retire 2. [Thinkful - List and Loop Drills: Grade calculator](https://www.codewars.com/kata/586e0dc9b98de0064b000247)

**Comment by hobovsky** [comment]
I think kata 1. is better to keep due to amount of languages. Calculation of an average of an array of numbers is covered by other kata, so having amount of grades fixed to 3 is IMO not too much of a problem.

**Comment by CiprianAmza** [comment]
I agree with hobovsky, keep only the first one.
