### ISSUE TITLE
Deduplicate - string case unification

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#187]
From #39

1. [Fix string case](https://www.codewars.com/kata/5b180e9fedaa564a7000009a)
* 7kyu
* Tie-breaking rule: make string lowercase
* Satisfaction 94% with 23k completions
* 1 pending issue
* 21 languages, no pending translations
* Published Jun 2018, author active

2. [Simple Fun #262: Case Unification](https://www.codewars.com/kata/59126cd3379de6ca5f00019c)
* 7kyu
* No inputs which would result in a tie
* Satisfaction 91% with 700+ completions
* No pending issues
* 3 languages, no pending translations, all covered by kata 1.
* Published May 2017, author active-ish

-------

### Conclusion

- Keep 1. [Fix string case](https://www.codewars.com/kata/5b180e9fedaa564a7000009a)
- [x] Retire 2. [Simple Fun #262: Case Unification](https://www.codewars.com/kata/59126cd3379de6ca5f00019c)

**Comment by hobovsky** [comment]
I think that amount of translations and possibility of ties make the kata 1. worth keeping, and kata 2. unnecessary.

**Comment by CiprianAmza** [comment]
Keep only 1, it has more translations.
