### ISSUE TITLE
Deduplicate - even distribution

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#191]
From #39

1. [Almost Even](https://www.codewars.com/kata/529e2e1f16cb0fcccb000a6b)
* 6kyu
* No invalid inputs
* Satisfaction 93% with ~2.2k completions
* No pending issues
* 5 languages + 1 pending translation (Coffeescript, C exclusive)
* Published Dec 2013, author active

2. [Cut it Clean](https://www.codewars.com/kata/5a39d21cb6cfd70767000086)
* 7kyu
* No invalid inputs
* Satisfaction 85% with 160 completions
* One issue about being a duplicate
* JS only + pending Python translation
* Published Dec 2017, author last active May 2023

3. [Distributing Candies Fairly](https://www.codewars.com/kata/59901cd68fc658ab6c000025)
* 7kyu
* Invalid negative inputs
* Satisfaction 90% with 900 completions
* One issue about being a duplicate
* 6 languages, no pending translations (C++ and Julia exclusive)
* Published Aug 2017, author active

4. [Christmas baubles on the tree](https://www.codewars.com/kata/5856c5f7f37aeceaa100008e)
* 7kyu
* 0 buckets is an invalid input
* Satisfaction 93% with 700 completions
* No pending issues
* 5 languages, no pending translations (Crystal and PHP exclusive)
* Published Dec 2016, author inactive

-----

### Conclusion

- Keep 1. [Almost Even](https://www.codewars.com/kata/529e2e1f16cb0fcccb000a6b)
- [x] Retire 2. [Cut it Clean](https://www.codewars.com/kata/5a39d21cb6cfd70767000086)
- [x] Retire 3. [Distributing Candies Fairly](https://www.codewars.com/kata/59901cd68fc658ab6c000025)
  - [x] Move C++ translation from 3. to 1.
  - [x] Move Julia translation from 3. to 1.
- [x] Retire 4. [Christmas baubles on the tree](https://www.codewars.com/kata/5856c5f7f37aeceaa100008e)
  - [x] Move PHP translation from 4. to 1.
  - [x] Move Crystal translation from 4. to 1.

**Comment by hobovsky** [comment]
Depending on a preferred rank, I would propose:
- Keep 1. as the original, and remove the rest (would be my personal pick), or
- If you think that 7 kyu is a better rank, then keep one of 3. or 4., remove invalid inputs from it, and retire the rest.



I think kata 2. can go as it does not present any additional value over the remaining ones.

**Comment by monadius** [comment]
Keep 1 only.

**Comment by KayleighWasTaken** [comment]
I'd just keep 1. rather than rewriting the spec for 3. or 4.

2. goes in the bin

**Comment by CiprianAmza** [comment]
I would suggest to keep 1 and 4.

**Comment by hobovsky** [comment]
> I would suggest to keep 1 and 4.

Why both of them? Except for their rank, they are identical.

**Comment by CiprianAmza** [comment]
> 

I was thinking that the first one has more completions and the last one has input validation, so not completely identical.
