### ISSUE TITLE
Deduplicate - 12h time to 24h time

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#198]
1. [What time is it?](https://www.codewars.com/kata/57729a09914da60e17000329)
- 7 kyu
- Input is string `"h:mm:ssXM"`, output is string `"HH:mm:ss"`
- Satisfaction 88% with 1300 completions
- 1 pending issue
- 3 languages, 1 pending translation
- Published Jun 2016, author inactive.

2. [Converting 12-hour time to 24-hour time](https://www.codewars.com/kata/59b0a6da44a4b7080300008a/)
- 7 kyu
- input are `(int hours, int  minutes, string am/pm)`, output is string `"HHmm"`
- Satisfaction 87% with 700+ completions
- No pending issues
- 5 languages, no pending translations
- Published Sep 2017, author last active Jun 2023

### Conclusion

- [x] Move C# translation from 1. to 2.
- [x] Move Ruby translation from 1. to 2.
- [x] Retire 1. [What time is it?](https://www.codewars.com/kata/57729a09914da60e17000329)
- Keep 2. [Converting 12-hour time to 24-hour time](https://www.codewars.com/kata/59b0a6da44a4b7080300008a/)

**Comment by hobovsky** [comment]
The core task of both kata is identical, they differ in terms of formatting of input and output.

The way how the kata are now, I have no preference and I think that ideally they could be merged: I like how one requires parsing, and how the other one has more parts (it has seconds), and a nicer formatting. Or maybe the details are different enough to not make these two duplicates of each other?

I have no preference which one to keep, and I think that both have so few languages that they could be easily redone as one kata combining the two if it would result in a better task.

**Comment by ejini6969** [comment]
Keep 2 because it has fresh translations. The extra second adds nothing new because time conversion and formatting has been done in other datetime-related tasks

**Comment by monadius** [comment]
Descriptions of two katas were swapped. I fixed it.

I prefer to keep 2 because it does not require any parsing (parsing is not difficult but it does not add anything to the main task itself).

**Comment by EloiseRosen** [comment]
vote to keep 2, retire 1

**Comment by hobovsky** [comment]
There seems to be agreement on keeping 2. and removign 1.

Thanks.
