### ISSUE TITLE
Deduplicate - Variable assignment

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#199]
1. [Grasshopper - Variable Assignment Debug](https://www.codewars.com/kata/5612e743cab69fec6d000077)
* 8 kyu
* Satisfaction 84% with 18k+ completions
* 1 pending issue
* 7 languages, no pending translations
* Published Oct 2015, author inactive

2. [Basic variable assignment](https://www.codewars.com/kata/50ee6b0bdeab583673000025)
* 8 kyu
* Satisfaction 80% with ~42k completions
* 2 pending issues
* 21 languages + 4 pending translations
* Published Jan 2013, author inactive

----------------

### Conclusion:

- [x] Retire 1. [Grasshopper - Variable Assignment Debug](https://www.codewars.com/kata/5612e743cab69fec6d000077)
- Keep 2. [Basic variable assignment](https://www.codewars.com/kata/50ee6b0bdeab583673000025)

**Comment by hobovsky** [comment]
Both kata are of bug fixing type, and the bug they present is exactly the same. I think that 2. can stay as more complete, and 1. is totally unnecessary. 

After 1. is retired, kata 2. would have to be reviewed, because some languages are missing the bug fixing aspect (COBOL), and some approach it inconsistently to other languages (C).

**Comment by EloiseRosen** [comment]
vote for retire 1, keep 2

**Comment by hobovsky** [comment]
Votes are quite unanimous to retire 1. and keep 2.

Thanks everyone!
