### ISSUE TITLE
What's wrong with these identifiers?

### ISSUE THREAD

**Issue by MobulaKuhlii** [codewars/content-issues#2]
Link: [What's wrong with these identifiers?](https://www.codewars.com/kata/56bb01de0e8b29de50000b19)

Issue: Needs actual description (reading discourse, previous one wasn't of any help either).

**Comment by kazk** [comment]
:man_facepalming: We don't allow authors to delete kata because it's not personal once published and trained on (contains work by other users).

Reverted to original description/solutions and retired.
