### ISSUE TITLE
Deduplicate - split string to n parts

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#202]
From #39

1. [Split In Parts](https://www.codewars.com/kata/5650ab06d11d675371000003)
* 7kyu
* Input is a string, output is a string of space-separated chunks.
* Satisfaction 95% with 6400 completions
* No pending issues
* 7 languages, no pending translations
* Published Nov 2015, author inactive.

2. [String chunks](https://www.codewars.com/kata/55b4f9906ac454650900007d)
* 7kyu
* Input is a string, output is an array of chunks. Chunk length can be invalid.
* Satisfaction 82% with ~950 completions.
* 5 pending issues
* 3 languages + 1 pending translation
* Published Jul 2015, author active.

3. [Cut array into smaller parts](https://www.codewars.com/kata/58ac59d21c9e1d7dc5000150)
* 7kyu
* Input is an array, output is an array of arrays (chunks).
* Satisfaction 89% with 1440 completions.
* 1 pending issue
* 7 languages, no pending translations
* Published Feb 2017, author active.

4. [String Breakers](https://www.codewars.com/kata/59d398bb86a6fdf100000031)
* 6kyu
* Input is a string, output is a string of newline-separated chunks.
* Satisfaction 93% with 2300 completions.
* No pending issues.
* 4 languages + 2 pending translations.
* Published Oct 2017, author active.

------------

### Conclusion

- Keep 1. [Split In Parts](https://www.codewars.com/kata/5650ab06d11d675371000003)
- Keep 3. [Cut array into smaller parts](https://www.codewars.com/kata/58ac59d21c9e1d7dc5000150)
- [x] Retire 2. [String chunks](https://www.codewars.com/kata/55b4f9906ac454650900007d)
- [x] Retire 4. [String Breakers](https://www.codewars.com/kata/59d398bb86a6fdf100000031)
  - [x] Move pending Julia translation to 1.

**Comment by ejini6969** [comment]
Keep 1 (clear specification of inputs being valid), retire 

* 2 (many issues, least completion && language && input validation required)
* 4 (Over-ranked at 6kyu, most similar to 2 except uses `\n`)

I prefer to retire 3, but maybe it is unique enough to stay with different output format.

**Comment by error256** [comment]
Depending on the language, strings may contain multi-codeunit characters, in which case random access is impossible and iterating over characters is required. It's not clear if input contains such characters in the katas, so it's not clear how much strings are different from arrays in this context, although in some languages strings are collections of characters anyway.

**Comment by hobovsky** [comment]
Unfortunately, hardly any kata which works with characters specifies alphabets, ranges, and kinds of characters used, etc. or when they do this, they do this not precisely enough. It's a general problem with authoring practices :(

**Comment by monadius** [comment]
Keep 1 and 3. It is possible to convert strings to char arrays and solve both katas with the same approach. But it is also possible to use regular expressions to solve 1. So I think that both 1 and 3 are valuable for beginners (and for those who like to solve katas in all available languages).

**Comment by EloiseRosen** [comment]
keep 1 and 3 and retire the others sounds fine to me

**Comment by hobovsky** [comment]
There seems to be agreement to keep 1. and 3.
