### ISSUE TITLE
Deduplicate - NATO alphabet

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#204]
From wiki list

1. [NATO Phonetic Alphabet](https://www.codewars.com/kata/54530f75699b53e558002076)
- 7 kyu.
- Inputs are single words of only lowercase letters.
- Satisfaction 92% with 5250 compeltions.
- 3 pending issues, one about being a duplicate of 3.
- 5 languages + 4 pending translations.
- Published Oct 2014, author deleted.

2. [NATO Phonetic Alphabet Ruby](https://www.codewars.com/kata/548113c7d68e97048a00026a)
- 6 kyu.
- Generally just a Ruby translation of 1. with some additional obstacles (characters out of alphabet like punctuation, digits).
- Satisfaction 78% with 76 completions.
- 1 pending issue.
- Ruby only.
- Published Dec 2014, author inactive.

3. [If you can read this...](https://www.codewars.com/kata/586538146b56991861000293)
- 6 kyu
- Inputs are sentences with lowercase letters, punctuation, and spaces.
- Satisfaction 87% with 10k+ completions.
- 8 pending issues.
- 10 languages + 4 pending translations.
- Published Dec 2016, author active.

--------

### Conclusion

- [x] Retire 1. [NATO Phonetic Alphabet](https://www.codewars.com/kata/54530f75699b53e558002076)
- [x] Retire 2. [NATO Phonetic Alphabet Ruby](https://www.codewars.com/kata/548113c7d68e97048a00026a)
- Keep 3. [If you can read this...](https://www.codewars.com/kata/586538146b56991861000293)

**Comment by hobovsky** [comment]
I would definitely retire 2.
Between 1. and 3., I think that I would keep 3. because it has more languages. But it has also many issues, so maybe it will be easier to just transfer/properly add the languages to 1.? I also like the fact that the 3. has sentences rather than single words.

**Comment by armeanco** [comment]
Retire: 
1. [NATO Phonetic Alphabet](https://www.codewars.com/kata/54530f75699b53e558002076)
2. [NATO Phonetic Alphabet Ruby](https://www.codewars.com/kata/548113c7d68e97048a00026a)

**Comment by EloiseRosen** [comment]
vote for keep 3, retire the others

**Comment by awesomeAD1** [comment]
I agree with the others, keep 3.

**Comment by hobovsky** [comment]
Looks like quite unanimous "Keep 3." to me.
