### ISSUE TITLE
Kata trial - retire Bingo Number Caller

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#205]
[Bingo Number Caller](https://www.codewars.com/kata/566d5cf8001db71d7b000022)

- Satisfaction 63%
- 2 pending issues
- 95 completions
- Languages: C# and F#

The kata uses a design which leads to many issues:
- Attempts to test for randomness
- Tests rely on a dependency to a hidden functionality. User solutions fail if they do not go in line with the non-specified component.

Please share your ideas how to proceed with the kata:
- Retire
- Keep its current design and fix (how?)
- Keep the kata and remake the task into something different (IDK, maybe _"accept a number as input and return it in the bingo-format"_, or  something else)

--------

### Conclusion 

- [x] Retire [Bingo Number Caller](https://www.codewars.com/kata/566d5cf8001db71d7b000022).

**Comment by hobovsky** [comment]
My proposal: Retire as FUBAR.

**Comment by awesomeAD1** [comment]
a(u)tomize it.

**Comment by hobovsky** [comment]
5 unanimous votes to retire should be enough to form a conclusion.
