### ISSUE TITLE
Deduplicate - mixed fractions

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#209]
Reported on Discord

1. [Convert Improper Fraction to Mixed Numeral](https://www.codewars.com/kata/574e4175ff5b0a554a00000b)
- 7 kyu
- numerator can be negative, denominator is always positive
- satisfaction 90% with 600 completions
- 3 pending issues
- 3 languages + 7 pending translations
- Published Jun 2016, author inactive

2. [Convert Improper Fraction to Mixed Number](https://www.codewars.com/kata/584acbee7d22f84dc80000e2)
- 7 kyu
- numerator and denominator are positive
- satisfaction 86% with 500 completions
- no pending issues
- 2 languages
- Published Dec 2016, author active

3. [Simple fraction to mixed number converter](https://www.codewars.com/kata/556b85b433fb5e899200003f)
- 5 kyu
- numerators can be negative, zero, or positive. Denominators can be positive, zero (expected error in such case), or negative.
- Satisfaction 90% with 4.5k completions
- no pending issues
- 4 languages + 1 pending translation
- Published May 2015, author active

-----------

### Conclusion

- Keep 1. [Convert Improper Fraction to Mixed Numeral](https://www.codewars.com/kata/574e4175ff5b0a554a00000b)
- [x] Retire 2. [Convert Improper Fraction to Mixed Number](https://www.codewars.com/kata/584acbee7d22f84dc80000e2)
- Keep 3. [Simple fraction to mixed number converter](https://www.codewars.com/kata/556b85b433fb5e899200003f)

**Comment by hobovsky** [comment]
Ideally, I think that keeping only 3. would be enough. I think that if we keep 3., then we do not need 1. or 2., but maybe they can be treated as a simple warm-up before a more demanding task?

**Comment by akar-0** [comment]
3 is the most complete and the others are too close to not be considered dupes IMO. It's overrated though... Can we consider to send it back to beta to reevaluate it? I don't know if there have been recently positive trials in the same sense,

**Comment by CiprianAmza** [comment]
I would say to keep 1 and 3, as they have a different level of difficulty.

**Comment by monadius** [comment]
Keep 1 and 3. 1 is simpler than 3 and solutions of 3 do not work for 1.

**Comment by EloiseRosen** [comment]
Vote for keep 1 and 3.

**Comment by hobovsky** [comment]
It seems that 1. and 3. stay, 2. goes away.

> 3 is the most complete and the others are too close to not be considered dupes IMO. It's overrated though... Can we consider to send it back to beta to reevaluate it? I don't know if there have been recently positive trials in the same sense,

I think it could be possible in a way that it sometimes works, but sometimes fails bad. It already happened that a kata was sent to beta for re-evaluation and didn't make it back and got auto-retired. The kata in question here also has many solutions, what causes a lot of problems while re-ranking.

I think we need some better tools for updating ranks, and I think we need to wait for them and keep the aspect of ranks rather separated from deduplications :(
