### ISSUE TITLE
Rerank: Create a phone number

### ISSUE THREAD

**Issue by the43rddev** [codewars/content-issues#210]
https://www.codewars.com/kata/525f50e3b73515a6db000b83

6kyu, should be 7...

**Comment by hobovsky** [comment]
Unfortunately, currently its not possible to change ranks of old kata which have many solutions. Changing ranks of kata freshly approved with a rank which is obviously off is possible,  but we still need to wait for tools to adjust ranks of old tasks.

**Comment by the43rddev** [comment]
that's surely unfortunate...
