### ISSUE TITLE
To Admins: Please activate Swift 5.9 for Katas

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#212]
### Discussed in https://github.com/codewars/content-issues/discussions/211

<div type='discussions-op-text'>

<sup>Originally posted by **sigmapie8** December  4, 2023</sup>
Currently, we're solving Katas with Swift 5.3 and it would really make our life easier if we get to solve on 5.9 vs 5.3.</div>

**Comment by hobovsky** [comment]
I updated the [Assembly interpreter](https://www.codewars.com/kata/58e61f3d8ff24f774400002c) to check if the compiler bug is gone and yup, it seems to work in 5.9.

**Comment by kazk** [comment]
All published kata were updated.
