### ISSUE TITLE
Retire "Days in the year"

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#216]
Kata: [Days in the year](https://www.codewars.com/kata/56d6c333c9ae3fc32800070f)

The kata attempts to make a practical topic of leap years more challenging by throwing in additional obstacles, but in the result turns the problem into a frankenstein of totally misplaced conditions:
- extends the topic of "leap years" beyond the scope of its applicability (years before modern definition of leap years),
- requires handling of the year 0, which is not a part of Julian calendar, nor (proleptic) Gregorian calendar.

As a result, the kata represents just some modular arithmetic task disguised behind a totally mis-applied theme of calendars.

It is also a close duplicate of [Leap Years](https://www.codewars.com/kata/526c7363236867513f0005ca).

Please vote 👎 to retire or 👍 to keep (with potential ideas for improvements)

-------

Conclusion:

- [x] Retire [Days in the year](https://www.codewars.com/kata/56d6c333c9ae3fc32800070f)

**Comment by KayleighWasTaken** [comment]
Retire as dupe of leap years.

**Comment by wtlgo** [comment]
It's a duplicate, so there's no reason to keep it I think

**Comment by hobovsky** [comment]
This discussion seems to be quite conclusive, so I'm going to close it and request retirement. Thanks for your inputs everyone!

**Comment by VanessaGreene** [comment]
Retired
