### ISSUE TITLE
Restore "Leap Years"

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#217]
[Leap Years](https://www.codewars.com/kata/526c7363236867513f0005ca) has been retired by mistake and should be recovered. Unfortunately, restoring it from the retirement is not straightforward and requires some admin black magic.

The kata is particularly valuable because it's been translated to 50 languages, thoroughly curated, and is a part of my [Authoring examples](https://www.codewars.com/collections/authoring-examples) collection.

**Comment by VanessaGreene** [comment]
Leap Years has now been restored
