### ISSUE TITLE
Kata ”Reversed sequence“ has an incorrect space in its title

### ISSUE THREAD

**Issue by ghost** [codewars/content-issues#221]
In this Kata (https://www.codewars.com/kata/5a00e05cc374cb34d100000d), there‘s an incorrect space after its title.
![image](https://github.com/user-attachments/assets/0bebf449-02a6-4c86-affc-46dea059d637)

**Comment by ejini6969** [comment]
Fixed, though technically not an issue :-)

**Comment by ghost** [comment]
> Fixed, though technically not an issue :-)

Btw, these Katas (https://www.codewars.com/kata/57a2013acf1fa5bfc4000921, https://www.codewars.com/kata/5ae62fcf252e66d44d00008e, https://www.codewars.com/kata/568d0dd208ee69389d000016) have the same issue.
