### ISSUE TITLE
Move to beta: Snake Collision

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#25]
[Snake Collision](http://codewars.com/kata/5ac616ccbc72620a6a000096)

Would it be possible to move this kata back to beta?

It's quite an old one, but I cannot tell when it got approved. It managed to collect three issues in a short time, and has not many completions ( < 40).

**Comment by FArekkusu** [comment]
> It managed to collect three issues in a short time

6 already.

Here's a [direct link to the kata](http://codewars.com/kata/5ac616ccbc72620a6a000096).

**Comment by kazk** [comment]
Done
