### ISSUE TITLE
rerank Consecutive Sum (7-> 6)

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/content-issues#30]
https://www.codewars.com/kata/5f120a13e63b6a0016f1c9d5

having this at 7 kyu is just a joke. Should be 6.

**Comment by kazk** [comment]
@Blind4Basics @monadius @ejini6969 Unapproved. For some reason, I can't approve it at the moment, but you guys should be able to.

**Comment by Blind4Basics** [comment]
it's because of the satisfaction rate: too low (74%)
Unless you can bypass this, it will stay in beta forever... (consequence of the inappropriate rank at approval: beginners became angry at it, forfeited, downvoted it, I guess... :/ )

**Comment by Blind4Basics** [comment]
oh wait... Maybe I can manage it...

**Comment by Blind4Basics** [comment]
nice... Thanks FArekkusu: https://www.codewars.com/kata/5f120a13e63b6a0016f1c9d5/discuss/python#608b49cba52643000763621c
