### ISSUE TITLE
retire Calculator (3 kyu)

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/content-issues#38]
[Calculator](https://www.codewars.com/kata/5235c913397cbf2508000048)

it has been in bad shape for years (with description talking about parentheses, but no tests). Recently updated to add the requirement (which is good), but that makes it pretty close to [evaluate math expressions](https://www.codewars.com/kata/52a78825cdfc2cfc87000005/python) (2 kyu) (iirc, difference is the purple has unary minus in addition).

The 2 kyu is more valuable (diversities/interest of the solutions), so imo, the 3 kyu should be retired.

**Comment by hobovsky** [comment]
Related to #10 

The problem I see here is that retiring this one and keeping "Evaluate math expression" as 2 ku will shift difficulty balance in a wrong direction. 3 kyu is, IMO, a suitable rank for a problem with BEDMAS _and_ unary prefix operators (unary plus and unary minus).

It's the 2 kyu one which should be retired or hardened. I will try to drop a summary of my ideas in #10.

**Comment by Blind4Basics** [comment]
then retire the 3 and rerank the 2? (yeah, impossible with the current process)

If you make the 2 kyu harder, it'll overlap with stuff like interactive interpreters

**Comment by hobovsky** [comment]
> If you make the 2 kyu harder, it'll overlap with stuff like interactive interpreters

I think it won't overlap with REPL kata, because interpreter kata have additional requirements of defining and using user-defined variables and functions. Their scope is larger than just evaluation of an expression.

**Comment by Blind4Basics** [comment]
possible. But then, what to add to this 2 kyu?

**Comment by hobovsky** [comment]
I'll post at #10

**Comment by Blind4Basics** [comment]
retired
