### ISSUE TITLE
Recent Markdown updates broke some invalid code formatting

### ISSUE THREAD

**Issue by XRFXLP** [codewars/content-issues#40]
Lots ( < 50 ) of myjinxin2015's kata has broken markdown formatting (like [this](https://www.codewars.com/kata/5a03cf478ba914e2ad00009e) ), mainly due to ending triple ticks doesn't end at new line (which is syntax error)

![image](https://user-images.githubusercontent.com/23459568/122146050-f0b6ba00-ce73-11eb-9908-095f018da881.png)

Which, as can be seen, makes the whole thing unreadable.

**Comment by kazk** [comment]
Some authors are using triple backticks for inline codespans, but errors should be fixed now.
