### ISSUE TITLE
Kata created by arhigod "inspired" by other sites

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#43]
Author: [arhigod](https://www.codewars.com/users/arhigod)

### CodeForces

 - [x] [Flipping game](https://www.codewars.com/kata/59841e5084533834d6000025) | [Flipping game](https://codeforces.com/problemset/problem/327/A)
 - [x] [Hungry Sequence](https://www.codewars.com/kata/59842c635dacec84e500001d) | [Hungry Sequence](https://codeforces.com/problemset/problem/327/B)
 - [x] [Magic Five](https://www.codewars.com/kata/59843a95b8a720846200009e) | [Magic Five](https://codeforces.com/problemset/problem/327/C)
 - [x] [Obtaining the String](https://www.codewars.com/kata/5bab83fffe6c0c52b8000172) | [Obtaining the String](https://codeforces.com/problemset/problem/1015/B)
 - [x] [Points in Segment](https://www.codewars.com/kata/5baa25f3246d071df90002b7) | [Points in Segments](https://codeforces.com/problemset/problem/1015/A)
 - [x] [Presents](https://www.codewars.com/kata/598d6fd5b383eda05c000046) | [Presents](https://codeforces.com/problemset/problem/136/A)
 - [x] [Permutations](https://www.codewars.com/kata/5993eec34f5d9f2504000051) | [Permutations](https://codeforces.com/problemset/problem/124/B)
 - [x] [Partial Teacher](https://www.codewars.com/kata/59847be2dff3ac9f0200011f) | [Partial Teacher](https://codeforces.com/problemset/problem/67/A)
 - [x] [Restaurant Tables](https://www.codewars.com/kata/598c1bc6a04cd3b8dd000012) | [Restaurant Tables](https://codeforces.com/problemset/problem/828/A)
 - [x] [Replacement](https://www.codewars.com/kata/598d89971928a085c000001a) | [Replacement](https://codeforces.com/problemset/problem/136/C)
 - [x] [String Task](https://www.codewars.com/kata/598ab63c7367483c890000f4) | [String Task](https://codeforces.com/problemset/problem/118/A)
 - [x] [Ternary Logic](https://www.codewars.com/kata/598d79f7b1954bc4cc000028) | [Ternary Logic](https://codeforces.com/problemset/problem/136/B)
 - [x] ~~[Fancy number](https://www.codewars.com/kata/598abbe504c6a8ca2d0000a4)~~ (retired) | [Fancy number](https://codeforces.com/problemset/problem/118/C)
 - [x] ~~[Black Square](https://www.codewars.com/kata/598d61807cccda3cdd00000a/discuss#5f1dc6e16ddabc00243af17e)~~ (retired) | [Black Square](https://codeforces.com/problemset/problem/828/B)
 - [x] ~~[Caesar's Legions](https://www.codewars.com/kata/598c00487beaca86ba000047)~~ (retired) | [Caesar's Legions](https://codeforces.com/problemset/problem/118/D)
 - [x] ~~[Restoration of permutation](https://www.codewars.com/kata/598827ae6b92e7d58f000001)~~ (retired) |  [Restoration of permutation](https://codeforces.com/problemset/problem/67/B)

**Comment by kazk** [comment]
The first one is by a different user #46.

**Comment by hobovsky** [comment]
> The first one is by a different user #46.

Removed from the list.
