### ISSUE TITLE
Kata created by AlexIsHappy "inspired" by other sites

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#44]
Author: [AlexIsHappy](https://www.codewars.com/users/AlexIsHappy)

### CodeForces

 - [x] [Dubstep](https://www.codewars.com/kata/551dc350bf4e526099000ae5) | [Dubstep](https://codeforces.com/contest/208/problem/A)
 - [x] [Double Cola](https://www.codewars.com/kata/551dd1f424b7a4cdae0001f0) | [Double Cola](https://codeforces.com/problemset/problem/82/A)
 - [x] [IQ Test](https://www.codewars.com/kata/552c028c030765286c00007d) | [IQ Test](https://codeforces.com/problemset/problem/25/A)
 - [x] [The Great Game](https://www.codewars.com/kata/553bee3d8234ef49fe000025) | [The Great Game](https://codeforces.com/problemset/problem/409/A)
 - [x] [Vasya - Clerk](https://www.codewars.com/kata/555615a77ebc7c2c8a0000b8) | [Cinema line](https://codeforces.com/problemset/problem/349/A)
 - [x] [Vasya and Stairs](https://www.codewars.com/kata/55251c0d2142d7b4ab000aef) | [Dreamoon and Stairs](https://codeforces.com/problemset/problem/476/A)
 - [x] [Where is Vasya?](https://www.codewars.com/kata/554754ac9d8ac3be120000b2) | [The number of positions](https://codeforces.com/problemset/problem/124/A)
 - [x] [Watermelon](https://www.codewars.com/kata/55192f4ecd82ff826900089e) | [Watermelon](https://codeforces.com/problemset/problem/4/a)
 - [x] ~~[Johny and Trees](https://www.codewars.com/kata/552a79d9bbaaf41f99000fcf)~~ (retired) | [Pashmak and Garden](https://codeforces.com/problemset/problem/459/A)
 - [x] ~~[Vasya and Drinks](https://www.codewars.com/kata/5555f47156d55fba5c000143)~~  (retired) | [Drinks](https://codeforces.com/problemset/problem/200/B)
 - [x] [Vasya in his free time](https://www.codewars.com/kata/559011063089b0d5500001aa) | [Case of the Zeros and Ones](https://codeforces.com/problemset/problem/556/A)
- [x] [Vasya and Plates](https://www.codewars.com/kata/55807d36933247feff00002f) | [Valera and Plates](https://codeforces.com/problemset/problem/369/A)
- [x] [Vasya and System of Equations](https://www.codewars.com/kata/556eed2836b302917b0000a3) | [System of Equations](https://codeforces.com/problemset/problem/214/A)
- [x] [Vasya and Book](https://www.codewars.com/kata/5522ebbd20cc1cf7980014e7) | [Petr and Book](https://codeforces.com/contest/139/problem/A)

**Comment by ejini6969** [comment]
@kazk  Here are four more copied katas from Codeforces by the same author himself!

[Vasya in his free time](https://www.codewars.com/kata/559011063089b0d5500001aa) | [Case of the Zeros and Ones](https://codeforces.com/problemset/problem/556/A)
[Vasya and Plates](https://www.codewars.com/kata/55807d36933247feff00002f) | [Valera and Plates](https://codeforces.com/problemset/problem/369/A)
[Vasya and System of Equations](https://www.codewars.com/kata/556eed2836b302917b0000a3) | [System of Equations](https://codeforces.com/problemset/problem/214/A)
[Vasya and Book](https://www.codewars.com/kata/5522ebbd20cc1cf7980014e7) | [Petr and Book](https://codeforces.com/contest/139/problem/A)

**Comment by kazk** [comment]
:man_facepalming:
Thanks, @ejini6969

**Comment by Paradoxial-Name** [comment]
That makes it all 12 of his katas.
