### ISSUE TITLE
"Does the path cross itself?" - copy of a problem from another site.

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#45]
Kata [Does the path cross itself?](https://www.codewars.com/kata/61765187f1c7eb004b6092f7) is a copy of [335. Self Crossing](https://leetcode.com/problems/self-crossing/) from LeetCode. Problem statement is an exact copy, just as examples.

Author: [alexbprofit](https://www.codewars.com/users/alexbprofit)

Unpublished and moved to draft.

**Comment by kazk** [comment]
Commented out the description.
