### ISSUE TITLE
"Algorithms: Interesting times in Digital Clock display" is a copy of a problem from another website

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#47]
Kata: [Algorithms: Interesting times in Digital Clock display](https://www.codewars.com/kata/58432307cbd22701e3000095/swift) (retired)
Author: [dloomb](https://www.codewars.com/users/dloomb)

The kata is already retired, I create the issue just to keep track of it.

Original notice, from internal chat:

> Received a first (that I know of) DMCA Takedown from Codility for https://www.codewars.com/kata/58432307cbd22701e3000095/swift
> 
> > Identification of Infringed Material
> >
> > The following copyrighted paragraphs have been allegedly copied from the copyrighted work:
> >
> > 1) Link :
> > https://www.codewars.com/kata/58432307cbd22701e3000095
> >
> > Text starting from
> > "the format "HH:MM:SS""
> >
> > to
> > ""22:22:21", "22:22:22", "22:22:23""
> 
> I searched it and Codility didn't come up (it's their private challenge), but found https://www.careercup.com/question?id=6199206977994752
>

**Comment by kazk** [comment]
Duplicate of #7.

Also, in general, please don't quote internal chat messages publicly without asking. Those are usually written quickly, and not meant to be read by others.

**Comment by hobovsky** [comment]
> Duplicate of #7.

🤦 I am an idiot.
