### ISSUE TITLE
Deduplicate "Convert time to words" kata

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#48]
Three very similar kata:

* [Read the time](https://www.codewars.com/kata/5c2b4182ac111c05cf388858)
  * 6kyu
  * 7 languages
  * 560 solves
  * author active
  * time in 24 hour format
* [What time is it?](https://www.codewars.com/kata/596218bb6878a33ca20000aa) 
   * 6kyu
   * Java and JS only
   * 105 solves
   * author active
   * AM && PM involved but can be discarded
* [Speaking clock](https://www.codewars.com/kata/speaking-clock)
  * 6kyu
  * Java && Python only
  * 115 solves
  * author inactive
  * result should be rounded to the next full 5 minutes

**Comment by hobovsky** [comment]
My proposal: Keep "Read the time" as the most complete, but only if the requested format of the answer is correct (grammatically and otherwise), what someone would have to verify. Retire "What time is it?" and "Speaking clock".

**Comment by Kacarott** [comment]
I agree. I am no grammar expert, but the format asked by "Read the time" seems correct to me.

**Comment by error256** [comment]
"Read the time" uses spaces instead of hyphens in numerals like "twenty-one".

**Comment by hobovsky** [comment]
Is this bad/wrong/incorrect?

**Comment by error256** [comment]
As far as I know, using hyphens in this case is the only correct option.

**Comment by hobovsky** [comment]
In this case, I can raise an issue (or rather re-raise it, as it's been raised before and shot down), and if author does not fix it, I'd change it.

What do you think? Raise an issue, screw grammar, or something else?

**Comment by ejini6969** [comment]
Based on previous experience on how the author interacted with issues raised, he/she will just close it without further justification. I think re-raising it won't do any difference, instead maybe we can try to communicate with the user through github or discord and explain him the need of changing the kata's requirements to the correct format although it will invalidate all existing solution across all languages. If they agree, we can retire the other one, if not we can find more alternatives or continue our persuasion towards them !

**Comment by hobovsky** [comment]
It's true that getting some authors to fix issues in their kata was difficult in the past, but I do not want to assume up-front that this will happen here. If necessary, we will find some way to deduplicate these kata: we can pick and fix another one, or we can fix this one by ourselves, possibilities are many. We will think of something if necessary. But still the "Read the time" seems as the best candidate to keep due to amount of available languages and how easy it would be to fix, "What time is it?" is the second candidate.

I think that existing solutions are not really good reason to keep any kata broken. If there's a bug in a kata, then why not fix it? Besides, come on - the kata will get 500 new solutions in no time.

My biggest problem is simply that, as a not native English speaker, I don't want to judge if the grammar of the kata is correct or not. At least two users already said it's wrong, and as soon as any native English speaker confirms that `"twenty nine minutes past one"` is incorrect and should be `"twenty-nine minutes past one"`, I will raise the issue and, if necessary, fix the kata by myself or ask it to be retired as a duplicate.

**Comment by hobovsky** [comment]
After discussing the case with some users most of them seems to be in position that the issue of hyphen is a minor one and should not impact a choice of a candidate to keep.

Okay then, "Read the time" stays, and I will ask the two remaining ones to be retired.

**Comment by kazk** [comment]
Retired
