### ISSUE TITLE
Deduplicate "Multiplication table" kata

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#49]
Both are ranked 6 kyu and have similar satisfaction rating of ~90%.

* [Multiplication table](https://www.codewars.com/kata/534d2f5b5371ecf8d2000a08) - 14 languages, 13k completions, 1 active issue, slightly older. Requires only square tables (N x N).
* [Multiplication Tables](https://www.codewars.com/kata/5432fd1c913a65b28f000342) - 3 languages (all of them covered by the kata above), 7k7 completions, 0.5 active issues. Requires also rectangular tables (M x N).

Retire one? Both? None?
Any improvements needed in the one(s) to be kept?

------

Conclusion:

* Keep [Multiplication table](https://www.codewars.com/kata/534d2f5b5371ecf8d2000a08)
* Get rid of [Multiplication Tables](https://www.codewars.com/kata/5432fd1c913a65b28f000342)

**Comment by scoraig52** [comment]
Did codewars just go down?
Anyway, at first sight, the first kata requires 1 parameter (size) and the 2nd requires both a row and col. The second kata is a bit more flexible in constraints because of this.

**Comment by Fibonaccios** [comment]
404 error
I have solved both, trivial task and both look similar. Maybe resolve the issue on the first one since it has more solves and get rid of the second one?

**Comment by Blind4Basics** [comment]
discord is down too, on my side

**Comment by scoraig52** [comment]
same here

**Comment by CiprianAmza** [comment]
The two katas are actually the same... not sure if we can call it a difference, one requires `n x n` and one `n x m` sizes.  In my opinion, we should keep the first one (more translations and the difference between them is negligible).

**Comment by scoraig52** [comment]
Since both kata's are practically the same, and the first one has a much bigger range of translated languages and submissions, I vote to keep the first one and nuke the 2nd.

**Comment by Kacarott** [comment]
I don't like either kata, but in my opinion, the first one would be preferable as it has a slightly better description, more translations, and the 'extra challenge' that the second one has is negligible.

**Comment by ejini6969** [comment]
The first one also does not have random tests in at least two languages, soo might need further fixing if we opt to keep that one. I also prefer to keep the first one due to the popularity and amount of pending translations.

**Comment by alexbprofit** [comment]
IMO none of these katas should be retired, because second kata is a performance version and advanced version of first.

**Comment by FArekkusu** [comment]
> advanced version of first

There's nothing advanced about replacing one variable with another variable in exactly same code.

> performance version

Lol, what? Is having unreasonable input ranges considered "performance-oriented" now?

___

> the first one would be preferable as it has a slightly better description, more translations

^ This. If you're going to keep one of these, go for the one which has more value (available languages).
