### ISSUE TITLE
Deduplicate - Inversions in an array

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#50]
**Number of inversion**
* [Calculate number of inversions in array](https://www.codewars.com/kata/537529f42993de0e0b00181f)
  * 5 languages
  * 6kyu
  * 940 solves, 93% satisfaction
  * No pending issues
  * Created 2014 (older)
* [Count inversions](https://www.codewars.com/kata/5728a1bc0838ffea270018b2)
  * python only
  * 7kyu
  * 206 solves, 84% satisfaction
  * 2 pending issues
  * Created 2016 (newer)

The two kata have different ranks, and maybe this should be considered when voting for one to be kept.

-----

I think the conclusion is quite clear here:
* Keep [Calculate number of inversions in array](https://www.codewars.com/kata/537529f42993de0e0b00181f)
* Retire [Count inversions](https://www.codewars.com/kata/5728a1bc0838ffea270018b2)

**Comment by hobovsky** [comment]
I have not solved any of these, but I would vote to keep "Calculate number of inversions in array" as a more complete one and get rid of "Count inversions" as a close duplicate, judging by the description.

I am not sure about the rank though (because I have not solved them), so if 6 kyu is seriously overranked maybe it could be made harder or considered for retirement and the other one to be kept.

**Comment by Blind4Basics** [comment]
I'd retire the 7 kyu. The solutions are exactly the same.

the rank, is a bit "meh", but making it harder would mean making it clearly harder than 6, so...

**Comment by CiprianAmza** [comment]
Same solution passes both katas. Definitely a duplicate. I also consider that retiring the 7 kyu one is the best option.

**Comment by ejini6969** [comment]
The second one's input is a tuple while the first one uses an array. This does not change the fact that the first one is more complete and the only issue is to import the solution explicitly in python. So I would suggest to keep the first one and the rank seems appropriate IMO ~

**Comment by alexbprofit** [comment]
> **Number of inversion**
> 
> * [Calculate number of inversions in array](https://www.codewars.com/kata/537529f42993de0e0b00181f)
>   
>   * 5 languages
>   * 6kyu
>   * 940 solves, 93% satisfaction
>   * No pending issues
>   * Created 2014 (older)
> * [Count inversions](https://www.codewars.com/kata/5728a1bc0838ffea270018b2)
>   
>   * python only
>   * 7kyu
>   * 206 solves, 84% satisfaction
>   * 2 pending issues
>   * Created 2016 (newer)
> 
> The two kata have different ranks, and maybe this should be considered when voting for one to be kept.

@hobovsky, i detect also the beta: https://www.codewars.com/kata/537544cb2993de6dd1001afa
only js and its performance version

**Comment by hobovsky** [comment]
Thanks for spotting, but for now, I think the beta can stay. I think the performance version is not bad to have, and community can still evaluate quality of the idea and iterate on the beta. Also betas are easier to get rid of than approved kata.
I will note it down, but we can keep it out of scope of this discussion.

Thanks.
