### ISSUE TITLE
List of beta katas to be unpublished

### ISSUE THREAD

**Issue by ejini6969** [codewars/content-issues#55]
* https://www.codewars.com/kata/58ae5fbed50275c5e6000d6a (duplicate of https://www.codewars.com/kata/57a4d500e298a7952100035d)
* https://www.codewars.com/kata/59bc141962365421fb000101 (duplicate of calculator katas)
* https://www.codewars.com/kata/57f57061e1c0bbab630000f8 (duplicate of https://www.codewars.com/kata/53f103c3ef9ad4014f00013b)
* https://www.codewars.com/kata/5c6f9cbe4185db000c4f1d61 (duplicate of leetcode problem : https://leetcode.com/problems/house-robber/)
* https://www.codewars.com/kata/56d930a9ba01a86d8f0006b7 (duplicate of http://www.codewars.com/kata/ip-validation)
* https://www.codewars.com/kata/582575a1871708bdcd000c00 (duplicate of https://www.codewars.com/kata/goldbachs-conjecture)
* https://www.codewars.com/kata/53ff65fe4a6ac1bae7000f00 (duplicate of https://www.codewars.com/kata/change-machine)
* https://www.codewars.com/kata/5a076c0306d5b664df000009 (duplicate of https://www.codewars.com/kata/drawing-a-cross)

**Comment by Blind4Basics** [comment]
done
