### ISSUE TITLE
Deduplicate "string subsequence"

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#61]
1. [What's in a name?](https://www.codewars.com/kata/59daf400beec9780a9000045)
  * 6kyu
  * check for random word
  * 1691 solutions, 94% satisfaction
  * 3 pending issues
  * 6 languages + 2 pending translations
  * published Oct 2019 (newer), author inactive

2. [The Fool's day](https://www.codewars.com/kata/59a3f82749ae65de2c000050)
  *  6kyu
  * dumbed down when compared to 1. as it checks only for a single, predefined subsequence
  * 299 solutions, 94% satisfaction
  * No pending issues
  * 2 languages + 3 pending translations, but set of languages overlaps with the 1.
  * published Aug 2017 (older), author inactive

First question is, are these two really duplicates, as the second one uses a hardcoded subsequence and allows for solutions with a hardcoded regex?

Bonus: Beta kata [Subsequence of Another](https://www.codewars.com/kata/5ab2b6abe78eee7de600361e), reported by FArekkusu, seems to be almost 1:1 duplicate of 1. (minus case insensitivity), and I unpublished it. Still, its author seems to strongly object. I managed to use just a slightly modified code to solve the beta and "What's in a name", so I see no real point in keeping the beta.

-------

Conclusion:

- Keep [What's in a name?](https://www.codewars.com/kata/59daf400beec9780a9000045)
- [x] Retire [The Fool's day](https://www.codewars.com/kata/59a3f82749ae65de2c000050) as duplicate of 1.
- If you feel it's necessary, retire also the draft of  [Subsequence of Another](https://www.codewars.com/kata/5ab2b6abe78eee7de600361e). It's unpublished now, but there exists a concern that its author will publish it one day because they seem to not agree with the fact that their kata is a duplicate.

**Comment by hobovsky** [comment]
My vote: Retire 2. as an oversimplified duplicate of 1.

I think the rank for 1. is OK, the task might require some googling but overall effort fits 6 kyu IMO.
If 1. would be to stay, its description could possibly use some improvements.

**Comment by ejini6969** [comment]
I agree. Katas which involve static variables (not sure how to phrase it in a more verbose way) and expect some sort of outputs are not good compared to random inputs. So, the 2nd one should be retired plus the reason justified by hob above ~~

**Comment by FArekkusu** [comment]
[This one](https://www.codewars.com/kata/5ab2b6abe78eee7de600361e/python) in beta should be retired too.

**Comment by hobovsky** [comment]
> [This one](https://www.codewars.com/kata/5ab2b6abe78eee7de600361e/python) in beta should be retired too.

Unpublished. Would you have any opinions on the actual topic this, or any other deduplication issues? The more opinions we collect, the more probable we get to some conclusion allowing for actions.

Thanks!

**Comment by FArekkusu** [comment]
> Would you have any opinions on the actual topic

Option 1 has more languages, it seems there aren't any issues with tests, and its description is clearer, so go with it, I guess.

> Unpublished

Since we're supposedly getting rid of duplicates, retiring the beta ones as well seems more logical to me. Considering how the author [believes his kata is not a duplicate and demands people to approve it](https://www.codewars.com/kata/5ab2b6abe78eee7de600361e/discuss/python#60809ab2cdae4d000906b82b), I doubt he'll silently comply with your decision.

**Comment by hobovsky** [comment]
> Considering how the author [believes his kata is not a duplicate and demands people to approve it](https://www.codewars.com/kata/5ab2b6abe78eee7de600361e/discuss/python#60809ab2cdae4d000906b82b), I doubt he'll silently comply with your decision.

Yes I've noticed this, and if the kata gets republished I will ask for its retirement explicitly.
Now thinking of it, I will probably apply for its retirement too then this discussion concludes, I just do not feel it needs to be discussed here. In case of this beta, duplication is obviously clear so lets focus on the approved ones and I will ask for retirement of all dupes except one in a final conclusion.

To explain a bit, participants of deduplication threads are not meant to give some long-winded explanations or justifications, we dont need to discuss obvious cases. The deduplication issues are here to show to admins that there's a common consensus on the matter in the community and decisions are not done single-handedly. Something just as simple as "Keep X, kill Y" will suffice in majority of cases, unless the case is, for some reason, more complicated. The more people votes here, the easier it will be to convince kazk that retiring an approved kata is a result of a common understanding among users.

**Comment by Kacarott** [comment]
I agree with keeping option 1 for the reasons mentioned above, as well as having a more clear description in my opinion.

Regarding the beta, I think it should become more common practice for mods to make final decisions on whether or not betas are duplicates or not, and either resolve issues (with finality) or remove from beta. There are a lot of a *lot* of katas filling up beta, which are essentially pointless to solve due to them being duplicates, but will never reach a low enough satisfaction rate to retire.

**Comment by Blind4Basics** [comment]
yup, keep 1 / retire 2

**Comment by EloiseRosen** [comment]
keep 1 and retire 2 looks good 👍

**Comment by hobovsky** [comment]
Created #74 as a follow-up.
