### ISSUE TITLE
Rerank "Bob's Jump"

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#62]
Kata: [Bob's Jump](https://www.codewars.com/kata/5eea52f43ed68e00016701f3)

258 solutions, 72% satisfaction.

Kata approved some time ago already, but causing problems since then. It got ranked as a 7 kyu because it apparently has a simple solution, but users struggle a lot with getting to it. Tests contain large inputs and call for an efficient solution, while white kata are generally not expect to impose tight performance requirements. The idea for solution does not seem to be easy to find either. Quite low satisfaction rank seems to confirm the concerns.

Request: re-rank the kata to 6 kyu, or move it back to beta so it could be re-ranked by the community.

**Comment by hobovsky** [comment]
I, for one, have no idea how to solve it. Not that I feel defeated by a 7 kyu kata, but it's also not something I'd expect from a 7 kyu kata.

**Comment by Blind4Basics** [comment]
note: this kata is _VERY_ problematic because to rerank it, it needs to be pushed back to beta anyway. Problem is: the satisfaction rate has began to fall into abyss because of the misranking, and if unapproved, it won't get approvable ever again. Unless the votes (or at least enough downvotes) are removed.

about the rank, it's at _the very least_ 6 kyu. I wouldn't mind to have it at 5, actually, but I know most will disagree because of the size of the code.

**Comment by hobovsky** [comment]
Oh i did not consider the fact that satisfaction rating might prevent re-approval. In such case, maybe we could ask to remove votes and start from scratch, or remove votes which were cast after approval?

**Comment by JohanWiltink** [comment]
I know reranking is expensive, but pushing it back to Draft is a means to an end which in this case would not work.

It doesn't need to be pushed back to Draft, it needs to be reranked. To ( 5 or ) 6, I agree with Blind. It requires memoisation or dynamic programming, which are not 7 kyu stuff.

**Comment by Blind4Basics** [comment]
> It doesn't need to be pushed back to Draft, it needs to be reranked.

problem is: to be reranked, it _has_ to be pushed ~~back to draft~~ first (that's the way it works, currently)

edit, scratch that, it has to be pushed back to _BETA_, sorry. Mixing my words... :/

**Comment by Kacarott** [comment]
I agree it is underrated. I believe there has been talk of setting more decisive guidelines for kata ranking? I would propose that one requirement for any white kata is that it *must* be passable with a naive solution.

**Comment by hobovsky** [comment]
I think guys you confused moving to beta and unpublishing to a draft.
Draft would be virtually unrecoverable. A beta,  OTOH, can be approved again.

**Comment by JohanWiltink** [comment]
Oh wait. Sorry.

Wrong terminology, right problem though.

**Comment by kazk** [comment]
Unapproved
