### ISSUE TITLE
Deduplicate "Rock, Paper, Scissors, Lizard, Spock"

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#66]
1. [Rock Paper Scissors Lizard Spock](https://www.codewars.com/kata/57d29ccda56edb4187000052)
  * 7kyu
  * 88% satisfaction, 489 solutions
  * 1 pending issue about being a duplicate
  * 3 languages + 1 pending translation
  * Published Sep 2016, author active

2. [Rock, Paper, Scissor, Lizard, Spock Game](https://www.codewars.com/kata/569651a2d6a620b72e000059)
  * 6kyu
  * The only difference with 1. is that this one is case-insensitive and checks for invalid inputs. 
  * 89% satisfaction, 448 solutions
  * No pending issues
  * 3 languages + 3 pending translations
  * Published Jan 2016, author inactive

Since both kata are nearly identical in terms of requirements, satisfaction, solutions, pending issues, and even publication date, the only criteria affecting the choice for keeping one and  retiring the other are probably ranking, and available languages.

Languages:

![image](https://user-images.githubusercontent.com/23709795/184323905-96f96fad-cd42-42e5-a4ff-ff603eaa2d75.png)

### Conclusion

- Keep 1. [Rock Paper Scissors Lizard Spock](https://www.codewars.com/kata/57d29ccda56edb4187000052)
- [x] Retire 2. [Rock, Paper, Scissor, Lizard, Spock Game](https://www.codewars.com/kata/569651a2d6a620b72e000059)

### Filling gaps

- [x] Move Ruby approved translation from 2. to 1.
- [x] Move Java pending translation from 2. to 1.
- [x] Think of a better description, maybe moving the image from 2. to 1.

**Comment by hobovsky** [comment]
My vote:

This time, I have no clear candidate for keeping, or for retirement. I lean towards keeping 1. because I think the rank is a bit better, and I do not like the input validation in 2. 2. has more languages, but languages present in 2. and missing in 1. can be transferred after deduplication.

**Comment by ejini6969** [comment]
~~This is a hard one to make a decision. The 1st one is a subset of 2nd one, so I lean towards keeping the 2nd one. Plus, the 2nd one has more translations (including pending) and has earlier creation data. Also its rank is more appropriate (it is important for users to check for input validness IMO), but the description needs to be clearer on what inputs are considered to be invalid (can be copied from the 1st one).~~

EDIT: Change my mind, retire 2 due to require effort in transferring languages to 1. (But IMO the picture in 2 should definitely be transferred to 1.)

**Comment by hobovsky** [comment]
~~So I count your vote as "keep and fix 2., retire 1." right?~~

EDIT: ejini changed his vote.

**Comment by Blind4Basics** [comment]
retire 2, because the author is inactive.

**Comment by Madjosz** [comment]
2. uses the wrong word "scissor". This word is only used in plural "scissors" because it's referring to the pair of scissor blades.

**Comment by hobovsky** [comment]
> 2. uses the wrong word "scissor". This word is only used in plural "scissors" because it's referring to the pair of scissor blades.

Oh right, I forgot to raise an issue about this.
But still, it's fixable and can be handled after the deduplication concludes.

**Comment by krishsharma0413** [comment]
**keep and fix 2, retire 1**

for no other reason than more lang support and have more checks and also an image in description.
but what i think makes it 6kyu is not what i am sure of tho maybe derank to 7kyu? also the description isnt as elaborated as the first.

**Comment by EloiseRosen** [comment]
vote for keep 1, retire 2

**Comment by akar-0** [comment]
Keep 1, retire 2, overrranked. Description of 1 can be improved easily.

**Comment by wtlgo** [comment]
I don't think that validation is a necessary part of the such kata. I vote to keep 1

**Comment by Blind4Basics** [comment]
~~retire 2~~ (_edit: oops, I already voted above..._ XD ).

Maybe add the picture of 2 in the description of 1? (it's on imgur)

**Comment by KayleighWasTaken** [comment]
Keep 1, transfer languages from 2.

**Comment by hobovsky** [comment]
Discussion can be concluded as keep 1., retire 2. Before retirement is requested, following changes need to be done:

- Move Ruby approved translation from 2. to 1.
- Move Java pending translation from 2. to 1.
- Think of a better description, maybe moving the image from 2. to 1.

**Comment by EloiseRosen** [comment]
I'll do # 3 (description)

**Comment by hobovsky** [comment]
Moved Ruby
