### ISSUE TITLE
Deduplicate - vowel / consonant count

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#70]
1. [Vowel Count](https://www.codewars.com/kata/54ff3102c1bad923760001f3)
  * 7kyu
  * Inputs with lowercase alpha chars and spaces
  * Satisfaction 88%, 214k solutions
  * 2 pending issues, random tests missing in some languages
  * 25 languages + 3 pending translations
  * Published Mar 2015, author last active Dec 2021

2. [count vowels in a string](https://www.codewars.com/kata/55b105503da095817e0000b6)
  * 7kyu
  * Inputs with lower- and uppercase characters; spaces and asterisks only in fixed test; mixed types in input
  * Satisfaction 88% satisfaction, 1k solutions
  * No pending issues
  * Python and Ruby only
  * Published Jul 2015, author inactive

3. [Count vowels](https://www.codewars.com/kata/57a1dd9fcf1fa5d0d100005f)
  * 7kyu
  * Inputs with lowercase alpha and spaces
  * Satisfaction 74%, 215 solutions
  * One pending issue about missing random tests in all languages
  * Only 3 FP languages: Haskell, F#, OCaml, and only Haskell is present in 1.
  * Published Aug 2016, author active

4. [Count consonants](https://www.codewars.com/kata/564e7fc20f0b53eb02000106)
  * 7kyu
  * Count consonants instead of vowels; inputs contain lowercase characters, and  in fixed tests additionally selection of uppercase and non-alpha chars
  * Satisfaction 91%, 1500 solutions
  * No pending issues
  * 7 languages, no pending translations
  * Published Nov 2015, author inactive

Questions: 
- Is 2. a duplicate or not, if it tests uppercase characters while other kata don't?
- \3. seems to be an exact duplicate of 1., but has almost unique selection of languages. What to do with it?
- Is 4. a duplicate or not, if the difference is consonants instead of vowels?

-----

Conclusion:

 - Keep [Vowel Count](https://www.codewars.com/kata/54ff3102c1bad923760001f3)
 - Keep [Count consonants](https://www.codewars.com/kata/564e7fc20f0b53eb02000106) as it potentially calls for another solution, make random tests consistent with fixed tests.
 - [x] Retire [count vowels in a string](https://www.codewars.com/kata/55b105503da095817e0000b6).
 - [x] Retire [Count vowels](https://www.codewars.com/kata/57a1dd9fcf1fa5d0d100005f), add translations to 1.

**Comment by hobovsky** [comment]
My vote:
- Keep 1. as the most complete of all candidates.
- Retire 2. I think upper- and lower-case letters are not enough of a difference.
- Retire 3., add corresponding translations to 1.
- Retire 4. as its solution (compared to 1.) boils down only to changing the allowed character set (but please see posts below).

**Comment by error256** [comment]
Keep 1, which, among other things, is the oldest, retire 2 and 3.
But I'm not sure about 4: the set of characters to check is larger (discourages using a chain of `==`-`or`) and case-insensitiveness allows using the corresponding regexp flag or case conversions. Are these differences significant for a 7 kyu or not? I'm OK with either choice.

**Comment by hobovsky** [comment]
It's just now when I noticed that 4. tests for uppercase letters in fixed tests. In such case, error256's doubts related to larger character set with case insensitivity are more justified.
I am not sure now. Please say what you think about 4.

**Comment by Blind4Basics** [comment]
* keep 1 and 4 (because, well, "some variety", like error256 pointed out)
* retire 2 and 3

**Comment by ejini6969** [comment]
I agree with B4B (changed my vote)
