### ISSUE TITLE
Deduplicate - Reorder number to maximum

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#79]
1. [Rotate to the max](https://www.codewars.com/kata/579fa665bb9944f9340005d2)
* 7kyu
* Accept string and int as input
* Satisfaction 92%, 1306 solutions
* One pending issue about being a duplicate
* 4 languages, no pending translations
* Published Aug 2016, author deletd

2. [Rearrange Number to Get its Maximum](https://www.codewars.com/kata/563700da1ac8be8f1e0000dc)
* 7kyu
* Valid inputs are defined as `100 <= n < 1000`
* Satisfaction 87%, ~4,7k solutions
* No pending issues
* 8 languages, no pending translations, COBOL exclusive
* Published Nov 2015, author inactive

3. [Form The Largest](https://www.codewars.com/kata/5a4ea304b3bfa89a9900008e)
* 7kyu
* Only ints as inputs
* Satisfaction 92%, ~8.3k solutions
* No pending issues, but a couple of issues about being a duplicate shot down by its author
* 17 languages, no pending translations; Dart
* Published Jan 2018, author is active

4. [Descending Order](https://www.codewars.com/kata/5467e4d82edf8bbf40000155)
* 7kyu
* int as input only
* Satisfaction 89%, ~145k solutions
* 1 pending issue about random tests missing in some languages
* 21 languages, no pending translations; Elixir, F#, R, Scala, Swift exclusive
* Published Nov 2014, author active

5. [noobCode 01: SUPERSIZE ME.... or rather, this integer!](https://www.codewars.com/kata/5709bdd2f088096786000008)
* 8kyu
* int as input only
* Satisfaction 93%, ~11.6k solutions
* No pending issues
* 10 languages + 2 pending translations; CFML exclusive
* Published Apr 2016, author inactive

----------

Conclusion:
- [x] Retire [Rotate to the max](https://www.codewars.com/kata/579fa665bb9944f9340005d2).
- [x] Retire [Rearrange Number to Get its Maximum](https://www.codewars.com/kata/563700da1ac8be8f1e0000dc)
- [x] Retire [Form The Largest](https://www.codewars.com/kata/5a4ea304b3bfa89a9900008e)
- [x] Retire [noobCode 01: SUPERSIZE ME.... or rather, this integer!](https://www.codewars.com/kata/5709bdd2f088096786000008)
- Keep [Descending Order](https://www.codewars.com/kata/5467e4d82edf8bbf40000155) and move unique, retired translations to it.

**Comment by hobovsky** [comment]
I have not solved all kata in all languages, so it's difficult for me to judge quality of particular languages, frameworks being up to date, etc.
For now, I vote 4. to stay as the most complete, with most languages, most solutions, and the oldest. Retire others, and add missing languages to 4.

**Comment by ejini6969** [comment]
*1) should be retired due to usage of strings which add unnecessary complexity to the task
*2) should be retired due to input constraints
*5) should be retired due to kata ranking (should be 7kyu)
*3) & 4) are same but 4) should be kept due to having more languages and completions

If that one is decided to stay, only CFML, Dart and COBOL need to be ported there ~~

**Comment by Blind4Basics** [comment]
I agree: keep 4, retire all the other ones.

**Comment by akar-0** [comment]
I agree too, keep 4 for being the most completed and translated. The only variations on the others are trivial task of input checking or validation with null interest, and make it hard to translate into many languages.

**Comment by EloiseRosen** [comment]
vote to keep 4

**Comment by chinwi00** [comment]
My code works normal in my ide 
But in kata !!! 
descending_order(num):
> diff = True
> > while diff >0:
        number = num
        ascending = "".join(sorted(str(number)))
        descending = "".join(sorted(str(number), reverse=True))
        print(descending)
        next_number = int(descending) - int(ascending)
        diff = number - next_number
        number = next_number

**Comment by Blind4Basics** [comment]
@chinwi00 : that's not (at all) the place for this. post either in the discourse of that kata or go on CW's discord in the `#help-solve` channel.
