### ISSUE TITLE
Deduplicate - Reverse every word in a string

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#80]
1. [All Star Code Challenge #29](https://www.codewars.com/kata/5866ec8b2e8d9cec7e0000bb)
* 7 kyu
* Satisfaction 91%, ~600 solutions
* One pending issue about being a duplicate
* 4 languages, no pending translations
* Published Dec 2016, author inactive

2. [Reverse Letters in Sentence](https://www.codewars.com/kata/57ebdf944cde58f973000405)
* 7 kyu
* Possible leading or trailing spaces
* Satisfaction 92%, ~2800 solutions
* One pending issue about being a duplicate
* 6 languages, no pending translations
* Published Sep 2016, author inactive

3. [Reverse words](https://www.codewars.com/kata/5259b20d6021e9e14c0010d4)
* 7 kyu
* Possible adjacent spaces
* Satisfaction 90%, 52k solutions
* One pending issue about "multi-char glyphs"
* 13 languages, 2 pending translations
* Published Oct 2013, author inactive

------

Conclusion:
 - [x] Retire [All Star Code Challenge #29](https://www.codewars.com/kata/5866ec8b2e8d9cec7e0000bb), move Crystal translation to 3.
 - [x] Retire [Reverse Letters in Sentence](https://www.codewars.com/kata/57ebdf944cde58f973000405), move Clojure translation to 3.
 - Keep [Reverse words](https://www.codewars.com/kata/5259b20d6021e9e14c0010d4).

**Comment by hobovsky** [comment]
Adjacent/leading/trailing spaces would probably make some difference in some languages, but it should not be that difficult to handle to make a difference. I vote to keep 3. as the most complete and retire others.

**Comment by ejini6969** [comment]
I also voted for 3) to stay as not many languages in 1) & 2) would make much difference in different space positions.

If so, only Crystal and Clojure require migrating to the kept one, but several adjustments on space position should be made

**Comment by Blind4Basics** [comment]
same for me.

**Comment by monadius** [comment]
~After solving these kata in most languages, I am confident that 1 is different from 2 and 3. Top solutions of 1 do not work for 2 and 3. It may be considered as an easy version of the other two kata. It is also possible to use the `split` and `join` methods to solve 1 in all languages which support these methods. I propose to retire 2 and keep 1 and 3.~

~JS is an exception: `split`, `join` solutions work for all kata without any adjustments. But I still consider that 1 is useful because `split` works differently in different languages.~

**Comment by hobovsky** [comment]
> JS is an exception: `split`, `join` solutions work for all kata without any adjustments. But I still consider that 1 is useful because `split` works differently in different languages.

Isn't Python also like this? I think I did not have to modify my Python solution to pass any of these?
But I agree that java, c#, cpp, would require different solutions.

**Comment by monadius** [comment]
Python's `split` can be called with and without arguments. Without arguments, it will work for 1 only. It requires a single space argument to pass other two kata. I think it is a valuable lesson for beginners.

**Comment by hobovsky** [comment]
Ah ok you're right, i called it with an argument  and thats why it always worked.

**Comment by Blind4Basics** [comment]
> Top solutions of 1 do not work for 2 and 3. 

And yet I solved the 3 of them with the ___exact___ same solution, both in JS _and_ python. To me they are definitely dups of each others.

**Comment by monadius** [comment]
After thinking more, I changed my mind. It is not difficult to adjust the behavior of `split` to solve all kata. There are many other kata where beginners can learn how `split` works. So I agree with others: retire 1 and 2, keep 3.

**Comment by akar-0** [comment]
I think too 3) only should be conserved for being the most complete and therefore more educational, and the other ones don't differ sufficiently to be maintained.

**Comment by EloiseRosen** [comment]
vote to keep 3
