### ISSUE TITLE
beta trial - All star code challenge 9

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/content-issues#81]
https://www.codewars.com/kata/5864614683f7e6e7830000c1

cons: 
* 250+ completions
* 5 opened issues
* author gone
* python is totally inconsistent with JS
* sort of duplicate
* teaches bad practices (mutate the input)

pros:
* it's a series... ( :/ )

add an emoji to this message: 

:+1:  = fix it
:-1: = nuke it

**Comment by ejini6969** [comment]
It's even a duplicate of another beta -> https://www.codewars.com/kata/5866d90edbca9ae420000145/javascript 

Basically the same thing except this one compares the object's values whereas the other one checks if a property exists in the object.

**Comment by CiprianAmza** [comment]
I think the kata should just be retired. The task is pretty simple and even the description is a little confusing: in Python the description presents an object with a method called "race", but in the tests there is actually a dictionary.

**Comment by Blind4Basics** [comment]
unpublished.
