### ISSUE TITLE
Deduplicate - build a chessboard

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#82]
checkerboard / chessboard

1. [Checkerboard Generation](https://www.codewars.com/kata/53dc08fa8a0c93229400023b) 
* 6kyu.
* Each field is represented by one of `"[r]"` or `"[b]"`.
* Satisfaction 91%, ~1000 solutions.
* 2 pending issues
* 4 languages + 1 pending translation (Clojure)
* Published Aug 2014, author inactive.

2. [Checkered Board](https://www.codewars.com/kata/5650f1a6075b3284120000c0) 
* 6kyu
* Fields are unicode characters (`■` and  `□`). Additional bit of difficulty is added because the color of the top left corner depends on input value `n`. Tests for invalid inputs like strings and negative numbers.
* Satisfaction 90%, ~900 solutions.
* 2 pending issues about outdated frameworks and missing random tests.
* 5 languages (Coffeescript exclusive), no pending translations.
* Published Nov 2015, author inactive.

3. [ChessBoard](https://www.codewars.com/kata/581c894633b9fe465d0000a6) 
* 7kyu
* Fields are represented by a space or `'#'`.
* Satisfaction 92%, 140 solutions.
* 1 pending issue. 
* 1 language, 1 pending translation (PHP exclusive) 
* Published Nov 2016, author inactive.

4. [Chessboard](https://www.codewars.com/kata/5749b82229d16cbc320015fe) 
* 7kyu.
* Fields are represented by `'*'` or `'.'`. Boards can be rectangular.
* Satisfaction 88%, 260 solutions.
* Python only.
* No pending issues, one suggestion mentioning it's a duplicate.
* Published May 2016, author inactive.

5. [Python Checkerboard](https://www.codewars.com/kata/57785441311a24465e000025) 
* 7kyu
* A bug fixing kata presenting a bug sometimes encountered by newbies.
* Satisfaction 89%, 430 solutions.
* 2 languages, 4 pending translations (but they are suspected to not hold to the bugfixing aspect of the kata).
* Published Jul 2016. 

--------

### Conclusion:

- Keep (2) [Checkered Board](https://www.codewars.com/kata/5650f1a6075b3284120000c0).
- [x] Retire (1) [Checkerboard Generation](https://www.codewars.com/kata/53dc08fa8a0c93229400023b). 
- [x] Retire (3) [ChessBoard](https://www.codewars.com/kata/581c894633b9fe465d0000a6) .
- [x] Retire (4) [Chessboard](https://www.codewars.com/kata/5749b82229d16cbc320015fe).
- Keep (5) [Python Checkerboard](https://www.codewars.com/kata/57785441311a24465e000025)  as not a duplicate.
- Move into (2) translations from retired kata which are not yet present there. Consider removing input validation from the task.

**Comment by hobovsky** [comment]
I think the 2. is the most interesting due to a slightly added complexity, and unicode characters. It's also the most complete. The input validation requirement sucks, but maybe can be removed, or left as is. The unicode characters are reported to create some problems in one of languages.

My vote is to keep 2. as the most interesting and most complete, and fix if needed.  1., 3., and 4. are simpler than 2., but still very similar. I think we don't need them if we keep 2.

I think 5. is not a duplicate and should be kept.

**Comment by twilight-sun** [comment]
in spite of description for me ■ and □ works ok in Ruby in kata 2. in Mozilla
maybe that issue now isn't a thing. not sure

**Comment by Kacarott** [comment]
I agree with keeping 2. The input validation is annoying, but it is the best option there. First one has a very strange output, 3 and 4 also have strange outputs and also single languages, 5 is needlessly python specific in its description and title.

**Comment by ejini6969** [comment]
I didn't realize 5 was a bug-fixing kata tho at that time of posting(I even translated it in the wrong way😅) and considered the fact that it expects different output type, it is not a duplicate IMO.

2. should be kept due to reasons above. If so, only C# require migration.

Also, regarding 5. I'll fix my translation sooner or later.

**Comment by EloiseRosen** [comment]
agree with keeping 2 and 5

**Comment by akar-0** [comment]
Keep 2 (though the input validation and the output format can require adaptations for some languages, it can be done individually) for being the most interesting, remove 1,3,4.

No opinion about 5.
