### ISSUE TITLE
Deduplicate "Brainfuck generator" kata

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#84]
1. [Brainfuck generator](https://www.codewars.com/kata/579e646353ba33cce2000093)
* Published Jul 2016, author active.
* No pending issues.
* Pending Rust translation.

2. [Generate BF Program from Target Output](https://www.codewars.com/kata/585ddf096d36a5a143000178)
* Published Dec 2016, author active.
* One pending issue.
* Pending Java translation.

Both kata are very similar: ranked as 6 kyu, and have similar satisfaction (~95%) and completion rate (~100+ solutions). They accept the same type of solutions (the most trivial programs, not optimized for length of code).
Both kata have the same amount of translations and languages, and no overlap between them. Whichever kata gets selected to stay, the other one will have to be merged into it.

-------

Conclusion:

- [x] Retire [Generate BF Program from Target Output](https://www.codewars.com/kata/585ddf096d36a5a143000178)
- Keep [Brainfuck generator](https://www.codewars.com/kata/579e646353ba33cce2000093) and move translations from 2.

**Comment by hobovsky** [comment]
Since both kata are very similar, I vote to keep the older one (i.e. 1.).
As both authors are active, I'd hope they'd help with migration of translations ;)

**Comment by wtlgo** [comment]
I also think we should merge the second one into the first one, and keep the first.

**Comment by Blind4Basics** [comment]
Authors should almost discuss between them to get an agrement. If they cannot, then the community could step up and take over the decision?

**Comment by ejini6969** [comment]
I haven't solved any of them, but I do not have any preference whatsoever.

**Comment by Kacarott** [comment]
I agree with keeping 1. In the case where two katas are of about equivalent quality, the older one should always be prioritised.

**Comment by 2bitsin** [comment]
Author of first one here 
I'm fine with whatever action you take.

**Comment by monadius** [comment]
The second kata has an incorrect BF interpreter (at least in JS): the command `.` does not output `0`.

**Comment by monadius** [comment]
I vote to keep 1 and retire 2. It will be easy to move 2 languages; moreover, this kata deserves more translations.

**Comment by hobovsky** [comment]
Since both authors explicitly stated they will be fine with any decision, I think it's OK to conclude early.
