### ISSUE TITLE
kata trial - Braces status

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/content-issues#86]
Follow up of #59 , this one got forgotten on the way...

[Braces status](https://www.codewars.com/kata/58983deb128a54b530000be6) (author last seen in Feb 2022)
* 6 kyu
* 550 completions
* 4 languages
* 4 opened issues
* supposed to enforce code usage restrictions, but they are badly implemented in most languages
* the intended solution makes it an exact duplicate of some other kata (see #59)

Post your overall opinion by adding an emoji to this message. I can go into details with a complete answer below.
:+1: = keep
:-1: = retire

**Comment by monadius** [comment]
It is essentially the same task as [Valid Braces](https://www.codewars.com/kata/5277c8a221e209d3f6000b56/javascript). Moreover, the regex restriction is not enforced (at least in JS).

**Comment by bestwebua** [comment]
@kazk, @Blind4Basics  Which one of these katas is older?

**Comment by JohanWiltink** [comment]
If you scroll down on the respective description pages, you can see the publication date yourself. It's in the `STATS` block.

**Comment by bestwebua** [comment]
Thanks, @JohanWiltink!
