### ISSUE TITLE
Retire "How low can you go?"

### ISSUE THREAD

**Issue by akar-0** [codewars/content-issues#89]
https://www.codewars.com/kata/52bd8335d9aca8fb16000341

This kata (4 kyu, JS only, ~500 completions) is just a duplicate of [bit counting](https://www.codewars.com/kata/526571aae218b8ee490006f4/javascript) (6 kyu, +147k completions, 14 languages including JS). It has performance requirements that make solutions based on conversion to binary string fail, but however it is still outrageously overranked and is totally spoiled by the other kata (for example [this solution](https://www.codewars.com/kata/reviews/5265c12a1c3e2482920009e2/groups/5399f929fa6656f7c8000eaf)). The *code golf* limit of 144 characters is ridiculous (I need to force my imagination to come up with a solution  that doesn't fit in it, and I'm not even sure it is properly enforced, see final note in description). It should never have been approved.

I propose to just retire it.

----

_See the [last post](https://github.com/codewars/content-issues/issues/89#issuecomment-1101759321) for conclusion._

**Comment by akar-0** [comment]
I didn't remember *bit counting* is already in deduplication process [there](https://github.com/codewars/content-issues/issues/75), should I close this and report the duplicate there? I think it's clear enough to be handled separately and quickly, though.

**Comment by hobovsky** [comment]
> I didn't remember _bit counting_ is already in deduplication process [there](https://github.com/codewars/content-issues/issues/75), should I close this and report the duplicate there? I think it's clear enough to be handled separately and quickly, though.

There's many opinions and votes on #75 already and I think adding this kata there will be a bit late to collect feedback, but I can link this issue from #75 to make tracking easy, and we can collect feedback for this specific kata here. I think it does not matter if both issues get concluded at the same time or not.

About the kata, I agree that it's both overrated and duplicate. My solution is exactly the same for all three kata. I vote to retire.

**Comment by akar-0** [comment]
> ... I can link this issue from https://github.com/codewars/content-issues/issues/75

Agree :)

**Comment by EloiseRosen** [comment]
vote to retire

**Comment by hobovsky** [comment]
Conclusion:

With 7 votes, I think retirement is a good course of action.
