### ISSUE TITLE
Deduplicate LCM

### ISSUE THREAD

**Issue by akar-0** [codewars/content-issues#90]
- 1:  [Least Common Multiple](https://www.codewars.com/kata/5259acb16021e9d8a60010af) (5 kyu, 10 languages, +3000 completions, published Oct 12, 2013)
- 2:  [Find The Minimum Number Divisible by Integers of an Array II](https://www.codewars.com/kata/56f1b3c94d0c330e4a000e95) (5kyu, Python only, 87 completions currently, published Mar 22, 2016)
-  3: [Find The Minimum Number Divisible by Integers of an Array I](https://www.codewars.com/kata/56f245a7e40b70f0e3000130) (6 kyu, Ruby, Python JS, 178 completions currently, published Mar 23, 2016)

The three katas ask to find the least common multiple of a list of numbers (the first kata uses variadic functions in languages that allow it, while the second and third uses a list). 2 and 3 seem mere duplicates; contrary to what the description states, there is no particular performance requirement in 2. The only relevant difference with 1 is that 2 and 3 just include an additional trivial and not pertinent input validation task, with multiple output types (return a string with a given format if some elements are strings not convertible to integers, but ignore `None`...). There seems to be an issue of integer overflow in JS in 3 (see issue raised by monadius in Discourse).

I suggest to simply remove 2 and 3, and keep 1.

-----

### Conclusion

- Keep 1. [Least Common Multiple](https://www.codewars.com/kata/5259acb16021e9d8a60010af)
- [x] Retire 2. [Find The Minimum Number Divisible by Integers of an Array II](https://www.codewars.com/kata/56f1b3c94d0c330e4a000e95)
- [x] Retire 3.  [Find The Minimum Number Divisible by Integers of an Array I](https://www.codewars.com/kata/56f245a7e40b70f0e3000130)

**Comment by ejini6969** [comment]
I believe there are more LCM katas out there other than these three ~~ I'm not sure if it's included in wiki page or my list of dups, will check tmr. Meanwhile I haven't solved the 2nd one, so can't give much comment on that but the last two are indeed annoying to solve due to multiple output types and "so-called fancy" extra requirements......

Also, 1st is overranked, based on today's standard should just be 7kyu or low 6kyu at most, so keeping that one requires re-ranking procedures....

Edit: retire 2 and 3, rerank 1 to 6 / 7kyu ~~

**Comment by akar-0** [comment]
I agree that 1 is overranked, however, if I'm not wrong, currently reranking a kata is a painful process that doesn't end properly many times, and I believe that as long as this has not been improved we should keep separated the two processes (deduplication and reranking), in order to avoid improductive stalemates. Let me know if I'm mistaken. This is a real problem because there are many duplicates on Codewars, and many overranked katas too. Forcing to mix both just encourages the paralysis.

**Comment by EloiseRosen** [comment]
agree with keep 1, remove 2 and 3

**Comment by hobovsky** [comment]
Thanks for creating the issue, and for nice analysis of problems!

I agree with keeping 1 and retiring 2 and 3 as duplicates, with annoying input validation, and bugged with overflow.

**Comment by CiprianAmza** [comment]
I agree with retiring 2 and 3. Maybe re-ranking first one to 6 kyu?

**Comment by Kacarott** [comment]
I did not enjoy 2 or 3 at all. Vote to retire.

**Comment by akar-0** [comment]
> I agree with retiring 2 and 3. Maybe re-ranking first one to 6 kyu?

Currently, there is no other way than sending it back to beta, and getting sufficient new votes to get a new ranking that would be more appropriate. It has been done on several other katas with sometimes bad results. The problem is the old votes remain unless users who already voted change their vote. IMO there are too few beta voters to make sure this would be productive. As I explained to ejini, I believe it's better not to mix the processes of deduplication and reranking.

**Comment by Madjosz** [comment]
Reading the descriptions of 2 & 3 I already lose the interest to solve them.

**Comment by hobovsky** [comment]
Conclusion is very clear to get rid of 2. and 3., and keep 1.
All languages are covered by 1., so there is nothing to be moved.
