### ISSUE TITLE
De-Duplicate "You Got Change?", "Making Change",  "Loose Change".

### ISSUE THREAD

**Issue by el-f** [codewars/content-issues#92]
1.  ["You Got Change?"](https://www.codewars.com/kata/5966f6343c0702d1dc00004c) - 7 Kyu, 5 languages, 1399 completions.
2.  ["Making Change"](https://www.codewars.com/kata/5365bb5d5d0266cd010009be) - 6 Kyu, 5 languages, 1080 completions.
3.  ["Loose Change"](https://www.codewars.com/kata/5571f712ddf00b54420000ee) - 6 Kyu, 4 languages, 3881 completions.

Basically no difference between 1 and 2.
Trivial differences between 1, 2 and 3 (returning dict vs array)

**Comment by ejini6969** [comment]
Already raised there with 3 more katas ~~ ATM Money Counter https://github.com/codewars/content-issues/issues/39, You can close this one for now!

**Comment by el-f** [comment]
> Already raised there with 3 more katas ~~ ATM Money Counter #39, You can close this one for now!

good to know, closing :)
