### ISSUE TITLE
DUPLICATE SUBMISSIONS

### ISSUE THREAD

**Issue by DelroyGayle** [codewars/content-issues#94]
Hello

Whilst staying up late to solve the following kata
https://www.codewars.com/kata/5518a860a73e708c0a000027/ 

Being tired and heavy handed, whilst editing and removing by superfluous comments and console.logs
I inadvertently submitted my work twice when I thought I was clicking 'Attempt'

So I have three versions of my program submitted.
The first two full of various comments and console logs

Whilst the last one is the one I meant to submit.

Please, Please
Could you delete the first two submitted seeing that there are duplicates filled with comments & console logs that don't belong to the final version

Thank you so much

**Comment by ejini6969** [comment]
This is not the right place to request for mods to delete your solution. And apparently as far as I can recall, solutions cannot be deleted but only hidden to not be visible from the solution panel. If you're still inclining on doing so, please come to discord #support-requests to request help from mods!
