### ISSUE TITLE
Retire Ping Pong 

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/content-issues#97]
[Ping Pong](https://www.codewars.com/kata/585aad11f59b3c25500001d4/)

* TS only
* blatant dup of any fizz buzz task
* tests out of date

(note: already listed in the list of dups and in the list of TS kata to update)

* :+1: : retire
* :-1: : keep it

-----------

**Conclusion:** retire.

**Comment by hobovsky** [comment]
Already listed on [wiki of duplicates](https://github.com/Codewars/content-issues/wiki/List-of-Possible-Duplicate-Kata#fizzbuzz), so we need to remember to remove it from there.
