### ISSUE TITLE
Retire Grouping and Counting 

### ISSUE THREAD

**Issue by akar-0** [codewars/content-issues#98]
"Grouping and Counting" https://www.codewars.com/kata/53a452dd0064085711001205/

This kata (6 kyu, Ruby only, ~600 completions, no random tests, outdated version) is just a duplicate of (for example, there may be others) [Counting Array Elements](https://www.codewars.com/kata/5569b10074fe4a6715000054/discuss/ruby) (~6000 completions, 4 languages, including Ruby, no open issue; the only excuse is it was published before). The restrictions (no `array,count / array.length`) don't add any real difficulty to the task (a single loop over the array does the job however).

In brief, overranked, no random tests, clear duplicate. I think it deserves just a quick retirement.

:+1: : keep
:-1: : retire

----

### Conclusion

- [x] Retire as simply a bad kata not worth to fix

**Comment by JohanWiltink** [comment]
The restrictions (a) suck, and (b) prevent translation to at least JS ( because stuff will break if you disable `.length`. Not worth (a) updating and (b) adding random tests.

I voted thumb down: retire it ( Roman style ).

**Comment by Blind4Basics** [comment]
> I voted thumb down: retire it ( Roman style ).

:whistling:  x)
